# Generated by Django 5.2 on 2026-01-12 14:36

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Assigned Driver',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_task_publish', models.BooleanField(default=False)),
                ('dl_task_number', models.CharField(max_length=100)),
                ('dl_task_number_dms', models.CharField(max_length=100)),
                ('dl_task_description', models.CharField(max_length=100)),
                ('dl_task_status_client', models.CharField(choices=[('for_review', 'For Review'), ('customer_confiration_pending', 'Customer Confirmation Pending'), ('0', 'Assigned to Driver'), ('2', 'Delivered'), ('rejected', 'Rejected'), ('9', 'Cancelled')], max_length=100)),
                ('dl_task_status', models.CharField(choices=[('for_review', 'For Review'), ('pending', 'Pending'), ('address_pending', 'Address Pending'), ('customer_confiration_pending', 'Customer Confirmation Pending'), ('customer_delaying', 'Customer make delaying'), ('dl_pending_payment', 'Pending Delivery charge Payment'), ('publish_to_dms', 'Publish to DMS'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=100)),
                ('dl_task_status_dms', models.CharField(choices=[('0', 'Assigned'), ('1', 'Started'), ('2', 'Successful'), ('3', 'Failed'), ('4', 'InProgress/Arrived'), ('6', 'Unassigned'), ('7', 'Accepted/Acknowledged'), ('8', 'Decline'), ('9', 'Cancel'), ('10', 'Deleted')], default=6, max_length=100)),
                ('dl_task_date', models.DateField(auto_now_add=True)),
                ('dl_waight', models.IntegerField(default=1)),
                ('dl_category', models.CharField(blank=True, choices=[('Food', 'Food'), ('Regular', 'Regular'), ('Electronics', 'Electronics'), ('Others', 'Others')], max_length=100)),
                ('dl_speed', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Same Day', 'Same Day'), ('On Demand', 'On Demand'), ('White Glove', 'White Glove')], max_length=100)),
                ('dl_price', models.IntegerField(blank=True, null=True)),
                ('driver_earnings', models.DecimalField(blank=True, decimal_places=2, help_text="Driver's earnings from this delivery (calculated on completion)", max_digits=10, null=True)),
                ('company_commission', models.DecimalField(blank=True, decimal_places=2, help_text="Company's commission from this delivery", max_digits=10, null=True)),
                ('cod_collected', models.BooleanField(default=False, help_text='Whether COD has been collected for this delivery')),
                ('cod_collected_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Actual COD amount collected from customer', max_digits=10)),
                ('cod_collected_at', models.DateTimeField(blank=True, help_text='When COD was collected', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the delivery was completed', null=True)),
                ('earnings_processed', models.BooleanField(default=False, help_text="Whether earnings have been added to driver's wallet")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Task',
            },
        ),
        migrations.CreateModel(
            name='DlAddressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=11)),
                ('area_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dl_zone', models.PositiveIntegerField(blank=True, null=True)),
                ('dl_building', models.PositiveIntegerField(blank=True, null=True)),
                ('dl_street', models.PositiveIntegerField(blank=True, null=True)),
                ('dl_latitude', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True)),
                ('dl_longitude', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True)),
                ('dl_pluscode', models.CharField(blank=True, max_length=50, null=True)),
                ('dl_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('is_villa_compound', models.BooleanField(default=False)),
                ('is_flat', models.BooleanField(default=False)),
                ('is_office', models.BooleanField(default=False)),
                ('dl_task_number', models.CharField(max_length=100)),
                ('dms_id', models.CharField(blank=True, max_length=100, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Address',
            },
        ),
        migrations.CreateModel(
            name='LatLonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.PositiveIntegerField()),
                ('street_number', models.PositiveIntegerField()),
                ('building_number', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lat/Lon Coordinates',
            },
        ),
        migrations.CreateModel(
            name='ShippingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('barcode_data', models.CharField(blank=True, max_length=255, null=True)),
                ('label_file', models.FileField(blank=True, null=True, upload_to=delivery.models.shipping_label_upload_path)),
                ('label_format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('zpl', 'ZPL (Zebra)')], default='png', max_length=10)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_address', models.TextField()),
                ('sender_phone', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_address', models.TextField()),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_zone', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient_street', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient_building', models.PositiveIntegerField(blank=True, null=True)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('printed', 'Printed'), ('attached', 'Attached to Package'), ('void', 'Void')], default='generated', max_length=20)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping Labels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('zone_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Zone Name',
            },
        ),
    ]
