# Generated by Django 5.1.2 on 2024-10-27 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '__first__'),
        ('fleet', '0001_initial'),
        ('orders', '0002_alter_order_cod_status_by_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatLonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.PositiveIntegerField()),
                ('street_number', models.PositiveIntegerField()),
                ('building_number', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.PositiveIntegerField(blank=True, null=True)),
                ('longitude', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': ' LatLons',
            },
        ),
        migrations.CreateModel(
            name='ZoneName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('zone_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Zone Name',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_task_publish', models.BooleanField(default=False)),
                ('dl_task_number', models.CharField(max_length=100)),
                ('dl_task_number_dms', models.CharField(max_length=100)),
                ('dl_task_description', models.CharField(max_length=100)),
                ('dl_task_status_client', models.CharField(choices=[('for_review', 'For Review'), ('customer_confiration_pending', 'Customer Confirmation Pending'), ('0', 'Assigned to Driver'), ('2', 'Delivered'), ('rejected', 'Rejected'), ('9', 'Cancelled')], max_length=100)),
                ('dl_task_status', models.CharField(choices=[('for_review', 'For Review'), ('pending', 'Pending'), ('address_pending', 'Address Pending'), ('customer_confiration_pending', 'Customer Confirmation Pending'), ('customer_delaying', 'Customer make delaying'), ('dl_pending_payment', 'Pending Delivery charge Payment'), ('publish_to_dms', 'Publish to DMS'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=100)),
                ('dl_task_status_dms', models.CharField(choices=[('0', 'Assigned'), ('1', 'Started'), ('2', 'Successful'), ('3', 'Failed'), ('4', 'InProgress/Arrived'), ('6', 'Unassigned'), ('7', 'Accepted/Acknowledged'), ('8', 'Decline'), ('9', 'Cancel'), ('10', 'Deleted')], default=6, max_length=100)),
                ('dl_task_date', models.DateField(auto_now_add=True)),
                ('dl_waight', models.IntegerField(default=1)),
                ('dl_category', models.CharField(blank=True, choices=[('Food', 'Food'), ('Regular', 'Regular'), ('Electronics', 'Electronics'), ('Others', 'Others')], max_length=100)),
                ('dl_speed', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Same Day', 'Same Day'), ('On Demand', 'On Demand'), ('White Glove', 'White Glove')], max_length=100)),
                ('dl_price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.business')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_task', to='orders.order')),
                ('pickup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.pickuplocation')),
            ],
            options={
                'verbose_name_plural': 'Delivery Task',
            },
        ),
        migrations.CreateModel(
            name='AssignedDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver')),
                ('dl_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverytask')),
            ],
            options={
                'verbose_name_plural': 'Assigned Driver',
            },
        ),
        migrations.CreateModel(
            name='DlAddressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=11)),
                ('area_name', models.CharField(max_length=100)),
                ('dl_zone', models.PositiveIntegerField(blank=True)),
                ('dl_building', models.PositiveIntegerField(blank=True)),
                ('dl_street', models.PositiveIntegerField(blank=True)),
                ('dl_latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19)),
                ('dl_longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19)),
                ('dl_pluscode', models.PositiveIntegerField(blank=True, null=True)),
                ('dl_unit', models.CharField(max_length=2)),
                ('is_villa_compound', models.BooleanField(default=False)),
                ('is_flat', models.BooleanField(default=False)),
                ('is_office', models.BooleanField(default=False)),
                ('dl_task_number', models.CharField(max_length=100)),
                ('dms_id', models.CharField(blank=True, max_length=100, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_addresses', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Delivery Address',
            },
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='dl_address_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dl_task', to='delivery.dladdressupdate'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='dl_to_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.dladdressupdate'),
        ),
    ]
