# Generated by Django 5.1.7 on 2025-11-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latlonlist',
            options={'verbose_name_plural': 'Lat/Lon Coordinates'},
        ),
        migrations.AlterField(
            model_name='dladdressupdate',
            name='area_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dladdressupdate',
            name='dl_building',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dladdressupdate',
            name='dl_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='dladdressupdate',
            name='dl_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='dladdressupdate',
            name='dl_pluscode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dladdressupdate',
            name='dl_street',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dladdressupdate',
            name='dl_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dladdressupdate',
            name='dl_zone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latlonlist',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='latlonlist',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True),
        ),
    ]
