# Generated by Django 5.2 on 2026-01-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_initial'),
        ('delivery', '0001_initial'),
        ('fleet', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assigneddriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.business'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_task', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.pickuplocation'),
        ),
        migrations.AddField(
            model_name='assigneddriver',
            name='dl_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverytask'),
        ),
        migrations.AddField(
            model_name='dladdressupdate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_addresses', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='dl_address_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dl_task', to='delivery.dladdressupdate'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='dl_to_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.dladdressupdate'),
        ),
        migrations.AddField(
            model_name='shippinglabel',
            name='delivery_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_labels', to='delivery.deliverytask'),
        ),
        migrations.AddField(
            model_name='shippinglabel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_labels', to='orders.order'),
        ),
        migrations.AddField(
            model_name='shippinglabel',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_labels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='shippinglabel',
            index=models.Index(fields=['label_number'], name='label_number_idx'),
        ),
        migrations.AddIndex(
            model_name='shippinglabel',
            index=models.Index(fields=['order', 'delivery_task'], name='label_order_task_idx'),
        ),
    ]
