# Generated by Django 5.2 on 2026-01-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dladdressupdate',
            name='mobile_no',
            field=models.CharField(max_length=20),
        ),
    ]
