# Generated by Django 5.1.7 on 2025-11-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_latlonlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='cod_collected',
            field=models.BooleanField(default=False, help_text='Whether COD has been collected for this delivery'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='cod_collected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Actual COD amount collected from customer', max_digits=10),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='cod_collected_at',
            field=models.DateTimeField(blank=True, help_text='When COD was collected', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='company_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Company's commission from this delivery", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the delivery was completed', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='driver_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Driver's earnings from this delivery (calculated on completion)", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_processed',
            field=models.BooleanField(default=False, help_text="Whether earnings have been added to driver's wallet"),
        ),
    ]
