# Generated by Django 5.2 on 2026-01-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_extend_mobile_no_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonename',
            options={'ordering': ['zone_number'], 'verbose_name_plural': 'Zone Names'},
        ),
        migrations.CreateModel(
            name='ZoneGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group name (e.g., West Doha, Industrial Area)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the area covered', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zones', models.ManyToManyField(help_text='Zones included in this group', related_name='zone_groups', to='delivery.zonename')),
            ],
            options={
                'verbose_name': 'Zone Group',
                'verbose_name_plural': 'Zone Groups',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
