# Generated by Django 5.1.7 on 2025-12-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def shipping_label_upload_path(instance, filename):
    """Generate upload path for shipping labels"""
    import os
    return os.path.join('shipping_labels', str(instance.order.business.business_code), filename)


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverytask_cod_collected_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('barcode_data', models.CharField(blank=True, max_length=255, null=True)),
                ('label_file', models.FileField(blank=True, null=True, upload_to='shipping_labels/')),
                ('label_format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('zpl', 'ZPL (Zebra)')], default='png', max_length=10)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_address', models.TextField()),
                ('sender_phone', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_address', models.TextField()),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_zone', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient_street', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient_building', models.PositiveIntegerField(blank=True, null=True)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('printed', 'Printed'), ('attached', 'Attached to Package'), ('void', 'Void')], default='generated', max_length=20)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_labels', to='delivery.deliverytask')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_labels', to='orders.order')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Labels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shippinglabel',
            index=models.Index(fields=['label_number'], name='label_number_idx'),
        ),
        migrations.AddIndex(
            model_name='shippinglabel',
            index=models.Index(fields=['order', 'delivery_task'], name='label_order_task_idx'),
        ),
    ]
