# Generated by Django 5.2 on 2026-01-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_add_zone_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonename',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zonename',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zonename',
            name='zone_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
