# Generated by Django 5.2.8 on 2025-12-07 11:01

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_add_shipping_label_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinglabel',
            name='label_file',
            field=models.FileField(blank=True, null=True, upload_to=delivery.models.shipping_label_upload_path),
        ),
    ]
