# Generated by Django 5.2 on 2026-01-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_add_zonename_latlong'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonename',
            options={'ordering': ['zone_number'], 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AddField(
            model_name='zonename',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zonename',
            name='neighbour_zones',
            field=models.ManyToManyField(blank=True, help_text='Adjacent/nearby zones', to='delivery.zonename'),
        ),
        migrations.AddField(
            model_name='zonename',
            name='zone_name_arabic',
            field=models.CharField(blank=True, help_text='Arabic name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zonename',
            name='zone_name',
            field=models.CharField(help_text='English name', max_length=100),
        ),
        migrations.AlterField(
            model_name='zonename',
            name='zone_number',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
