# Generated by Django 5.2 on 2026-01-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_update_zonename_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonename',
            name='polygon',
            field=models.JSONField(blank=True, help_text='Zone boundary coordinates as [[lat, lon], [lat, lon], ...] array', null=True),
        ),
        migrations.AlterField(
            model_name='zonename',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Center point latitude', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zonename',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Center point longitude', max_digits=10, null=True),
        ),
    ]
