# Generated by Django 5.2 on 2026-02-06 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_dladdressupdate_mobile_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonename',
            options={'ordering': ['zone_number'], 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AddField(
            model_name='zonename',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zonename',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Center point latitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zonename',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Center point longitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zonename',
            name='neighbour_zones',
            field=models.ManyToManyField(blank=True, help_text='Adjacent/nearby zones', to='delivery.zonename'),
        ),
        migrations.AddField(
            model_name='zonename',
            name='polygon',
            field=models.JSONField(blank=True, help_text='Zone boundary coordinates as [[lat, lon], [lat, lon], ...] array', null=True),
        ),
        migrations.AddField(
            model_name='zonename',
            name='zone_name_arabic',
            field=models.CharField(blank=True, help_text='Arabic name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zonename',
            name='zone_name',
            field=models.CharField(help_text='English name', max_length=100),
        ),
        migrations.AlterField(
            model_name='zonename',
            name='zone_number',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.CreateModel(
            name='DeliveryTaskQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=100)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='delivery/qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_qrcode', to='delivery.deliverytask')),
            ],
            options={
                'verbose_name': 'Delivery Task QR Code',
                'verbose_name_plural': 'Delivery Task QR Codes',
            },
        ),
        migrations.CreateModel(
            name='ZoneGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group name (e.g., West Doha, Industrial Area)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the area covered', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zones', models.ManyToManyField(help_text='Zones included in this group', related_name='zone_groups', to='delivery.zonename')),
            ],
            options={
                'verbose_name': 'Zone Group',
                'verbose_name_plural': 'Zone Groups',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ZoneArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(help_text='English area name', max_length=150)),
                ('area_name_arabic', models.CharField(blank=True, help_text='Arabic area name', max_length=150, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Area center latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Area center longitude', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(help_text='Parent zone', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='delivery.zonename')),
            ],
            options={
                'verbose_name': 'Zone Area',
                'verbose_name_plural': 'Zone Areas',
                'ordering': ['zone__zone_number', 'area_name'],
                'unique_together': {('zone', 'area_name')},
            },
        ),
    ]
