# Generated by Django 5.2 on 2026-02-06 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_zonename_options_zonename_is_active_and_more'),
        ('fleet', '0006_add_transaction_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='calculated_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='System-calculated driver earnings (before verification)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='cod_settled',
            field=models.BooleanField(default=False, help_text='Whether COD has been submitted/settled with admin'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='cod_settled_at',
            field=models.DateTimeField(blank=True, help_text='When COD was submitted to admin', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_notes',
            field=models.TextField(blank=True, help_text='Staff notes about earnings verification', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_published_at',
            field=models.DateTimeField(blank=True, help_text='When earnings were published and visible to driver', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_settled',
            field=models.BooleanField(default=False, help_text='Whether driver earnings have been settled/paid out'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_settled_at',
            field=models.DateTimeField(blank=True, help_text='When driver earnings were settled', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', help_text='Earnings verification status by staff', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_verified_at',
            field=models.DateTimeField(blank=True, help_text='When earnings were verified by staff', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_verified_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who verified the earnings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='verified_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Staff-verified/adjusted driver earnings', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='dl_task_status',
            field=models.CharField(choices=[('for_review', 'For Review'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('start_ride', 'Start Ride'), ('out_for_delivery', 'Out for Delivery'), ('in_transit', 'In Transit'), ('contacted', 'Contacted & Confirmed'), ('non_reachable', 'Non Reachable'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='dl_task_status_dms',
            field=models.CharField(choices=[('0', 'Assigned'), ('1', 'Started'), ('2', 'Successful'), ('3', 'Failed'), ('4', 'InProgress/Arrived'), ('6', 'Unassigned'), ('7', 'Accepted/Acknowledged'), ('8', 'Decline'), ('9', 'Cancel'), ('10', 'Deleted')], default='6', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='assigneddriver',
            unique_together={('driver', 'dl_task')},
        ),
    ]
