# Generated by Django 5.2 on 2026-01-18 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_add_zonename_polygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(help_text='English area name', max_length=150)),
                ('area_name_arabic', models.CharField(blank=True, help_text='Arabic area name', max_length=150, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Area center latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Area center longitude', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(help_text='Parent zone', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='delivery.zonename')),
            ],
            options={
                'verbose_name': 'Zone Area',
                'verbose_name_plural': 'Zone Areas',
                'ordering': ['zone__zone_number', 'area_name'],
                'unique_together': {('zone', 'area_name')},
            },
        ),
    ]
