# Generated by Django 5.2 on 2026-02-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_deliverytask_calculated_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('fawran', 'Fawran')], default='', help_text='Customer preferred payment method', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='preferred_time',
            field=models.CharField(blank=True, default='', help_text='Customer preferred delivery time slots (comma-separated)', max_length=50),
        ),
    ]
