# Generated by Django 5.2 on 2026-01-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_add_zone_area_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTaskQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=100)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='delivery/qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_qrcode', to='delivery.deliverytask')),
            ],
            options={
                'verbose_name': 'Delivery Task QR Code',
                'verbose_name_plural': 'Delivery Task QR Codes',
            },
        ),
    ]
