# Generated by Django 5.2.9 on 2026-01-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_add_delivery_task_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='dl_task_status',
            field=models.CharField(choices=[('for_review', 'For Review'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('start_ride', 'Start Ride'), ('in_transit', 'In Transit'), ('contacted', 'Contacted'), ('non_reachable', 'Non Reachable'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=100),
        ),
    ]
