# Generated by Django 5.2 on 2026-02-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_deliverytask_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('9am-1pm', '9 AM – 1 PM'), ('2pm-6pm', '2 PM – 6 PM'), ('6pm-10pm', '6 PM – 10 PM')], default='', help_text='Customer preferred delivery time slot', max_length=50),
        ),
    ]
