# Generated by Django 5.2 on 2026-02-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_fix_preferred_time_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytask',
            name='dl_task_number_dms',
        ),
        migrations.RemoveField(
            model_name='deliverytask',
            name='dl_task_status_dms',
        ),
        migrations.RemoveField(
            model_name='dladdressupdate',
            name='dms_id',
        ),
    ]
