# Generated by Django 5.2.9 on 2026-01-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_update_task_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='cod_settled',
            field=models.BooleanField(default=False, help_text='Whether COD has been submitted/settled with admin'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='cod_settled_at',
            field=models.DateTimeField(blank=True, help_text='When COD was submitted to admin', null=True),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='dl_task_status',
            field=models.CharField(choices=[('for_review', 'For Review'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('start_ride', 'Start Ride'), ('in_transit', 'In Transit'), ('contacted', 'Contacted & Confirmed'), ('non_reachable', 'Non Reachable'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=100),
        ),
    ]
