# Generated by Django 5.2 on 2026-02-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_remove_deliverytask_dl_task_number_dms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='cod_client_settled',
            field=models.BooleanField(default=False, help_text='Whether COD has been settled with the business client'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='cod_client_settled_at',
            field=models.DateTimeField(blank=True, help_text='When COD was settled with the business client', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='failed_attempt_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of failed delivery attempts for this task'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='failure_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the failure', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('customer_not_home', 'Customer Not Home'), ('address_not_found', 'Address Not Found'), ('customer_refused', 'Customer Refused Delivery'), ('customer_unreachable', 'Customer Unreachable'), ('vehicle_issue', 'Vehicle / Driver Issue'), ('wrong_address', 'Wrong Address on Order'), ('customer_requested_reschedule', 'Customer Requested Reschedule'), ('cod_amount_dispute', 'COD Amount Disputed'), ('other', 'Other')], help_text='Why the delivery failed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason driver rejected this task', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='reschedule_date',
            field=models.DateField(blank=True, help_text='Rescheduled delivery date after failure', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='reschedule_reason',
            field=models.CharField(blank=True, help_text='Reason for rescheduling', max_length=255, null=True),
        ),
    ]
