# Generated by Django 5.2.9 on 2026-02-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_add_cod_settled_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_settled',
            field=models.BooleanField(default=False, help_text='Whether driver earnings have been settled/paid out'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_settled_at',
            field=models.DateTimeField(blank=True, help_text='When driver earnings were settled', null=True),
        ),
    ]
