# Generated by Django 5.2 on 2026-02-28 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_businessteamjoinrequest'),
        ('delivery', '0012_deliverytask_cod_client_settled_and_more'),
        ('fleet', '0012_remove_driver_driver_code_dms'),
        ('warehouse', '0005_add_dimensions_to_storage_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='hub_warehouse',
            field=models.ForeignKey(blank=True, help_text='Hub warehouse this delivery leg originates from (for hub_delivery tasks).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_delivery_tasks', to='warehouse.warehouselocation'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='task_leg',
            field=models.CharField(choices=[('single', 'Single Leg (Standard)'), ('hub_delivery', 'Hub Delivery — Leg 2 (To Customer)')], default='single', help_text="Leg type: 'single' = standard delivery. 'hub_delivery' = Leg 2 of hub model.", max_length=20),
        ),
        migrations.CreateModel(
            name='HubPickupBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, help_text='e.g. BATCH-20260228-001', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending — awaiting driver assignment'), ('assigned', 'Assigned to driver'), ('accepted', 'Accepted by driver'), ('in_progress', 'Driver on the way to pickup'), ('arrived', 'Driver at pickup location'), ('collected', 'All packages collected'), ('at_hub', 'Delivered to hub'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('driver_earnings', models.DecimalField(decimal_places=2, default=0, help_text='Total earnings for this pickup ride (set by staff).', max_digits=10)),
                ('earnings_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hub_batches', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_pickup_batches', to='fleet.driver')),
                ('hub_warehouse', models.ForeignKey(blank=True, help_text='Hub warehouse where driver drops off all goods.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_batches', to='warehouse.warehouselocation')),
                ('pickup_location', models.ForeignKey(blank=True, help_text='Seller location where driver collects goods.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_batches', to='business.pickuplocation')),
            ],
            options={
                'db_table': 'delivery_hubpickupbatch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='hub_pickup_batch',
            field=models.ForeignKey(blank=True, help_text="Batch that delivered this order's goods to hub (Leg 1 reference).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tasks', to='delivery.hubpickupbatch'),
        ),
    ]
