# Generated by Django 5.2.9 on 2026-02-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_alter_deliverytask_dl_task_status'),
        ('fleet', '0007_remove_drivertransaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='dl_task_status_dms',
            field=models.CharField(choices=[('0', 'Assigned'), ('1', 'Started'), ('2', 'Successful'), ('3', 'Failed'), ('4', 'InProgress/Arrived'), ('6', 'Unassigned'), ('7', 'Accepted/Acknowledged'), ('8', 'Decline'), ('9', 'Cancel'), ('10', 'Deleted')], default='6', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='assigneddriver',
            unique_together={('driver', 'dl_task')},
        ),
    ]
