# Generated by Django 5.2 on 2026-03-02 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_hub_delivery_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='dl_task_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
