# Generated by Django 5.2.11 on 2026-02-04 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_deliverytask_earnings_settled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='calculated_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='System-calculated driver earnings (before verification)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_notes',
            field=models.TextField(blank=True, help_text='Staff notes about earnings verification', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_published_at',
            field=models.DateTimeField(blank=True, help_text='When earnings were published and visible to driver', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', help_text='Earnings verification status by staff', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_verified_at',
            field=models.DateTimeField(blank=True, help_text='When earnings were verified by staff', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='earnings_verified_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who verified the earnings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='verified_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Staff-verified/adjusted driver earnings', max_digits=10, null=True),
        ),
    ]
