# Generated by Django 5.2.11 on 2026-02-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_earnings_verification'),
        ('fleet', '0008_earnings_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('10am-2pm', '10 AM – 2 PM'), ('2pm-6pm', '2 PM – 6 PM'), ('6pm-10pm', '6 PM – 10 PM')], default='', help_text='Customer preferred delivery time slot', max_length=20),
        ),
    ]
