# Generated by Django 5.2.11 on 2026-02-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_deliverytask_preferred_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='preferred_time',
            field=models.CharField(blank=True, default='', help_text='Customer preferred delivery time slots (comma-separated)', max_length=50),
        ),
    ]
