# Generated by Django 5.2 on 2026-03-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_taskstatuspoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='address_accuracy',
            field=models.CharField(blank=True, choices=[('by_customer', 'Confirmed by Customer'), ('by_staff', 'Updated by Staff'), ('geocoded', 'Auto-Geocoded'), ('unverified', 'Unverified')], default='unverified', help_text='Who provided/confirmed the delivery address coordinates', max_length=20),
        ),
    ]
