# Generated by Django 5.2.11 on 2026-02-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_alter_deliverytask_dl_task_status_and_more'),
        ('fleet', '0008_earnings_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('fawran', 'Fawran')], default='', help_text='Customer preferred payment method', max_length=20),
        ),
    ]
