# Generated by Django 5.2.11 on 2026-02-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_deliverytask_payment_method_and_more'),
        ('fleet', '0011_finalize_driver_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='dl_task_status',
            field=models.CharField(choices=[('for_review', 'For Review'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('start_ride', 'Start Ride'), ('out_for_delivery', 'Out for Delivery'), ('in_transit', 'In Transit'), ('contacted', 'Contacted & Confirmed'), ('non_reachable', 'Non Reachable'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='dl_task_status_dms',
            field=models.CharField(choices=[('0', 'Assigned'), ('1', 'Started'), ('2', 'Successful'), ('3', 'Failed'), ('4', 'InProgress/Arrived'), ('6', 'Unassigned'), ('7', 'Accepted/Acknowledged'), ('8', 'Decline'), ('9', 'Cancel'), ('10', 'Deleted')], default='6', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('9am-1pm', '9 AM – 1 PM'), ('2pm-6pm', '2 PM – 6 PM'), ('6pm-10pm', '6 PM – 10 PM')], default='', help_text='Customer preferred delivery time slot', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='assigneddriver',
            unique_together={('driver', 'dl_task')},
        ),
    ]
