# Generated by Django 5.2.11 on 2026-03-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_hub_delivery_fields'),
        ('delivery', '0019_alter_deliverytask_dl_task_status_and_more'),
    ]

    operations = [
    ]
