# Generated by Django 5.2.11 on 2026-03-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_dl_task_date_editable'),
        ('delivery', '0020_merge_20260302_0136'),
    ]

    operations = [
    ]
