# Generated by Django 5.2.11 on 2026-03-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_remove_deliverytask_dl_task_number_dms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='completion_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Driver GPS latitude when task was completed', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='completion_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Driver GPS longitude when task was completed', max_digits=10, null=True),
        ),
    ]
