# Generated by Django 5.2.11 on 2026-03-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_driver_location_model'),
        ('fleet', '0015_driverdocument_document_file_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatusPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=100)),
                ('new_status', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Driver GPS latitude at status change', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Driver GPS longitude at status change', max_digits=10, null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in metres', null=True)),
                ('distance_from_delivery', models.FloatField(blank=True, help_text='Distance from delivery location in km (Haversine)', null=True)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Delivery address latitude at time of status change', max_digits=10, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Delivery address longitude at time of status change', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.driver')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_points', to='delivery.deliverytask')),
            ],
            options={
                'verbose_name': 'Task Status Point',
                'verbose_name_plural': 'Task Status Points',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='tsp_task_ts_idx')],
            },
        ),
    ]
