# Generated by Django 5.2.11 on 2026-03-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_add_address_accuracy_to_delivery_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='address_accuracy',
            field=models.CharField(blank=True, choices=[('by_customer', 'By Customer'), ('by_staff', 'By Staff'), ('by_driver', 'By Driver'), ('geocoded', 'Geocoded'), ('unverified', 'Unverified')], default='unverified', help_text='Who provided/confirmed the delivery address coordinates', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('pos', 'POS'), ('fawran', 'Fawran')], default='', help_text='Customer preferred payment method', max_length=20),
        ),
    ]
