# Generated by Django 5.2.11 on 2026-04-02 06:10

import delivery.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0027_alter_deliverytask_dl_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('photo', 'Delivery Photo'), ('signature', 'Customer Signature'), ('barcode_scan', 'Barcode Scan')], default='photo', max_length=20)),
                ('photo', models.ImageField(upload_to=delivery.models.delivery_proof_upload_path)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('barcode_data', models.CharField(blank=True, default='', help_text='Scanned barcode value', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proofs', to='delivery.deliverytask')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_proof',
                'ordering': ['-created_at'],
            },
        ),
    ]
