# Generated by Django 5.2.11 on 2026-04-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0028_deliveryproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='tracking_token',
            field=models.CharField(blank=True, db_index=True, help_text='Public token for customer tracking page URL', max_length=64, null=True, unique=True),
        ),
    ]
