# Generated by Django 5.2.11 on 2026-04-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0029_deliverytask_tracking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='delivery_distance_flag',
            field=models.BooleanField(default=False, help_text='Flagged: driver completed delivery far from address (>5km)'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='time_slot_missed',
            field=models.BooleanField(default=False, help_text="Delivered outside customer's preferred time slot"),
        ),
    ]
