# Generated by Django 5.2.11 on 2026-04-08 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0030_deliverytask_delivery_distance_flag_and_more'),
        ('fleet', '0021_add_cod_submission_fk_and_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='cod_submission_txn',
            field=models.ForeignKey(blank=True, help_text='The COD submission transaction this task was settled in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_tasks', to='fleet.drivertransaction'),
        ),
    ]
