# Generated by Django 5.2.12 on 2026-04-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0031_add_cod_submission_fk_and_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='payment_split',
            field=models.JSONField(blank=True, help_text='Split COD payment by method: {cash: 100, fawran: 50}', null=True),
        ),
    ]
