# Generated by Django 5.2.12 on 2026-06-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0032_deliverytask_payment_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='dl_task_status',
            field=models.CharField(choices=[('for_review', 'For Review'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('start_ride', 'Start Ride'), ('out_for_delivery', 'Out for Delivery'), ('in_transit', 'In Transit'), ('contacted', 'Contacted & Confirmed'), ('non_reachable', 'Non Reachable'), ('delivered', 'Delivered'), ('partial_delivery', 'Partial Delivery'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('dropsownlost', 'Drops Own Lost')], max_length=100),
        ),
    ]
