# Generated by Django 5.2.12 on 2026-06-30 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0033_add_partial_delivery_status'),
        ('fleet', '0026_alter_drivertransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='cod_client_settle_txn',
            field=models.ForeignKey(blank=True, help_text='The COD client-settlement (business payout) transaction this task was paid in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_settled_tasks', to='fleet.drivertransaction'),
        ),
    ]
