# Generated by Django 5.2.12 on 2026-06-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0034_deliverytask_cod_client_settle_txn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='dl_price',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
