# Generated by Django 5.2.16 on 2026-07-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0035_alter_deliverytask_dl_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='address_accuracy',
            field=models.CharField(blank=True, choices=[('by_customer', 'By Client'), ('by_staff', 'By Staff'), ('by_driver', 'By Driver'), ('geocoded', 'Geocoded'), ('unverified', 'Unverified')], default='unverified', help_text='Who provided/confirmed the delivery address coordinates', max_length=20),
        ),
    ]
