# Generated by Django 5.2.16 on 2026-07-20 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_business_pickup_disposition_default_and_more'),
        ('delivery', '0036_alter_deliverytask_address_accuracy'),
        ('fleet', '0028_alter_drivernotification_notification_type'),
        ('orders', '0053_alter_orderstatushistory_field_name'),
        ('warehouse', '0012_alter_warehouse_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_mode', models.CharField(choices=[('assigned', 'Assigned fleet only'), ('public_pool', 'Public pool')], db_index=True, default='assigned', max_length=20)),
                ('disposition', models.CharField(choices=[('drop', 'Drop at hub'), ('self_deliver', 'Deliver by self'), ('transfer', 'Transfer to another driver')], default='drop', help_text='Preset from the business config at creation; the driver executes it', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('arrived', 'Arrived at Client'), ('collected', 'Collected'), ('dropped', 'Dropped at Hub'), ('handed_off', 'Handed Off'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('transfer_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_tasks', to='business.business')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_tasks', to='fleet.driver')),
                ('drop_warehouse', models.ForeignKey(blank=True, help_text="Hub drop point (default warehouse), used when disposition is 'drop'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_drop_tasks', to='warehouse.warehouselocation')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_task', to='orders.order')),
                ('pickup_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_tasks', to='business.pickuplocation')),
                ('transfer_to_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_pickup_transfers', to='fleet.driver')),
            ],
            options={
                'verbose_name': 'Pickup Task',
                'verbose_name_plural': 'Pickup Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='source_pickup_task',
            field=models.ForeignKey(blank=True, help_text='First-mile pickup task this delivery leg originated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tasks', to='delivery.pickuptask'),
        ),
        migrations.AddIndex(
            model_name='pickuptask',
            index=models.Index(fields=['status', 'pickup_mode'], name='pickup_pool_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuptask',
            index=models.Index(fields=['driver', 'status'], name='pickup_driver_idx'),
        ),
    ]
