# Generated by Django 5.2.16 on 2026-07-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0038_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='cod_reference',
            field=models.CharField(blank=True, default='', help_text='Transfer/terminal reference for electronic COD (Fawran, POS) — the only way to reconcile a collection against the bank', max_length=100),
        ),
    ]
