# Generated by Django 5.2.16 on 2026-07-28 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0039_deliverytask_cod_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='charge_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Client delivery-charge verification status by staff', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='charge_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the client delivery charge was verified by staff', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='charge_verified_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who verified the client delivery charge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_delivery_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='verified_delivery_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Staff-verified/adjusted delivery charge billed to the client (replaces raw dl_price on the client payout)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='dl_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, help_text='System-calculated delivery charge billed to the client (QAR, fils-accurate)', max_digits=10, null=True),
        ),
    ]
