# Generated by Django 5.2.16 on 2026-07-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0040_deliverytask_charge_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='settled_delivery_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Delivery charge actually deducted at the business payout. Frozen at payout time so a later edit to verified_delivery_charge cannot make an issued invoice disagree with the money that moved.', max_digits=10, null=True),
        ),
    ]
