# Generated by Django 5.2.16 on 2026-07-29 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0041_deliverytask_settled_delivery_charge'),
        ('fleet', '0030_businesspayoutdeduction'),
        ('orders', '0057_order_route_distance_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_km', models.FloatField(help_text="Straight-line km between the driver's delivery GPS and the customer's marked location")),
                ('driver_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('driver_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('customer_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('customer_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_accuracy', models.FloatField(blank=True, help_text="Reported accuracy of the driver's fix, in metres — a loose fix is weaker evidence than a tight one", null=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('driver_correct', 'Driver GPS correct — customer pin moved'), ('customer_correct', 'Customer pin correct — driver was away from the drop'), ('both_wrong', 'Both wrong — address needs re-verification'), ('dismissed', 'Not a real discrepancy')], db_index=True, default='pending', max_length=20)),
                ('coords_updated', models.BooleanField(default=False, help_text="Whether approving this review actually moved the order's coordinates")),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_reviews', to='fleet.driver')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_reviews', to='orders.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_reviews', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_review', to='delivery.deliverytask')),
            ],
            options={
                'verbose_name': 'Delivery Location Review',
                'db_table': 'delivery_location_review',
                'ordering': ['-gap_km', '-created_at'],
                'indexes': [models.Index(fields=['status', '-gap_km'], name='dlr_status_gap_idx')],
            },
        ),
    ]
