# Generated by Django 5.2.16 on 2026-07-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0042_deliverylocationreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='dladdressupdate',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
