# Generated by Django 5.2.16 on 2026-08-02 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0043_dladdressupdate_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='cod_reconciled',
            field=models.BooleanField(default=False, help_text='Finance matched the electronic COD leg against the bank/terminal statement'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='cod_reconciled_at',
            field=models.DateTimeField(blank=True, help_text='When the electronic COD leg was reconciled', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='cod_reconciled_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who reconciled the electronic COD leg', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cod_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
    ]
