# Generated by Django 5.2.16 on 2026-08-08 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0044_deliverytask_cod_reconciled_and_more'),
        ('fleet', '0032_alter_drivertransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='charge_invoice',
            field=models.ForeignKey(blank=True, help_text="Charge invoice this delivery's fee was billed on", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='fleet.businesschargeinvoice'),
        ),
    ]
