# Generated by Django 5.2.16 on 2026-08-08 16:32

import core.validators
import delivery.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0045_deliverytask_charge_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryproof',
            name='photo',
            field=models.ImageField(upload_to=delivery.models.delivery_proof_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(10)]),
        ),
        migrations.AlterField(
            model_name='shippinglabel',
            name='label_file',
            field=models.FileField(blank=True, null=True, upload_to=delivery.models.shipping_label_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif', 'pdf']), core.validators.MaxFileSizeValidator(10)]),
        ),
    ]
