# Generated by Django 5.2.16 on 2026-09-08 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0047_alter_deliverytaskqrcode_qrcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='driver_note',
            field=models.TextField(blank=True, default='', help_text='Instruction from the office, shown to the assigned driver on the task sheet.'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='driver_note_at',
            field=models.DateTimeField(blank=True, help_text='When the office note was last sent', null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='driver_note_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who sent the note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_notes_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
