# Generated by Django 5.2.16 on 2026-09-11 21:23
#
# Purpose: Give every customer address row a random URL key.
# Used by: delivery.views.dl_address_link / save_location_data.
# Notes: The public page was addressed by dl_task_number (= the order number),
#        which is sequential and guessable. Existing rows are backfilled in
#        batches so the links keep working after deploy.

import secrets

from django.db import migrations, models


def backfill_tokens(apps, schema_editor):
    DlAddressUpdate = apps.get_model('delivery', 'DlAddressUpdate')
    qs = DlAddressUpdate.objects.filter(access_token__isnull=True).only('id')
    batch = []
    for row in qs.iterator(chunk_size=2000):
        row.access_token = secrets.token_urlsafe(32)
        batch.append(row)
        if len(batch) >= 2000:
            DlAddressUpdate.objects.bulk_update(batch, ['access_token'])
            batch = []
    if batch:
        DlAddressUpdate.objects.bulk_update(batch, ['access_token'])


def clear_tokens(apps, schema_editor):
    # Reverse is a no-op beyond the column drop that follows it.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0048_deliverytask_driver_note_deliverytask_driver_note_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dladdressupdate',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(backfill_tokens, clear_tokens),
    ]
