# Generated by Django 5.2.16 on 2026-09-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0051_backfill_address_area_and_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='task_leg',
            field=models.CharField(choices=[('single', 'Single Leg (Standard)'), ('hub_delivery', 'Hub Delivery — Leg 2 (To Customer)'), ('exchange', 'Exchange — Collect Old, Deliver New')], default='single', help_text="Leg type: 'single' = standard delivery. 'hub_delivery' = Leg 2 of hub model.", max_length=20),
        ),
    ]
