# Generated by Django 5.2.17 on 2026-09-21 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0043_business_return_destination'),
        ('delivery', '0052_alter_deliverytask_task_leg'),
        ('fleet', '0046_driverpushsubscription'),
        ('orders', '0071_alter_orderstatushistory_field_name'),
        ('warehouse', '0012_alter_warehouse_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='dl_task_status',
            field=models.CharField(choices=[('for_review', 'For Review'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('start_ride', 'Start Ride'), ('out_for_delivery', 'Out for Delivery'), ('in_transit', 'In Transit'), ('contacted', 'Contacted & Confirmed'), ('non_reachable', 'Non Reachable'), ('delivered', 'Delivered'), ('partial_delivery', 'Partial Delivery'), ('returned_to_shipper', 'Returned to Shipper'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('dropsownlost', 'Drops Own Lost')], max_length=100),
        ),
        migrations.CreateModel(
            name='ParcelCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('with_driver', 'With driver'), ('in_manifest', 'In return manifest'), ('received', 'Received'), ('disputed', 'Disputed'), ('not_in_custody', 'Driver says not held'), ('lost', 'Lost'), ('voided', 'Voided')], db_index=True, default='with_driver', max_length=20)),
                ('destination_kind', models.CharField(choices=[('hub', 'Ezzy hub / warehouse'), ('business', 'Back to the business')], default='hub', max_length=20)),
                ('destination_source', models.CharField(blank=True, default='', help_text='Which rule chose this destination (ReturnDestination.source)', max_length=64)),
                ('destination_fallback_reason', models.CharField(blank=True, default='', help_text='Why the configured destination could not be used, if it could not', max_length=255)),
                ('destination_overridden', models.BooleanField(default=False, help_text='Staff changed the snapshot by hand from the returns console')),
                ('manifest_reference', models.CharField(blank=True, default='', help_text='Return-manifest or bag number the driver hands in with', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_custodies', to='business.business')),
                ('driver', models.ForeignKey(blank=True, help_text='Who is physically liable for the parcel while custody is open', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_custodies', to='fleet.driver')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_parcel_custodies', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_custodies', to='orders.order')),
                ('pickup_location', models.ForeignKey(blank=True, help_text="Set when destination_kind is 'business'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_custodies', to='business.pickuplocation')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_parcel_custodies', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_custodies', to='orders.returnrequest')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_custodies', to='delivery.deliverytask')),
                ('warehouse_location', models.ForeignKey(blank=True, help_text="Set when destination_kind is 'hub'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_custodies', to='warehouse.warehouselocation')),
            ],
            options={
                'verbose_name': 'Parcel Custody',
                'verbose_name_plural': 'Parcel Custody',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['status', 'destination_kind'], name='custody_status_dest_idx'), models.Index(fields=['driver', 'status'], name='custody_driver_idx'), models.Index(fields=['warehouse_location', 'status'], name='custody_hub_idx'), models.Index(fields=['order'], name='custody_order_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['with_driver', 'in_manifest', 'disputed'])), fields=('task',), name='uniq_open_parcel_custody_per_task')],
            },
        ),
    ]
