# Generated by Django 5.2.17 on 2026-09-21 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0043_business_return_destination'),
        ('delivery', '0053_alter_deliverytask_dl_task_status_parcelcustody'),
        ('fleet', '0047_remove_driver_driver_code_idx_and_more'),
        ('orders', '0071_alter_orderstatushistory_field_name'),
        ('warehouse', '0012_alter_warehouse_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parcelcustody',
            name='uniq_open_parcel_custody_per_task',
        ),
        migrations.AddField(
            model_name='parcelcustody',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, help_text='The hub custody this return run was raised from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forward_legs', to='delivery.parcelcustody'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='task_leg',
            field=models.CharField(choices=[('single', 'Single Leg (Standard)'), ('hub_delivery', 'Hub Delivery — Leg 2 (To Customer)'), ('exchange', 'Exchange — Collect Old, Deliver New'), ('return_to_client', 'Return — Hub to Client')], default='single', help_text="Leg type: 'single' = standard delivery. 'hub_delivery' = Leg 2 of hub model.", max_length=20),
        ),
        migrations.AlterField(
            model_name='parcelcustody',
            name='status',
            field=models.CharField(choices=[('with_driver', 'With driver'), ('in_manifest', 'In return manifest'), ('at_hub', 'At hub — awaiting run to client'), ('received', 'Received'), ('disputed', 'Disputed'), ('not_in_custody', 'Driver says not held'), ('lost', 'Lost'), ('voided', 'Voided')], db_index=True, default='with_driver', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='parcelcustody',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['with_driver', 'in_manifest', 'at_hub', 'disputed'])), fields=('task',), name='uniq_open_parcel_custody_per_task'),
        ),
    ]
