# Generated by Django 5.2.17 on 2026-09-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0054_remove_parcelcustody_uniq_open_parcel_custody_per_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='task_leg',
            field=models.CharField(choices=[('single', 'Single Leg (Standard)'), ('hub_delivery', 'Hub Delivery — Leg 2 (To Customer)'), ('exchange', 'Exchange — Collect Old, Deliver New'), ('return_to_client', 'Return — Hub to Client'), ('collect_from_customer', 'Return — Collect from Customer')], default='single', help_text="Leg type: 'single' = standard delivery. 'hub_delivery' = Leg 2 of hub model.", max_length=24),
        ),
    ]
