# Generated by Django 5.2.17 on 2026-09-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0055_alter_deliverytask_task_leg'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='fee_collected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee collected from the customer in cash (Ezzy revenue)', max_digits=10),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='fee_collected_at',
            field=models.DateTimeField(blank=True, help_text='When the cash delivery fee was collected', null=True),
        ),
    ]
