# Generated by Django 5.2.17 on 2026-10-05 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def keep_current_pool_public(apps, schema_editor):
    """Tasks drivers can take today stay takeable — the new flag must not empty New."""
    DeliveryTask = apps.get_model('delivery', 'DeliveryTask')
    DeliveryTask.objects.filter(
        dl_task_publish=True, driver__isnull=True,
        dl_task_status__in=['pending', 'for_review'],
    ).exclude(order__order_status='cancelled').update(public_pool=True)


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0047_businessapisettings_import_qatar_only'),
        ('delivery', '0056_deliverytask_fee_collected_amount_and_more'),
        ('fleet', '0059_driverdocument_verified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='public_pool',
            field=models.BooleanField(db_default=False, db_index=True, default=False, help_text='Open to every driver with app access (PWA New tab)'),
        ),
        migrations.CreateModel(
            name='TaskAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower runs first')),
                ('task_leg', models.CharField(blank=True, choices=[('single', 'Single Leg (Standard)'), ('hub_delivery', 'Hub Delivery — Leg 2 (To Customer)'), ('exchange', 'Exchange — Collect Old, Deliver New'), ('return_to_client', 'Return — Hub to Client'), ('collect_from_customer', 'Return — Collect from Customer')], max_length=24)),
                ('dl_speed', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Same Day', 'Same Day'), ('On Demand', 'On Demand'), ('White Glove', 'White Glove')], max_length=100)),
                ('action', models.CharField(choices=[('driver', 'Assign to driver'), ('public', 'Send to Public')], default='driver', max_length=10)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignment_rules', to='business.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_assignment_rules', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignment_rules', to='fleet.driver')),
                ('zone_group', models.ForeignKey(blank=True, help_text="Matched on the task's drop-off zone", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignment_rules', to='delivery.zonegroup')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.RunPython(keep_current_pool_public, migrations.RunPython.noop),
    ]
