# Generated by Django 5.2.11 on 2026-03-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='Super admin — can approve driver status changes and other sensitive actions'),
        ),
    ]
