# Generated by Django 5.2.11 on 2026-03-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_is_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTriggerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('whatsapp', 'WhatsApp Notification'), ('webhook', 'Webhook Event'), ('system', 'System Auto-Action')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto Trigger Config',
                'verbose_name_plural': 'Auto Trigger Configs',
                'ordering': ['category', 'trigger_key'],
            },
        ),
    ]
