# Generated by Django 5.2.8 on 2025-11-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_is_business_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
