# Generated by Django 5.2.11 on 2026-03-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_auto_trigger_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotriggerconfig',
            name='action',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
