# Generated by Django 5.2.8 on 2025-11-19 20:08

from django.db import migrations
import random
from datetime import datetime


def generate_user_numbers(apps, schema_editor):
    """Generate user_number for all existing profiles"""
    Profile = apps.get_model('core', 'Profile')
    year = datetime.now().year

    for profile in Profile.objects.filter(user_number__isnull=True):
        # Generate unique user number
        while True:
            random_num = random.randint(100000, 999999)
            user_number = f"EZZY{year}{random_num}"

            # Check if unique
            if not Profile.objects.filter(user_number=user_number).exists():
                profile.user_number = user_number
                profile.save()
                break


def reverse_func(apps, schema_editor):
    """Reverse migration - set user_number to None"""
    Profile = apps.get_model('core', 'Profile')
    Profile.objects.all().update(user_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_user_number'),
    ]

    operations = [
        migrations.RunPython(generate_user_numbers, reverse_func),
    ]
