# Generated by Django 5.2.11 on 2026-03-17 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_action_to_autotriggerconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('action_type', models.CharField(choices=[('whatsapp_message', 'Send WhatsApp Message'), ('webhook_call', 'Call Webhook URL'), ('update_order_status', 'Update Order Status'), ('update_task_status', 'Update Task Status'), ('assign_driver', 'Assign Driver'), ('send_notification', 'Send In-App Notification'), ('create_task', 'Create Delivery Task')], max_length=50)),
                ('action_config', models.JSONField(blank=True, default=dict, help_text='Action parameters: message template, webhook URL, status value, etc.')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='core.autotriggerconfig')),
            ],
            options={
                'verbose_name': 'Auto Flow',
                'verbose_name_plural': 'Auto Flows',
                'ordering': ['-created_at'],
            },
        ),
    ]
