# Generated by Django 5.2 on 2025-12-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20251119_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
