# Generated by Django 5.2.11 on 2026-03-17 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_auto_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFlowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('test', 'Test')], max_length=10)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('result', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.autoflow')),
            ],
            options={
                'verbose_name': 'Auto Flow Log',
                'ordering': ['-executed_at'],
            },
        ),
    ]
