# Generated by Django 5.2.11 on 2026-03-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_auto_flow_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Friendly name (e.g. Main, Support, Sales)', max_length=100)),
                ('instance_name', models.CharField(help_text='Evolution API instance name', max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', help_text='WhatsApp number (e.g. +974 XXXX XXXX)', max_length=30)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default when no instance is specified')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Instance',
                'verbose_name_plural': 'WhatsApp Instances',
                'ordering': ['-is_default', 'label'],
            },
        ),
    ]
