# Generated by Django 5.2.12 on 2026-05-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_whatsappinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoflowlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('test', 'Test'), ('throttled', 'Throttled')], max_length=10),
        ),
        migrations.CreateModel(
            name='AutoFlowThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('pending_count', models.PositiveIntegerField(default=0, help_text='Tasks published since the last message went out.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='throttle', to='core.autoflow')),
            ],
            options={
                'verbose_name': 'Auto Flow Throttle',
            },
        ),
    ]
