# Generated by Django 5.2.12 on 2026-06-30 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_autoflowlog_status_autoflowthrottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotriggerconfig',
            name='whatsapp_instance',
            field=models.ForeignKey(blank=True, help_text='WhatsApp number this trigger sends from (blank = default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='core.whatsappinstance'),
        ),
    ]
