# Generated by Django 5.2.12 on 2026-06-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_autotriggerconfig_whatsapp_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoflowthrottle',
            name='pending_since',
            field=models.DateTimeField(blank=True, help_text='When the current pending batch started accumulating. The digest sends once throttle_minutes elapse from here.', null=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='waha_session',
            field=models.CharField(blank=True, default='', help_text='WAHA session name for this same number (blank = default WAHA session)', max_length=100),
        ),
        migrations.AlterField(
            model_name='autoflowthrottle',
            name='pending_count',
            field=models.PositiveIntegerField(default=0, help_text='Tasks accumulated since the last digest message went out.'),
        ),
    ]
