# Generated by Django 5.2.12 on 2026-06-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_autoflowthrottle_pending_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotriggerconfig',
            name='whatsapp_channel',
            field=models.CharField(blank=True, choices=[('', 'Default (by config)'), ('evolution', 'Evolution API'), ('waha', 'WAHA')], default='', help_text='Channel this trigger sends through (blank = by config).', max_length=20),
        ),
    ]
