# Generated by Django 5.2.16 on 2026-07-18 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_autotriggerconfig_whatsapp_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSenderRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('orders_tasks', 'Orders & Delivery Tasks'), ('marketing', 'Marketing & CRM')], max_length=30, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(blank=True, help_text='WhatsApp number this section sends from (blank = default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_routes', to='core.whatsappinstance')),
            ],
            options={
                'verbose_name': 'WhatsApp Sender Route',
                'verbose_name_plural': 'WhatsApp Sender Routes',
                'ordering': ['section'],
            },
        ),
    ]
