# Generated by Django 5.2.16 on 2026-07-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_whatsappsenderroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsenderroute',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Off = section is not restricted; falls back to the default sender.'),
        ),
    ]
