# Generated by Django 5.2.16 on 2026-07-18 21:15

from django.db import migrations, models


def split_marketing_route(apps, schema_editor):
    """Copy the old combined 'marketing' route to the three new sections."""
    Route = apps.get_model('core', 'WhatsAppSenderRoute')
    old = Route.objects.filter(section='marketing').first()
    if not old:
        return
    for key in ('crm_leads', 'marketing_campaigns', 'followups'):
        Route.objects.get_or_create(
            section=key,
            defaults={'instance': old.instance, 'is_enabled': old.is_enabled},
        )
    old.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_whatsappsenderroute_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsenderroute',
            name='section',
            field=models.CharField(choices=[('orders_tasks', 'Orders & Delivery Tasks'), ('crm_leads', 'CRM & Leads'), ('marketing_campaigns', 'Marketing Campaigns'), ('followups', 'Follow-up Digests')], max_length=30, unique=True),
        ),
        migrations.RunPython(split_marketing_route, migrations.RunPython.noop),
    ]
