# Generated by Django 5.2.16 on 2026-08-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_whatsappsenderroute_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signup_landing_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_referrer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_source',
            field=models.CharField(choices=[('driver_join', 'Driver Join Link'), ('business_join', 'Client Join'), ('team_join', 'Team Join'), ('pricing_inquiry', 'Pricing Inquiry'), ('website', 'Website Visit'), ('direct_login', 'Direct Login'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_source_inferred',
            field=models.BooleanField(default=False, help_text='Source was guessed from the account afterwards, not tracked at signup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_utm',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
