# Generated by Django 5.2.16 on 2026-08-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_signup_landing_path_profile_signup_referrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weak_password',
            field=models.BooleanField(default=False, help_text='Last password seen at login failed the strength rules'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weak_password_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weak_password_skips',
            field=models.PositiveSmallIntegerField(default=0, help_text='Times the user postponed the change-password warning (max 3)'),
        ),
    ]
