# Generated by Django 5.2.16 on 2026-08-01 10:03

from django.db import migrations, models


def grant_all_departments_to_existing_staff(apps, schema_editor):
    """
    Existing staff keep the access they had yesterday.

    The new fields default to False, which would lock every current staff member
    out of every desk the moment the middleware goes live. Backfill all three
    departments so nothing changes on deploy; a super admin then narrows people
    down from the Staff Roles page. Super admins are skipped — they bypass
    departments anyway.
    """
    Profile = apps.get_model('core', 'Profile')
    Profile.objects.filter(is_staff=True).update(
        dept_operations=True, dept_finance=True, dept_marketing=True,
    )


def revoke_all_departments(apps, schema_editor):
    """Reverse half of the backfill; the AddFields drop the columns anyway."""
    Profile = apps.get_model('core', 'Profile')
    Profile.objects.update(
        dept_operations=False, dept_finance=False, dept_marketing=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_weak_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dept_finance',
            field=models.BooleanField(default=False, help_text='Staff department: Finance — COD, settlements, payouts, transactions'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dept_marketing',
            field=models.BooleanField(default=False, help_text='Staff department: Marketing — CRM leads, WhatsApp inbox, pricing inquiries'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dept_operations',
            field=models.BooleanField(default=False, help_text='Staff department: Operations — orders, tasks, drivers, dispatch, warehouse'),
        ),
        migrations.RunPython(
            grant_all_departments_to_existing_staff,
            revoke_all_departments,
        ),
    ]
