# Generated by Django 5.2.16 on 2026-08-01 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_dept_finance_profile_dept_marketing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(db_index=True, help_text='URL name without namespace, e.g. cod_ledger', max_length=100, unique=True)),
                ('namespace', models.CharField(default='workforce', help_text='URL namespace the name belongs to', max_length=50)),
                ('departments', models.CharField(blank=True, default='', help_text="Comma-separated department codes, e.g. 'ops,fin'. 'shared' means every staff member.", max_length=120)),
                ('is_enabled', models.BooleanField(default=True, help_text='Unticked blocks the page for everyone except super admins')),
                ('label', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_department_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Department',
                'verbose_name_plural': 'Page Departments',
                'ordering': ['url_name'],
            },
        ),
    ]
