# Generated by Django 5.2.16 on 2026-08-01 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pagedepartment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Template key from core.message_templates.TEMPLATE_DEFAULTS', max_length=100, unique=True)),
                ('body', models.TextField(blank=True, default='', help_text='Message body; {placeholders} are filled at send time. Blank = code default.')),
                ('is_enabled', models.BooleanField(default=True, help_text='Off = this message is not sent at all.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['key'],
            },
        ),
    ]
