# Generated by Django 5.2.16 on 2026-08-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_messagetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autotriggerconfig',
            options={'ordering': ['department', 'category', 'trigger_key'], 'verbose_name': 'Auto Trigger Config', 'verbose_name_plural': 'Auto Trigger Configs'},
        ),
        migrations.AddField(
            model_name='autotriggerconfig',
            name='department',
            field=models.CharField(choices=[('ops', 'Operations'), ('fin', 'Finance'), ('mkt', 'Marketing'), ('admin', 'Admin / Platform')], db_index=True, default='admin', help_text='Staff desk that owns this trigger (admin = super admin only).', max_length=10),
        ),
    ]
