# Generated by Django 5.2.16 on 2026-08-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_autotriggerconfig_department_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsenderroute',
            name='channel',
            field=models.CharField(choices=[('evolution', 'Evolution API'), ('waha', 'WAHA')], default='evolution', help_text="API this section sends through. WAHA uses the number's WAHA session; Evolution uses its instance name.", max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappsenderroute',
            name='section',
            field=models.CharField(choices=[('orders_tasks', 'Orders & Delivery Tasks'), ('crm_leads', 'CRM — Business Leads'), ('driver_onboarding', 'CRM — Driver Leads & Join Form'), ('marketing_campaigns', 'Marketing Campaigns'), ('followups', 'Follow-up Digests')], max_length=30, unique=True),
        ),
    ]
