# Generated by Django 5.2.16 on 2026-08-08 16:32

import core.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_marketing_auto_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user/avatar.png', null=True, upload_to=core.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(5)]),
        ),
    ]
