# Generated by Django 5.2.16 on 2026-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_profilepicture_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(db_index=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Recipient, partially masked', max_length=30)),
                ('success', models.BooleanField(default=False)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, default='', help_text='Error text, or empty when the send succeeded', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Send Log',
                'verbose_name_plural': 'WhatsApp Send Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
