# Generated by Django 5.2.16 on 2026-08-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_whatsappsendlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsendlog',
            name='channel',
            field=models.CharField(choices=[('evolution', 'Evolution API'), ('waha', 'WAHA')], default='evolution', max_length=20),
        ),
    ]
