# Generated by Django 5.2.16 on 2026-08-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_quote_agreed_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotriggerconfig',
            name='notify_number',
            field=models.CharField(blank=True, default='', help_text='Staff number this alert is delivered TO (blank = default sender number).', max_length=20),
        ),
    ]
