# Generated by Django 5.2.16 on 2026-08-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_inquiry_resume_nudge_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappverification',
            name='verification_type',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('phone_add', 'Phone Number Add'), ('phone_update', 'Phone Number Update'), ('account_verify', 'Account Verification'), ('device_verify', 'Driver Device Verification')], max_length=20),
        ),
    ]
