# Generated by Django 5.2.16 on 2026-09-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_unapproved_order_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_customer',
            field=models.BooleanField(db_index=True, default=False, help_text='Personal sender — books one-off deliveries, has no Business'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
