# Generated by Django 5.2.17 on 2026-09-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_p2p_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional note on when to use it.', max_length=300),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Written by staff on the Messages page (no code default behind it).'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Name on the card and in the send window picker.', max_length=120),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='msg_id',
            field=models.CharField(blank=True, default='', help_text='Staff-facing ID in its own C-series, so it can never collide with a code M-number.', max_length=10),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='section',
            field=models.CharField(blank=True, choices=[('orders_tasks', 'Orders & Delivery Tasks'), ('crm_leads', 'CRM — Business Leads'), ('driver_onboarding', 'CRM — Driver Leads & Join Form'), ('marketing_campaigns', 'Marketing Campaigns'), ('followups', 'Follow-up Digests')], default='', help_text='Sender route it belongs to — decides the number it sends from.', max_length=30),
        ),
    ]
