# Generated by Django 5.2.17 on 2026-10-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_messagetemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lead_manager',
            field=models.BooleanField(db_default=False, default=False, help_text='Lead manager — sees every CRM lead and assigns leads to anyone'),
        ),
    ]
