# Generated by Django 5.2 on 2026-01-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_variant', models.CharField(max_length=100)),
                ('short_code', models.CharField(blank=True, max_length=5, null=True)),
                ('discription', models.CharField(max_length=100)),
                ('color_variants_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Color Variants',
            },
        ),
        migrations.CreateModel(
            name='UnitVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_variant', models.CharField(max_length=100)),
                ('short_code', models.CharField(blank=True, max_length=5, null=True)),
                ('discription', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Unit Variants',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('product_category_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_sku', models.CharField(db_index=True, max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('item_price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('item_discription', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_logo', models.ImageField(blank=True, default='business/product_images/brand_logo_default.jpg', null=True, upload_to='product_images/brand_logo')),
                ('product_image', models.ImageField(blank=True, default='business/product_images/product_image_default.jpg', null=True, upload_to='product_images/product_images')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='business.business')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.colorvariant')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcategory')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unitvariant')),
            ],
            options={
                'verbose_name_plural': 'Products items',
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_inventory', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Product Inventory',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='services_images/default.jpg', null=True, upload_to='services_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', '-created_at'], name='product_business_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['item_sku'], name='product_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='product_barcode_idx'),
        ),
    ]
