# Generated by Django 5.2 on 2026-01-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='6-digit unique product identifier (last 2 digits from business code)', max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/brand_logo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/product_images'),
        ),
    ]
