# Generated by Django 5.1.7 on 2025-11-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_businessprofile_business_linkedin_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_sku',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', '-created_at'], name='product_business_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['item_sku'], name='product_sku_idx'),
        ),
    ]
