# Generated by Django 5.2.11 on 2026-03-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_id_alter_product_brand_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='hex_code',
            field=models.CharField(blank=True, help_text='Hex color code e.g. #FF0000', max_length=7, null=True),
        ),
    ]
