# Generated by Django 5.2.11 on 2026-03-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_colorvariant_hex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='client_names',
            field=models.TextField(blank=True, help_text="Comma-separated alternate names clients use for this product (e.g. 'Oud 50ml, special oud')", null=True),
        ),
    ]
