# Generated by Django 5.2.11 on 2026-04-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_client_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique product identifier: {business_pk}-{5-digit-counter} (e.g. 3-00001)', max_length=10, null=True, unique=True),
        ),
    ]
