# Generated by Django 5.2.11 on 2026-04-02 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_add_product_combo'),
        ('product', '0006_fix_product_id_length_15'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_name', models.CharField(max_length=200)),
                ('combo_sku', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('combo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Bundle price (if different from sum of items)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_combos', to='business.business')),
            ],
            options={
                'db_table': 'product_combo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.productcombo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_memberships', to='product.product')),
            ],
            options={
                'db_table': 'product_comboitem',
                'unique_together': {('combo', 'product')},
            },
        ),
    ]
