# Generated by Django 5.2.16 on 2026-08-08 16:32

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_add_product_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/brand_logo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/product_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(8)]),
        ),
    ]
