# Generated by Django 5.2.16 on 2026-08-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_services_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label_print_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='label_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Shared key for every variant of the same product. Platform product id for imports, {business_pk}-G{n} for manual products.', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_label',
            field=models.CharField(blank=True, default='', help_text="Variant name override, e.g. '50ml / Gift Box'. Blank falls back to colour / size / unit.", max_length=120),
        ),
    ]
