# Generated by Django 5.2 on 2026-01-17 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_add_team_permissions'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerWarehouseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default warehouse for this seller?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this link active?')),
                ('priority', models.IntegerField(default=0, help_text='Selection priority (higher = preferred). Used for auto-selection.')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Special notes about this warehouse-seller relationship')),
            ],
            options={
                'verbose_name': 'Seller Warehouse Link',
                'verbose_name_plural': 'Seller Warehouse Links',
                'ordering': ['business', '-is_default', '-priority', 'warehouse'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Location name (e.g., 'North Gate', 'Main Entrance')", max_length=200)),
                ('code', models.CharField(db_index=True, help_text='Location code within warehouse', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Specific address or directions')),
                ('zone_number', models.IntegerField(blank=True, help_text='Delivery zone number', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this location operational?')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default location for the warehouse?')),
                ('operating_hours', models.TextField(blank=True, help_text='Operating hours for pickup')),
                ('notes', models.TextField(blank=True, help_text='Special instructions for drivers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse Location',
                'verbose_name_plural': 'Warehouse Locations',
                'ordering': ['warehouse', '-is_default', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Fulfillment Center', 'verbose_name_plural': 'Fulfillment Centers'},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='business',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=models.CharField(default='Bahrain', max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_by',
            field=models.ForeignKey(help_text='Staff who created this warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, help_text='Warehouse description and details'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this the default fulfillment center?'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Staff member managing this warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique warehouse code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this warehouse operational?'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(help_text='Fulfillment center name', max_length=200),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active', 'name'], name='wh_fc_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='wh_fc_code_idx'),
        ),
        migrations.AddField(
            model_name='sellerwarehouselink',
            name='business',
            field=models.ForeignKey(help_text='Seller/business using this warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_links', to='business.business'),
        ),
        migrations.AddField(
            model_name='sellerwarehouselink',
            name='linked_by',
            field=models.ForeignKey(help_text='Staff who created this link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouse_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerwarehouselink',
            name='warehouse',
            field=models.ForeignKey(help_text='Fulfillment center serving this seller', on_delete=django.db.models.deletion.CASCADE, related_name='seller_links', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouselocation',
            name='warehouse',
            field=models.ForeignKey(help_text='Parent fulfillment center', on_delete=django.db.models.deletion.CASCADE, related_name='pickup_locations', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='sellerwarehouselink',
            name='default_location',
            field=models.ForeignKey(blank=True, help_text='Default pickup location for this seller at this warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_sellers', to='warehouse.warehouselocation'),
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['warehouse', 'is_active'], name='wh_loc_wh_active_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['zone_number'], name='wh_loc_zone_num_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouselocation',
            unique_together={('warehouse', 'code')},
        ),
        migrations.AddIndex(
            model_name='sellerwarehouselink',
            index=models.Index(fields=['business', 'is_active'], name='wh_link_biz_active_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerwarehouselink',
            index=models.Index(fields=['warehouse', 'is_active'], name='wh_link_wh_active_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerwarehouselink',
            index=models.Index(fields=['business', 'is_default'], name='wh_link_biz_default_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerwarehouselink',
            unique_together={('business', 'warehouse')},
        ),
    ]
