# Generated by Django 5.2 on 2026-02-13 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_pickuplocation_warehouse'),
        ('product', '0002_product_product_id_alter_product_brand_logo_and_more'),
        ('warehouse', '0003_sellerwarehouselink_warehouselocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('request_type', models.CharField(choices=[('inbound', 'Inbound - To Warehouse'), ('outbound', 'Outbound - From Warehouse')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_delivery_date', models.DateField(blank=True, help_text='When business plans to deliver products', null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests', to='business.business')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Target warehouse for this request', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Inbound Product Request',
                'verbose_name_plural': 'Inbound Product Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('request_type', models.CharField(choices=[('inbound', 'Inbound - To Warehouse'), ('outbound', 'Outbound - From Warehouse')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests', to='business.business')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Target warehouse for this request', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Outbound Product Request',
                'verbose_name_plural': 'Outbound Product Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(help_text='Quantity requested')),
                ('quantity_fulfilled', models.PositiveIntegerField(default=0, help_text='Quantity actually fulfilled (for partial fulfillment tracking)')),
                ('notes', models.TextField(blank=True, help_text='Item-specific notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inbound_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.inboundproductrequest')),
                ('outbound_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.outboundproductrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Request Item',
                'verbose_name_plural': 'Product Request Items',
                'ordering': ['id'],
            },
        ),
    ]
