# Generated by Django 5.2.11 on 2026-02-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_inboundproductrequest_outboundproductrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='max_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max weight capacity in kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=8, null=True),
        ),
    ]
