# Generated by Django 5.2.11 on 2026-03-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_storagelocation_height_cm_storagelocation_length_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreservation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('fulfilled', 'Fulfilled'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
    ]
