# Generated by Django 5.2.11 on 2026-03-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_stockreservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklistitem',
            name='is_packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='picklistitem',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Picked'), ('packing', 'Packing'), ('packed', 'Packed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
