# Generated by Django 5.2.11 on 2026-03-26 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_alter_order_client_order_code_and_more'),
        ('product', '0004_product_client_names'),
        ('warehouse', '0006_add_packing_status_and_is_packed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('reason', models.CharField(default='order_cancelled', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_returns', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_tasks', to='orders.order')),
                ('pick_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_tasks', to='warehouse.picklist')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_tasks', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Return Task',
                'verbose_name_plural': 'Return Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_returned', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_task_items', to='warehouse.storagelocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_task_items', to='product.product')),
                ('return_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.returntask')),
            ],
            options={
                'verbose_name': 'Return Task Item',
                'verbose_name_plural': 'Return Task Items',
            },
        ),
    ]
