# Generated by Django 5.2.11 on 2026-03-26 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_alter_business_fulfillment_service_status'),
        ('warehouse', '0007_add_return_task_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Seller/business this pick list belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_lists', to='business.business'),
        ),
        migrations.AddField(
            model_name='picklist',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Warehouse zone for this pick list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_lists', to='warehouse.storagelocation'),
        ),
    ]
