# Generated by Django 5.2.11 on 2026-03-26 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_add_driver_meta'),
        ('orders', '0039_alter_order_client_order_code_and_more'),
        ('warehouse', '0008_add_business_zone_to_picklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('assigned', 'Assigned to Driver'), ('handed_over', 'Handed Over'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='ready', max_length=20)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wh_dispatch_batches', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_batches', to='fleet.driver')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_batches', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Dispatch Batch',
                'verbose_name_plural': 'Dispatch Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_handed_over', models.BooleanField(default=False)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.dispatchbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_items', to='orders.order')),
                ('pick_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_items', to='warehouse.picklist')),
            ],
            options={
                'verbose_name': 'Dispatch Item',
                'verbose_name_plural': 'Dispatch Items',
            },
        ),
    ]
