# Generated by Django 5.2.11 on 2026-03-26 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_alter_business_fulfillment_service_status'),
        ('orders', '0039_alter_order_client_order_code_and_more'),
        ('product', '0004_product_client_names'),
        ('warehouse', '0009_add_dispatch_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('in_transit', 'In Transit (returning)'), ('received', 'Received at Warehouse'), ('inspected', 'Inspected'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='requested', max_length=20)),
                ('reason', models.CharField(choices=[('wrong_item', 'Wrong Item Received'), ('damaged', 'Damaged / Defective'), ('refused', 'Customer Refused (COD)'), ('change_of_mind', 'Change of Mind'), ('not_as_described', 'Not as Described'), ('other', 'Other')], max_length=30)),
                ('customer_notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_returns', to='business.business')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_returns', to='orders.order')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_requests', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_returns', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Customer Return',
                'verbose_name_plural': 'Customer Returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('reason', models.CharField(blank=True, choices=[('wrong_item', 'Wrong Item Received'), ('damaged', 'Damaged / Defective'), ('refused', 'Customer Refused (COD)'), ('change_of_mind', 'Change of Mind'), ('not_as_described', 'Not as Described'), ('other', 'Other')], max_length=30)),
                ('condition', models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged'), ('defective', 'Defective'), ('opened', 'Opened/Used')], max_length=20)),
                ('disposition', models.CharField(blank=True, choices=[('restock', 'Restock (Good Condition)'), ('quarantine', 'Quarantine (Inspect Further)'), ('dispose', 'Dispose (Damaged)')], max_length=20)),
                ('is_received', models.BooleanField(default=False)),
                ('is_inspected', models.BooleanField(default=False)),
                ('is_restocked', models.BooleanField(default=False)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('restocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.customerreturn')),
                ('location', models.ForeignKey(blank=True, help_text='Location to restock to (if disposition is restock)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='warehouse.storagelocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='product.product')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
            },
        ),
    ]
