# Generated by Django 5.2.11 on 2026-03-26 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_client_names'),
        ('warehouse', '0010_add_customer_return_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PutAwayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('total_items', models.IntegerField(default=0)),
                ('completed_items', models.IntegerField(default=0)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_put_aways', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_put_aways', to=settings.AUTH_USER_MODEL)),
                ('inbound_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='put_away_tasks', to='warehouse.inboundproductrequest')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='put_away_tasks', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Put-Away Task',
                'verbose_name_plural': 'Put-Away Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PutAwayTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_location', models.ForeignKey(blank=True, help_text='Location where items were actually placed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_put_aways', to='warehouse.storagelocation')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_put_away_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='put_away_items', to='product.product')),
                ('put_away_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.putawaytask')),
                ('source_location', models.ForeignKey(blank=True, help_text='Location where stock was received (dock/staging)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='put_away_sources', to='warehouse.storagelocation')),
                ('suggested_location', models.ForeignKey(blank=True, help_text='System-suggested location (where product already exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_put_aways', to='warehouse.storagelocation')),
            ],
            options={
                'verbose_name': 'Put-Away Item',
                'verbose_name_plural': 'Put-Away Items',
                'ordering': ['put_away_task', 'suggested_location__code'],
            },
        ),
        migrations.AddIndex(
            model_name='putawaytask',
            index=models.Index(fields=['warehouse', 'status', '-created_at'], name='wh_putaway_status_idx'),
        ),
    ]
