# Generated by Django 5.2.11 on 2026-04-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_putawaytask_putawaytaskitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.CharField(default='Qatar', max_length=100),
        ),
    ]
