# Generated by Django 5.2.11 on 2026-03-19 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_add_column_mapping_to_api_settings'),
        ('ezzy_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookImportKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=48, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('total_received', models.PositiveIntegerField(default=0)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_import_key', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Webhook Import Keys',
            },
        ),
        migrations.CreateModel(
            name='WebhookImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('error', 'Error')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('orders_created', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_import_logs', to='business.business')),
                ('webhook_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ezzy_api.webhookimportkey')),
            ],
            options={
                'verbose_name_plural': 'Webhook Import Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
