# Generated by Django 5.2.12 on 2026-07-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezzy_api', '0003_webhookimportkey_wc_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapikey',
            name='key_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientapikey',
            name='key_prefix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='clientapikey',
            name='scope',
            field=models.CharField(choices=[('read', 'Read only'), ('write', 'Read & write'), ('admin', 'Full access (manage keys)')], default='write', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientapikey',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
