# Generated by Django 5.2.16 on 2026-08-08 16:32

import core.validators
import django.core.validators
import ezzy_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezzy_api', '0005_hash_existing_api_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdocument',
            name='document_file',
            field=models.FileField(upload_to=ezzy_api.models.order_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif', 'pdf']), core.validators.MaxFileSizeValidator(10)]),
        ),
        migrations.AlterField(
            model_name='taskdocument',
            name='document_file',
            field=models.FileField(upload_to=ezzy_api.models.task_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif', 'pdf']), core.validators.MaxFileSizeValidator(10)]),
        ),
    ]
