# Generated by Django 5.2.16 on 2026-09-08 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0040_businessledgerentry'),
        ('orders', '0065_order_p2p_customer_order_package_weight_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PRateBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_boxes', models.PositiveIntegerField(default=1, help_text='Lowest box count this row covers')),
                ('max_boxes', models.PositiveIntegerField(blank=True, help_text='Highest box count. Blank = no upper limit.', null=True)),
                ('size', models.CharField(blank=True, choices=[('xs', 'Envelope / Docs (≤ 0.5 kg)'), ('s', 'Small Box (≤ 3 kg)'), ('m', 'Medium Box (≤ 10 kg)'), ('l', 'Large Box (≤ 25 kg)'), ('xl', 'Bulky / Extra Large (25 kg+)')], default='', help_text='Blank = any size', max_length=4)),
                ('up_to_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight ceiling for this row. Blank = any weight.', max_digits=7, null=True)),
                ('vehicle', models.CharField(blank=True, choices=[('bike', 'Motorcycle'), ('car', 'Car'), ('suv', 'SUV / Pickup'), ('van', 'Van'), ('truck', 'Truck')], default='', help_text='Blank = any vehicle', max_length=10)),
                ('speed', models.CharField(blank=True, choices=[('express', 'Express — as soon as possible'), ('standard', 'Scheduled — on a chosen date')], default='', help_text='Blank = any speed', max_length=20)),
                ('up_to_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance ceiling for this row. Blank = no upper limit.', max_digits=7, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='QAR. Ignored when needs_quote is set.', max_digits=10)),
                ('needs_quote', models.BooleanField(default=False, help_text='No automatic price — staff quote this one by hand')),
                ('priority', models.IntegerField(default=0, help_text='Higher wins when two rows are equally specific')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'P2P rate band',
                'verbose_name_plural': 'P2P rate card',
                'ordering': ['-priority', 'up_to_km', 'id'],
            },
        ),
        migrations.CreateModel(
            name='P2PBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft — quote accepted, not signed in'), ('details', 'Signed in — filling details'), ('awaiting_price', 'Awaiting staff price'), ('awaiting_customer', 'Awaiting customer confirmation'), ('confirmed', 'Confirmed by customer'), ('abandoned', 'Abandoned'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('from_label', models.CharField(max_length=150)),
                ('to_label', models.CharField(max_length=150)),
                ('from_lat', models.DecimalField(decimal_places=15, max_digits=19)),
                ('from_lng', models.DecimalField(decimal_places=15, max_digits=19)),
                ('to_lat', models.DecimalField(decimal_places=15, max_digits=19)),
                ('to_lng', models.DecimalField(decimal_places=15, max_digits=19)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('size', models.CharField(blank=True, choices=[('xs', 'Envelope / Docs (≤ 0.5 kg)'), ('s', 'Small Box (≤ 3 kg)'), ('m', 'Medium Box (≤ 10 kg)'), ('l', 'Large Box (≤ 25 kg)'), ('xl', 'Bulky / Extra Large (25 kg+)')], default='', max_length=4)),
                ('vehicle', models.CharField(blank=True, choices=[('bike', 'Motorcycle'), ('car', 'Car'), ('suv', 'SUV / Pickup'), ('van', 'Van'), ('truck', 'Truck')], default='', max_length=10)),
                ('speed', models.CharField(choices=[('express', 'Express — as soon as possible'), ('standard', 'Scheduled — on a chosen date')], default='express', max_length=20)),
                ('box_count', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Server-computed. Null when the booking needs a staff quote.', max_digits=10, null=True)),
                ('needs_quote', models.BooleanField(default=False)),
                ('ladder_version', models.CharField(blank=True, default='', max_length=20)),
                ('staff_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('priced_at', models.DateTimeField(blank=True, null=True)),
                ('customer_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, default='', max_length=100)),
                ('sender_phone', models.CharField(blank=True, default='', max_length=20)),
                ('pickup_locality', models.CharField(blank=True, default='', max_length=150)),
                ('pickup_zone', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_street', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_building', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_notes', models.CharField(blank=True, default='', max_length=160)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_status', models.CharField(choices=[('pending', 'Not collected'), ('collected_cash', 'Collected in cash at pickup'), ('billed', 'Billed to the client invoice'), ('waived', 'Waived')], db_index=True, default='pending', max_length=20)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Set once they sign in. Null while the draft is anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2p_bookings', to=settings.AUTH_USER_MODEL)),
                ('fee_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2p_bookings', to='fleet.drivertransaction')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2p_booking', to='orders.order')),
                ('priced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2p_bookings_priced', to=settings.AUTH_USER_MODEL)),
                ('rate_band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='p2p.p2prateband')),
            ],
            options={
                'verbose_name': 'P2P booking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='p2p_cust_created_idx'), models.Index(fields=['status', '-created_at'], name='p2p_status_created_idx')],
            },
        ),
    ]
