# Generated by Django 5.2.16 on 2026-09-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0002_seed_rate_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pbooking',
            name='booker_role',
            field=models.CharField(choices=[('sender', "I'm sending it"), ('receiver', "I'm receiving it")], default='sender', help_text='Which end of this job the customer is standing at', max_length=10),
        ),
        migrations.AddField(
            model_name='p2pbooking',
            name='fee_payer',
            field=models.CharField(choices=[('sender', 'Sender pays the driver at pickup'), ('receiver', 'Receiver pays the driver on delivery')], default='sender', help_text='Decides whether the driver asks for the fee at pickup or at the door', max_length=10),
        ),
        migrations.AddField(
            model_name='p2pbooking',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='p2pbooking',
            name='receiver_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='p2pbooking',
            name='fee_status',
            field=models.CharField(choices=[('pending', 'Not collected'), ('collected_cash', 'Collected in cash'), ('billed', 'Billed to the client invoice'), ('waived', 'Waived')], db_index=True, default='pending', max_length=20),
        ),
    ]
