# Generated by Django 5.2.16 on 2026-09-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0003_p2pbooking_booker_role_p2pbooking_fee_payer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pbooking',
            name='booker_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='p2pbooking',
            name='booker_role',
            field=models.CharField(choices=[('sender', "I'm sending it"), ('receiver', "I'm receiving it"), ('other', "I'm booking it for two other people")], default='sender', help_text='Which end of this job the customer is standing at, if either', max_length=10),
        ),
    ]
