# Generated by Django 5.2.16 on 2026-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0004_p2pbooking_booker_phone_alter_p2pbooking_booker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pbooking',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p2pbooking',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
