# Generated by Django 5.2.16 on 2026-09-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0005_p2pbooking_pickup_date_p2pbooking_pickup_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PBoxTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_boxes', models.PositiveIntegerField(default=1, help_text='Lowest box count this tier covers')),
                ('max_boxes', models.PositiveIntegerField(blank=True, help_text='Highest box count. Blank = no upper limit.', null=True)),
                ('uplift', models.DecimalField(decimal_places=2, default=0, help_text='QAR added to the band price for a job in this tier. Ignored when needs_quote is set.', max_digits=10)),
                ('needs_quote', models.BooleanField(default=False, help_text='No automatic price at this many boxes — staff price it')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'P2P box tier',
                'verbose_name_plural': 'P2P box tiers',
                'ordering': ['min_boxes', 'id'],
            },
        ),
    ]
