# Generated by Django 5.2.16 on 2026-09-08 18:45

from django.db import migrations, models

# p2p.models.P2P_MAX_KG at the time of writing. A literal because a migration is a
# historical record: it has to keep doing the same thing after that constant moves.
MAX_KG = 1000


def close_weight(apps, schema_editor):
    """Existing tiers cover every weight, which is now said with a number."""
    apps.get_model('p2p', 'P2PBoxTier').objects.filter(
        up_to_kg__isnull=True).update(up_to_kg=MAX_KG)


def reopen_weight(apps, schema_editor):
    apps.get_model('p2p', 'P2PBoxTier').objects.filter(
        up_to_kg=MAX_KG).update(up_to_kg=None)


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0008_close_open_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pboxtier',
            name='up_to_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight ceiling for this tier. Four boxes of documents and four of tiles are not the same job.', max_digits=8, null=True),
        ),
        migrations.RunPython(close_weight, reopen_weight),
    ]
