# Generated by Django 5.2.16 on 2026-09-08 19:01

from django.db import migrations, models

# Cubic metres of load space per vehicle. The bike is measured: its box is a 30 cm cube,
# 0.027 cbm, which is the number ops gave. The rest are the usual load spaces for the
# classes of vehicle the fleet runs, and every one of them is editable on the rate card
# page — these are a starting point, not a rule.
SEED_CAPACITY = [
    ('bike', '0.0270'),
    ('car', '0.4000'),
    ('suv', '1.5000'),
    ('van', '6.0000'),
    ('truck', '20.0000'),
]


def seed(apps, schema_editor):
    P2PVehicleCapacity = apps.get_model('p2p', 'P2PVehicleCapacity')
    for vehicle, cbm in SEED_CAPACITY:
        P2PVehicleCapacity.objects.get_or_create(
            vehicle=vehicle, defaults={'capacity_cbm': cbm, 'is_active': True})


def unseed(apps, schema_editor):
    apps.get_model('p2p', 'P2PVehicleCapacity').objects.filter(
        vehicle__in=[v for v, _ in SEED_CAPACITY]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0009_box_tier_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PVehicleCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('bike', 'Motorcycle'), ('car', 'Car'), ('suv', 'SUV / Pickup'), ('van', 'Van'), ('truck', 'Truck')], help_text='Which vehicle this is the capacity of', max_length=10, unique=True)),
                ('capacity_cbm', models.DecimalField(decimal_places=4, help_text='Cubic metres of load space. A 30 cm cube is 0.027.', max_digits=8)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Off = no volume limit on this vehicle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'P2P vehicle capacity',
                'verbose_name_plural': 'P2P vehicle capacities',
                'ordering': ['capacity_cbm', 'id'],
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
