# Generated by Django 5.2.16 on 2026-09-08 19:27

from django.db import migrations, models

# A pickup goes out for a cubic metre and up. Below that a car can take it, and sending
# the SUV means a bigger vehicle and a bigger price for a load that did not need either.
# The other vehicles have no minimum until ops give them one on the rate card page.
MIN_LOAD = {'suv': '1.0000'}


def seed(apps, schema_editor):
    P2PVehicleCapacity = apps.get_model('p2p', 'P2PVehicleCapacity')
    for vehicle, minimum in MIN_LOAD.items():
        P2PVehicleCapacity.objects.filter(vehicle=vehicle).update(min_cbm=minimum)


def unseed(apps, schema_editor):
    apps.get_model('p2p', 'P2PVehicleCapacity').objects.filter(
        vehicle__in=MIN_LOAD).update(min_cbm=0)


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0010_vehicle_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pvehiclecapacity',
            name='min_cbm',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Smallest load worth sending this vehicle out for. A pickup set to 1.0 is not offered for a parcel a car could take. Ignored when nothing smaller can carry the load. 0 = no minimum.', max_digits=8),
        ),
        migrations.RunPython(seed, unseed),
    ]
