# Generated by Django 5.2.16 on 2026-09-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0014_fill_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PBookingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xs', 'Envelope / Docs (≤ 0.5 kg)'), ('s', 'Small Box (≤ 3 kg)'), ('m', 'Medium Box (≤ 10 kg)'), ('l', 'Large Box (≤ 25 kg)'), ('xl', 'Bulky / Extra Large (25 kg+)')], help_text='Which box size this line counts', max_length=4)),
                ('count', models.PositiveIntegerField(default=1, help_text='How many boxes of this size')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(help_text='The job this is part of', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='p2p.p2pbooking')),
            ],
            options={
                'verbose_name': 'P2P booking line',
                'verbose_name_plural': 'P2P booking lines',
                'ordering': ['booking', 'size', 'id'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'size'), name='uniq_p2p_booking_line_size')],
            },
        ),
    ]
