# Generated by Django 5.2.16 on 2026-09-10 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0067_ordercomments_backfill_read'),
        ('p2p', '0015_booking_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pbooking',
            name='return_description',
            field=models.CharField(blank=True, default='', help_text='What comes back on the return leg', max_length=255),
        ),
        migrations.AddField(
            model_name='p2pbooking',
            name='return_order',
            field=models.OneToOneField(blank=True, help_text='The order for the leg back. Null on every one-way booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2p_return_booking', to='orders.order'),
        ),
        migrations.AddField(
            model_name='p2pbooking',
            name='return_trip',
            field=models.BooleanField(default=False, help_text='A second journey bringing something back to the pickup point'),
        ),
    ]
