# Generated by Django 5.2 on 2026-01-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_initial'),
        ('fleet', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchConfig',
            fields=[
                ('pickup_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dispatch_config', serialize=False, to='business.pickuplocation')),
                ('max_batch_size', models.PositiveSmallIntegerField(default=2, help_text='Maximum orders per batch')),
                ('hold_window_seconds', models.PositiveIntegerField(default=180, help_text='Default hold window in seconds (3 min)')),
                ('min_hold_seconds', models.PositiveIntegerField(default=120, help_text='Minimum hold window (2 min)')),
                ('max_hold_seconds', models.PositiveIntegerField(default=240, help_text='Maximum hold window (4 min)')),
                ('sla_minutes', models.PositiveIntegerField(default=60, help_text='Target delivery SLA in minutes')),
                ('sla_buffer_minutes', models.PositiveIntegerField(default=15, help_text='Release batch if SLA deadline is within this buffer')),
                ('sla_override_enabled', models.BooleanField(default=True, help_text='Auto-release batches when SLA at risk')),
                ('max_orders_per_rider', models.PositiveSmallIntegerField(default=2, help_text='Maximum active orders per rider')),
                ('max_batches_per_rider', models.PositiveSmallIntegerField(default=1, help_text='Maximum active batches per rider')),
                ('peak_start_1', models.TimeField(default='11:00:00', help_text='Lunch peak start')),
                ('peak_end_1', models.TimeField(default='14:00:00', help_text='Lunch peak end')),
                ('peak_start_2', models.TimeField(default='18:00:00', help_text='Dinner peak start')),
                ('peak_end_2', models.TimeField(default='21:00:00', help_text='Dinner peak end')),
                ('enforce_batching_peak', models.BooleanField(default=True, help_text='Strictly enforce batching during peak hours')),
                ('allow_single_release_offpeak', models.BooleanField(default=True, help_text='Allow single-order release during off-peak')),
                ('batching_enabled', models.BooleanField(default=True, help_text='Enable order batching for this location')),
                ('auto_assignment_enabled', models.BooleanField(default=True, help_text='Enable automatic rider assignment')),
                ('zone_priority_enabled', models.BooleanField(default=True, help_text='Prioritize riders familiar with destination zone')),
                ('load_balancing_enabled', models.BooleanField(default=True, help_text='Distribute orders evenly among riders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispatch Config',
                'verbose_name_plural': 'Dispatch Configs',
            },
        ),
        migrations.CreateModel(
            name='RiderShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning (6AM-2PM)'), ('afternoon', 'Afternoon (2PM-10PM)'), ('night', 'Night (10PM-6AM)'), ('custom', 'Custom Hours')], default='custom', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('break', 'On Break'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('break_start', models.DateTimeField(blank=True, null=True)),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('total_break_minutes', models.PositiveIntegerField(default=0)),
                ('batches_completed', models.PositiveIntegerField(default=0)),
                ('orders_delivered', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='business.pickuplocation')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.driver')),
            ],
            options={
                'verbose_name': 'Rider Shift',
                'verbose_name_plural': 'Rider Shifts',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='OrderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('destination_zone', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('holding', 'Holding'), ('ready', 'Ready'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('release_reason', models.CharField(blank=True, choices=[('batch_full', 'Batch Full'), ('timeout', 'Hold Window Expired'), ('sla_risk', 'SLA Risk'), ('manual', 'Manual Release'), ('off_peak', 'Off-Peak Single Release')], max_length=20, null=True)),
                ('hold_started_at', models.DateTimeField(blank=True, null=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('order_count', models.PositiveSmallIntegerField(default=0)),
                ('total_cod', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_delivery_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_batches', to='fleet.driver')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='business.pickuplocation')),
                ('assigned_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='dispatch.ridershift')),
            ],
            options={
                'verbose_name': 'Order Batch',
                'verbose_name_plural': 'Order Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('batch_created', 'Batch Created'), ('order_added', 'Order Added to Batch'), ('batch_released', 'Batch Released'), ('batch_assigned', 'Batch Assigned to Rider'), ('batch_started', 'Batch Delivery Started'), ('batch_completed', 'Batch Completed'), ('batch_cancelled', 'Batch Cancelled'), ('sla_warning', 'SLA Warning Triggered'), ('sla_override', 'SLA Override Release'), ('shift_started', 'Shift Started'), ('shift_ended', 'Shift Ended'), ('shift_break_start', 'Shift Break Started'), ('shift_break_end', 'Shift Break Ended'), ('config_changed', 'Config Changed'), ('manual_override', 'Manual Override')], db_index=True, max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='orders.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_actions', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='fleet.driver')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='dispatch.orderbatch')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='dispatch.ridershift')),
            ],
            options={
                'verbose_name': 'Dispatch Log',
                'verbose_name_plural': 'Dispatch Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_sla_at_risk', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignment', to='orders.order')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_orders', to='dispatch.orderbatch')),
            ],
            options={
                'verbose_name': 'Batch Order',
                'verbose_name_plural': 'Batch Orders',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['batch', 'sequence'], name='batchorder_seq_idx'), models.Index(fields=['sla_deadline'], name='batchorder_sla_idx')],
                'unique_together': {('batch', 'order')},
            },
        ),
        migrations.CreateModel(
            name='RiderKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('batched_orders', models.PositiveIntegerField(default=0)),
                ('single_orders', models.PositiveIntegerField(default=0)),
                ('total_batches', models.PositiveIntegerField(default=0)),
                ('batches_with_2_orders', models.PositiveIntegerField(default=0)),
                ('total_active_minutes', models.PositiveIntegerField(default=0)),
                ('avg_delivery_time', models.PositiveIntegerField(default=0)),
                ('sla_compliant_orders', models.PositiveIntegerField(default=0)),
                ('sla_breached_orders', models.PositiveIntegerField(default=0)),
                ('orders_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('batching_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sla_compliance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_kpis', to='business.pickuplocation')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='fleet.driver')),
            ],
            options={
                'verbose_name': 'Rider KPI',
                'verbose_name_plural': 'Rider KPIs',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['rider', 'date'], name='kpi_rider_date_idx'), models.Index(fields=['date', 'pickup_location'], name='kpi_date_location_idx')],
                'unique_together': {('rider', 'date', 'pickup_location')},
            },
        ),
        migrations.AddIndex(
            model_name='ridershift',
            index=models.Index(fields=['rider', 'status', 'scheduled_start'], name='shift_rider_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ridershift',
            index=models.Index(fields=['pickup_location', 'status'], name='shift_location_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ridershift',
            index=models.Index(fields=['scheduled_start', 'scheduled_end'], name='shift_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='ridershift',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_end__gt', models.F('scheduled_start'))), name='shift_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='orderbatch',
            index=models.Index(fields=['pickup_location', 'destination_zone', 'status'], name='batch_loc_zone_status_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbatch',
            index=models.Index(fields=['status', 'hold_expires_at'], name='batch_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbatch',
            index=models.Index(fields=['assigned_rider', 'status'], name='batch_rider_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchlog',
            index=models.Index(fields=['action', '-created_at'], name='displog_action_time_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchlog',
            index=models.Index(fields=['batch', '-created_at'], name='displog_batch_time_idx'),
        ),
    ]
