# Generated by Django 5.1.2 on 2024-10-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('qid', models.BigIntegerField()),
                ('job', models.CharField(max_length=100)),
                ('self_intro', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Careers',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('purpose', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='PricingEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('business_contact_number', models.CharField(max_length=100)),
                ('operation_team_contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('website_url', models.CharField(blank=True, max_length=200, null=True)),
                ('social_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('product_category', models.CharField(max_length=200)),
                ('is_personalized_product', models.BooleanField(default=False)),
                ('is_registered_company_in_qatar', models.BooleanField(default=False)),
                ('is_located_in_qatar', models.BooleanField(default=False)),
                ('is_staff_available_in_qatar', models.BooleanField(default=False)),
                ('is_required_COD_service', models.BooleanField(default=False)),
                ('is_required_fulfillment_service_for_operate_from_outside_qatar', models.BooleanField(default=False)),
                ('is_required_fulfillment_service_for_make_hub_in_doha', models.BooleanField(default=False)),
                ('avarage_number_of_order_last_week', models.CharField(blank=True, null=True)),
                ('avarage_number_of_order_done_last_month', models.CharField(blank=True, null=True)),
                ('avarage_number_of_order_expect_next_month', models.CharField(blank=True, null=True)),
                ('orders_expected_in_next_3_months_milestone', models.CharField(blank=True, null=True)),
                ('speed_delivery_offer_to_customers', models.CharField(blank=True, max_length=200, null=True)),
                ('is_frequent_same_day_pick_and_delivery_required', models.BooleanField(default=False)),
                ('preferred_delivery_time_window', models.CharField(blank=True, max_length=200, null=True)),
                ('typical_package_size', models.CharField(blank=True, max_length=100, null=True)),
                ('is_special_handling_required', models.BooleanField(default=False)),
                ('type_of_pickup_location', models.CharField(blank=True, max_length=200, null=True)),
                ('pickup_Location_area_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pickup_location_time_slab', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_pickup_times_in_day', models.CharField(blank=True, default='1', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pricing Inquiries',
            },
        ),
    ]
