# Generated by Django 5.2 on 2026-01-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('qid', models.BigIntegerField()),
                ('job', models.CharField(max_length=100)),
                ('self_intro', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Careers',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('purpose', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('pick_and_delivery', 'Pick and Delivery'), ('store_pickup_and_delivery', 'Store Pickup and Delivery')], max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('pickup_address', models.TextField(help_text='Full pickup address')),
                ('pickup_zone', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_street', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_building', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('pickup_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_contact_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_address', models.TextField(help_text='Full delivery address')),
                ('delivery_zone', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_street', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_building', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('delivery_contact_name', models.CharField(max_length=100)),
                ('delivery_contact_mobile', models.CharField(max_length=20)),
                ('package_description', models.TextField(help_text='Description of items to be delivered')),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=10, null=True)),
                ('package_category', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('delivery_speed', models.CharField(blank=True, help_text='Normal, Same Day, On Demand', max_length=50, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('business_contact_number', models.CharField(max_length=100)),
                ('operation_team_contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('website_url', models.CharField(blank=True, max_length=200, null=True)),
                ('social_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('product_category', models.CharField(max_length=200)),
                ('is_personalized_product', models.BooleanField(default=False)),
                ('is_registered_company_in_qatar', models.BooleanField(default=False)),
                ('is_located_in_qatar', models.BooleanField(default=False)),
                ('is_team_available_in_qatar', models.BooleanField(default=False)),
                ('is_required_COD_service', models.BooleanField(default=False)),
                ('is_required_fulfillment_service_for_operate_from_outside_qatar', models.BooleanField(default=False)),
                ('is_required_fulfillment_service_for_make_hub_in_doha', models.BooleanField(default=False)),
                ('avarage_number_of_order_last_week', models.CharField(blank=True, max_length=20, null=True)),
                ('avarage_number_of_order_done_last_month', models.CharField(blank=True, max_length=20, null=True)),
                ('avarage_number_of_order_expect_next_month', models.CharField(blank=True, max_length=20, null=True)),
                ('orders_expected_in_next_3_months_milestone', models.CharField(blank=True, max_length=20, null=True)),
                ('speed_delivery_offer_to_customers', models.CharField(blank=True, max_length=200, null=True)),
                ('is_frequent_same_day_pick_and_delivery_required', models.BooleanField(default=False)),
                ('preferred_delivery_time_window', models.CharField(blank=True, max_length=200, null=True)),
                ('typical_package_size', models.CharField(blank=True, max_length=100, null=True)),
                ('is_special_handling_required', models.BooleanField(default=False)),
                ('type_of_pickup_location', models.CharField(blank=True, max_length=200, null=True)),
                ('pickup_Location_area_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pickup_location_time_slab', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_pickup_times_in_day', models.CharField(blank=True, default='1', max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('date_modified', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pricing Inquiries',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=200)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'WhatsApp Inquiries',
            },
        ),
    ]
