# Generated by Django 5.1.2 on 2024-10-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingenquiry',
            old_name='is_staff_available_in_qatar',
            new_name='is_team_available_in_qatar',
        ),
    ]
