# Generated by Django 4.1.13 on 2024-12-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_rename_is_staff_available_in_qatar_pricingenquiry_is_team_available_in_qatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingenquiry',
            name='avarage_number_of_order_done_last_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingenquiry',
            name='avarage_number_of_order_expect_next_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingenquiry',
            name='avarage_number_of_order_last_week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricingenquiry',
            name='orders_expected_in_next_3_months_milestone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
