# Generated by Django 5.2.11 on 2026-02-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_pricingenquiry_average_order_value_qar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
