# Generated by Django 5.1.7 on 2025-11-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_alter_pricingenquiry_avarage_number_of_order_done_last_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='date_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
