# Generated by Django 5.1.7 on 2025-11-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_pricingenquiry_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('pick_and_delivery', 'Pick and Delivery'), ('store_pickup_and_delivery', 'Store Pickup and Delivery')], max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('pickup_address', models.TextField(help_text='Full pickup address')),
                ('pickup_zone', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_street', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_building', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('pickup_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_contact_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_address', models.TextField(help_text='Full delivery address')),
                ('delivery_zone', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_street', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_building', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('delivery_contact_name', models.CharField(max_length=100)),
                ('delivery_contact_mobile', models.CharField(max_length=20)),
                ('package_description', models.TextField(help_text='Description of items to be delivered')),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=10, null=True)),
                ('package_category', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('delivery_speed', models.CharField(blank=True, help_text='Normal, Same Day, On Demand', max_length=50, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
