# Generated by Django 5.1.7 on 2025-11-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_deliveryrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=200)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'WhatsApp Inquiries',
            },
        ),
    ]
