# Generated by Django 5.2.12 on 2026-06-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_pricingenquiry_preferred_pickup_time_preferred_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='instagram_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
