# Generated by Django 5.2.16 on 2026-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_add_instagram_facebook_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='average_package_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='cod_orders_share',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='contact_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='current_delivery_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='fulfillment_storage_volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='number_of_pickup_locations',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='special_handling_detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
