# Generated by Django 5.2 on 2026-02-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_whatsappinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='current_courier_provider',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='delivery_coverage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='is_return_logistics_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='order_management_system',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='preferred_communication_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='preferred_start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
