# Generated by Django 5.2 on 2026-02-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_pricingenquiry_current_courier_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='average_order_value_qar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
