# Generated by Django 5.2.16 on 2026-07-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_pricingenquiry_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
