# Generated by Django 5.2 on 2026-02-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_pricingenquiry_average_order_value_qar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='business_operating_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='is_delivery_free_to_customers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
