# Generated by Django 5.2 on 2026-02-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_pricingenquiry_business_operating_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='business_location_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
