# Generated by Django 5.2 on 2026-02-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_pricingenquiry_business_location_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
