# Generated by Django 5.2.16 on 2026-08-16 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_quote_token_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one rate card can be active. Activating this deactivates the rest.')),
                ('base_price_default', models.DecimalField(decimal_places=2, default=25, help_text='Used when volume or distance is unknown. Quote high and discount — the opposite error is unrecoverable.', max_digits=10)),
                ('min_price_floor', models.DecimalField(decimal_places=2, default=15, help_text='Lowest price the engine will suggest. This is a CONFIGURED CONSTANT, not a measured cost to serve — see floor basis.', max_digits=10)),
                ('floor_basis', models.CharField(choices=[('config', 'Configured constant (not a measured cost)'), ('measured', 'Measured cost to serve')], default='config', max_length=10)),
                ('rounding_step', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('rounding_mode', models.CharField(choices=[('nearest', 'Nearest'), ('up', 'Always up')], default='nearest', max_length=10)),
                ('max_total_discount_pct', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('max_total_uplift_pct', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Rate Card',
                'verbose_name_plural': 'Rate Cards',
                'ordering': ['-is_active', 'code'],
            },
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='quoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='quoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='quoted_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='quoted_price_unit',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='quoted_price_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='suggested_price_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='suggested_price_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='typical_delivery_distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PricingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleset_code', models.CharField(max_length=50)),
                ('inputs_snapshot', models.JSONField(default=dict)),
                ('inputs_hash', models.CharField(db_index=True, max_length=64)),
                ('breakdown', models.JSONField(default=list, help_text='Ordered line items with running total.')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clamped_reason', models.CharField(blank=True, max_length=120, null=True)),
                ('floor_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floor_basis', models.CharField(blank=True, max_length=10, null=True)),
                ('comparable_median', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comparable_p25', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comparable_p75', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comparable_sample', models.PositiveIntegerField(default=0)),
                ('benchmark_midpoint', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flags', models.JSONField(default=list)),
                ('rationale_text', models.TextField(blank=True, null=True)),
                ('rationale_source', models.CharField(default='template', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_action', models.CharField(choices=[('none', 'No action yet'), ('accepted', 'Accepted as quoted'), ('overridden', 'Overridden by staff'), ('rejected', 'Rejected')], default='none', max_length=20)),
                ('staff_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('staff_note', models.TextField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='webpages.pricingenquiry')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='webpages.pricingruleset')),
            ],
            options={
                'verbose_name': 'Pricing Suggestion',
                'verbose_name_plural': 'Pricing Suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='latest_suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webpages.pricingsuggestion'),
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('volume_distance_base', 'Base — volume x distance'), ('weight', 'Weight'), ('size', 'Package size'), ('speed', 'Delivery speed'), ('cod', 'Cash on delivery'), ('special_handling', 'Special handling'), ('returns', 'Return logistics'), ('pickup_locations', 'Pickup locations'), ('pickups_per_day', 'Pickups per day')], max_length=30)),
                ('match_field', models.CharField(help_text='Normalised input key, e.g. monthly_orders, weight_mid_kg.', max_length=50)),
                ('match_kind', models.CharField(choices=[('numeric_range', 'Numeric range'), ('band_exact', 'Exact band'), ('boolean_true', 'Boolean is true'), ('contains', 'List contains'), ('always', 'Always')], default='numeric_range', max_length=20)),
                ('match_value', models.CharField(blank=True, max_length=120, null=True)),
                ('match_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('match_max', models.DecimalField(blank=True, decimal_places=2, help_text='Exclusive upper bound. Leave empty for open-ended.', max_digits=12, null=True)),
                ('match2_field', models.CharField(blank=True, max_length=50, null=True)),
                ('match2_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('match2_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effect', models.CharField(choices=[('set_base', 'Set base price'), ('add', 'Add QR'), ('pct', '% of base')], default='add', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('label', models.CharField(help_text='The line sales reads on the breakdown.', max_length=120)),
                ('explanation', models.TextField(blank=True, help_text='Where this rate came from.', null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('stop_on_match', models.BooleanField(default=True, help_text='Off means later rules in the same dimension can also apply (they stack).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='webpages.pricingruleset')),
            ],
            options={
                'verbose_name': 'Rate Card Rule',
                'verbose_name_plural': 'Rate Card Rules',
                'ordering': ['ruleset', 'dimension', 'priority', 'id'],
                'indexes': [models.Index(fields=['ruleset', 'dimension', 'priority'], name='webpages_pr_ruleset_38078a_idx')],
            },
        ),
    ]
