# Generated by Django 5.2 on 2026-03-02 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_pricingenquiry_is_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pricing_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='crm_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('negotiating', 'Negotiating'), ('converted', 'Converted'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingenquiry',
            name='staff_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PricingEnquiryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('note', 'Note'), ('followup', 'Follow-up'), ('status_change', 'Status Change')], default='note', max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='webpages.pricingenquiry')),
            ],
            options={
                'verbose_name_plural': 'Pricing Enquiry Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
