# Generated by Django 5.2.16 on 2026-08-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0014_fix_cod_rule_stacking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='resume_nudge_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
