# Generated by Django 5.2.16 on 2026-08-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_pricingenquiry_resume_nudge_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='dimension',
            field=models.CharField(choices=[('volume_distance_base', 'Base — volume x distance'), ('weight', 'Weight'), ('size', 'Package size'), ('speed', 'Delivery speed'), ('cod', 'Cash on delivery'), ('special_handling', 'Special handling'), ('returns', 'Return logistics'), ('same_day_pickup', 'Same-day pick & deliver'), ('pickup_type', 'Pickup point type'), ('pickup_locations', 'Pickup locations'), ('pickups_per_day', 'Pickups per day')], max_length=30),
        ),
    ]
