# Generated by Django 5.2.17 on 2026-09-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0019_v2_high_volume_at_500'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingenquiry',
            name='trimmed_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
