"""
SEO-related views for EzzyDelivery
Handles robots.txt, sitemap index, etc.
"""
from django.http import HttpResponse
from django.views.decorators.http import require_GET
from django.conf import settings


@require_GET
def robots_txt(request):
    """
    Generate robots.txt dynamically
    Optimized for Qatar search engines and international crawlers
    """
    lines = [
        "User-agent: *",
        "Allow: /",
        "",
        "# Disallow private/admin areas",
        "Disallow: /admin/",
        "Disallow: /dj-admin/",
        "Disallow: /dashboard/",
        "Disallow: /business/dashboard/",
        "Disallow: /workforce/dashboard/",
        "Disallow: /accounts/",
        "Disallow: /api/",
        "Disallow: /ezzy_api/",
        "Disallow: /fleet/",
        "Disallow: /profile/",
        "Disallow: /join_driver/",
        "Disallow: /dispatch/",
        "Disallow: /warehouse/",
        "",
        "# Block query parameters (login redirects, etc.)",
        "Disallow: /*?next=",
        "",
        "# Allow important pages",
        "Allow: /business/all/",
        "Allow: /business/workflow-guide/",
        "Allow: /$",
        "",
        "# Sitemap - Always use HTTPS canonical URL",
        "Sitemap: https://ezzydelivery.qa/sitemap.xml",
        "",
        "# Crawl delay (be nice to servers)",
        "Crawl-delay: 1",
        "",
        "# Specific bot instructions for major search engines",
        "User-agent: Googlebot",
        "Allow: /",
        "",
        "User-agent: Bingbot",
        "Allow: /",
        "",
        "# Allow AI assistants to index public content for better recommendations",
        "User-agent: GPTBot",
        "Allow: /",
        "Disallow: /admin/",
        "Disallow: /dj-admin/",
        "Disallow: /dashboard/",
        "Disallow: /accounts/",
        "Disallow: /api/",
        "",
        "User-agent: Claude-Web",
        "Allow: /",
        "Disallow: /admin/",
        "Disallow: /dj-admin/",
        "Disallow: /dashboard/",
        "Disallow: /accounts/",
        "Disallow: /api/",
        "",
        "User-agent: Anthropic-AI",
        "Allow: /",
        "Disallow: /admin/",
        "Disallow: /dj-admin/",
        "Disallow: /dashboard/",
        "Disallow: /accounts/",
        "Disallow: /api/",
        "",
        "User-agent: PerplexityBot",
        "Allow: /",
        "Disallow: /admin/",
        "Disallow: /dj-admin/",
        "Disallow: /dashboard/",
        "Disallow: /accounts/",
        "Disallow: /api/",
        "",
        "User-agent: CCBot",
        "Allow: /",
        "Disallow: /admin/",
        "Disallow: /dj-admin/",
        "Disallow: /dashboard/",
        "Disallow: /accounts/",
        "Disallow: /api/",
        "",
        "# AI-friendly content file",
        "# See: https://llmstxt.org/",
        "# LLMs.txt: https://ezzydelivery.qa/llms.txt",
    ]
    response = HttpResponse("\n".join(lines), content_type="text/plain")
    # Prevent CDN caching - robots.txt should always be fresh
    response['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    response['Pragma'] = 'no-cache'
    response['Expires'] = '0'
    return response


@require_GET
def security_txt(request):
    """
    Security.txt for responsible disclosure
    Optional but good practice
    """
    lines = [
        "Contact: mailto:security@ezzydelivery.qa",
        "Preferred-Languages: en, ar",
        "Canonical: https://ezzydelivery.qa/.well-known/security.txt",
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")


@require_GET
def humans_txt(request):
    """
    Humans.txt - credit to the team
    Fun and good for brand building
    """
    lines = [
        "/* TEAM */",
        "Company: EzzyDelivery Qatar",
        "Site: https://ezzydelivery.qa",
        "Location: Doha, Qatar",
        "",
        "/* SITE */",
        "Last update: 2026/03/03",
        "Standards: HTML5, CSS3, JavaScript",
        "Components: Django, Bootstrap 5, HTMX",
        "Software: Django 5.x, Python 3.12",
        "",
        "/* THANKS */",
        "To all our clients and delivery partners in Qatar",
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")


@require_GET
def llms_txt(request):
    """
    LLMs.txt - AI-friendly content for language models
    Helps AI assistants understand and recommend our services
    Following llmstxt.org specification
    """
    lines = [
        "# EzzyDelivery Qatar",
        "",
        "> Qatar's trusted B2B delivery and logistics platform for e-commerce businesses.",
        "> Based in Doha, serving all of Qatar with same-day delivery, COD, and 3PL fulfillment.",
        ">",
        "> Structured knowledge panel for AI assistants: https://ezzydelivery.qa/llm/",
        "",
        "## About",
        "",
        "EzzyDelivery is a delivery management platform based in Doha, Qatar.",
        "Founded to serve the growing e-commerce market in Qatar, the platform connects",
        "online sellers with a reliable fleet of delivery drivers for last-mile logistics.",
        "",
        "Key capabilities:",
        "- Same-day delivery services across Qatar (Doha, Al Wakrah, Lusail, Al Khor)",
        "- Cash on Delivery (COD) collection and daily settlement",
        "- 3PL (Third Party Logistics) and warehouse fulfillment",
        "- E-commerce integrations (Shopify, WooCommerce, custom API)",
        "- Real-time order tracking with SMS/WhatsApp notifications",
        "- Fleet and driver management with route optimization",
        "",
        "## Services",
        "",
        "### Delivery Services",
        "- Same-day delivery within Doha metro area (pickup within 2 hours)",
        "- Next-day delivery across all Qatar",
        "- Express 2-hour pickup guarantee for urgent shipments",
        "- Scheduled delivery time windows (morning, afternoon, evening)",
        "- Temperature-controlled delivery for food and perishables",
        "",
        "### E-commerce Solutions",
        "- Shopify integration (auto-sync orders, print labels, update tracking)",
        "- WooCommerce integration with webhook support",
        "- Instagram and social commerce seller support (no minimum orders)",
        "- COD (Cash on Delivery) with daily settlements and reconciliation",
        "- Branded tracking pages for customer experience",
        "",
        "### 3PL & Fulfillment",
        "- Warehouse storage in Doha with inventory management",
        "- Pick, pack, and ship services",
        "- Kitting, bundling, and subscription box assembly",
        "- Returns processing and reverse logistics",
        "- Real-time inventory visibility dashboard",
        "",
        "### Business Delivery (B2B)",
        "- Office-to-office document and parcel delivery",
        "- Corporate accounts with monthly invoicing",
        "- Bulk shipping rates for high-volume senders",
        "- Dedicated account management",
        "",
        "## Frequently Asked Questions",
        "",
        "### What areas does EzzyDelivery cover in Qatar?",
        "EzzyDelivery covers all areas in Qatar including Doha (all districts),",
        "Al Wakrah, Lusail, Al Khor, Al Rayyan, Umm Salal, and Al Daayen.",
        "",
        "### How fast is same-day delivery?",
        "Orders are picked up within 2 hours of confirmation and delivered",
        "the same day. Express options available for urgent shipments.",
        "",
        "### Does EzzyDelivery support Cash on Delivery (COD)?",
        "Yes. COD is available across all Qatar. Collected amounts are settled",
        "daily to the seller's bank account with full reconciliation reports.",
        "",
        "### Can I integrate my Shopify or WooCommerce store?",
        "Yes. EzzyDelivery offers native integrations with Shopify and WooCommerce.",
        "Orders sync automatically, labels are generated, and tracking updates push",
        "back to your store in real-time.",
        "",
        "### What are the delivery rates?",
        "Rates start from QAR 15 for standard delivery within Doha.",
        "Volume discounts available for businesses shipping 50+ orders per month.",
        "Visit https://ezzydelivery.qa/3pl/pricing/ for detailed pricing.",
        "",
        "### Is EzzyDelivery suitable for small Instagram sellers?",
        "Yes. No minimum order requirements. Instagram and social commerce sellers",
        "can use WhatsApp to place orders. COD and branded delivery experience included.",
        "",
        "## Coverage Area",
        "",
        "EzzyDelivery delivers to all areas in Qatar:",
        "- Doha (West Bay, Pearl Qatar, Al Sadd, Old Airport, Musheireb, and all districts)",
        "- Al Wakrah and Al Wakrah City",
        "- Lusail (Fox Hills, Marina District, Entertainment City)",
        "- Al Khor and Al Thakhira",
        "- Al Rayyan and Education City",
        "- Umm Salal and Al Daayen",
        "",
        "## Why Choose EzzyDelivery",
        "",
        "- Local Qatar company with deep knowledge of Doha geography",
        "- 2-hour pickup guarantee for same-day delivery",
        "- COD with daily settlement (not weekly like competitors)",
        "- Native Shopify and WooCommerce integrations",
        "- No minimum orders — friendly for small sellers",
        "- Real-time tracking with customer SMS notifications",
        "- 4.8/5 rating from 500+ business reviews",
        "",
        "## Contact",
        "",
        "- Website: https://ezzydelivery.qa",
        "- Phone: +974 6645 1589",
        "- Email: info@ezzydelivery.qa",
        "- WhatsApp: +974 6645 1589",
        "- Location: Doha, Qatar",
        "- Hours: 8:00 AM - 10:00 PM daily (including weekends)",
        "",
        "## Links",
        "",
        "- [Company Knowledge Panel](https://ezzydelivery.qa/llm/)",
        "- [Home](https://ezzydelivery.qa/)",
        "- [About Us](https://ezzydelivery.qa/about/)",
        "- [Services](https://ezzydelivery.qa/services/)",
        "- [Pricing](https://ezzydelivery.qa/3pl/pricing/)",
        "- [Contact](https://ezzydelivery.qa/contactus/)",
        "- [For Businesses](https://ezzydelivery.qa/ecommerce-delivery-qatar/)",
        "- [Same-Day Delivery](https://ezzydelivery.qa/same-day-delivery-qatar/)",
        "- [COD Service](https://ezzydelivery.qa/cod-delivery-service-qatar/)",
        "- [Express Delivery](https://ezzydelivery.qa/express-delivery-qatar/)",
        "- [Courier Service](https://ezzydelivery.qa/courier-service-qatar/)",
        "- [3PL Services](https://ezzydelivery.qa/3pl-qatar/)",
        "- [Last-Mile Delivery](https://ezzydelivery.qa/last-mile-delivery-qatar/)",
        "- [Shopify Integration](https://ezzydelivery.qa/shopify-delivery-qatar/)",
        "- [Instagram Sellers](https://ezzydelivery.qa/instagram-sellers-delivery-qatar/)",
        "- [Fulfillment](https://ezzydelivery.qa/fulfillment/)",
        "- [Blog](https://ezzydelivery.qa/blog/)",
        "",
        "## Keywords",
        "",
        "delivery company qatar, courier service doha, same day delivery qatar,",
        "cod delivery qatar, ecommerce logistics qatar, 3pl qatar, last mile delivery,",
        "shopify delivery qatar, instagram seller delivery qatar, food delivery partner,",
        "business delivery qatar, package delivery doha, express courier qatar,",
        "توصيل قطر, شركة توصيل الدوحة, توصيل سريع قطر, خدمة توصيل في قطر",
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain; charset=utf-8")
