# Generated by Django 5.1.2 on 2024-10-27 04:20

import django.db.models.deletion
import fleet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('driver_code', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_code_dms', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_phone', models.CharField(max_length=100)),
                ('driver_whatsapp', models.CharField(max_length=100)),
                ('driver_bio', models.CharField(blank=True, max_length=225, null=True)),
                ('driver_languages', models.CharField(choices=[('arabic', 'Arabic'), ('english', 'English'), ('hindi', 'Hindi'), ('philipine', 'Philipine'), ('other', 'Other')], max_length=100)),
                ('driver_license_number', models.CharField(max_length=100)),
                ('driver_rating', models.IntegerField(default=0)),
                ('driver_rating_count', models.IntegerField(default=0)),
                ('driver_reviews', models.TextField(default='')),
                ('driver_reviews_count', models.IntegerField(default=0)),
                ('driver_status', models.CharField(choices=[('Pending on Review', 'Pending on Review'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Blocked', 'Blocked')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='core.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('QID', 'QID'), ('Driving License', 'Driving License'), ('Passport', 'Passport'), ('National Identification', 'National Identification')], max_length=100, null=True)),
                ('document_no', models.CharField(max_length=100)),
                ('document_issued_from', models.CharField(blank=True, max_length=100, null=True)),
                ('document_expiry_date', models.DateField(blank=True, null=True)),
                ('document_file', models.ImageField(blank=True, default='core/driver/default/doc_default.png', null=True, upload_to=fleet.models.upload_path_handler)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_document', to='fleet.driver')),
            ],
            options={
                'verbose_name_plural': 'Driver Documents',
            },
        ),
        migrations.CreateModel(
            name='DriverVacancyAplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('whatsapp_no', models.IntegerField()),
                ('landmark', models.CharField(max_length=100)),
                ('zone_name', models.CharField(max_length=100)),
                ('licence', models.CharField(choices=[('none', 'None'), ('2wheeler', '2 Wheeler'), ('4wheeler', '4 Wheeler'), ('heavy', 'Heavy')], max_length=100)),
                ('is_in_qatar', models.BooleanField(default=False)),
                ('job_type', models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time'), ('both', 'Both')], max_length=100)),
                ('own_vehicle', models.CharField(choices=[('none', 'None'), ('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('pickup', 'Pickup'), ('pickup3ton', 'Pickup 3Ton'), ('pickup_big', 'Pickup Big Items')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Driver Job',
            },
        ),
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('none', 'None'), ('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('pickup', 'Pickup'), ('pickup3ton', 'Pickup 3Ton'), ('pickup_big', 'Pickup Big Items')], default='none', max_length=100)),
                ('vehicle_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Inactive', max_length=100)),
                ('vehicle_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicle', to='fleet.driver')),
            ],
            options={
                'verbose_name_plural': 'Driver Vehicles',
            },
        ),
    ]
