# Generated by Django 5.2 on 2026-01-12 14:36

import django.db.models.deletion
import fleet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('driver_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('driver_code_dms', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_phone', models.CharField(max_length=100)),
                ('driver_whatsapp', models.CharField(max_length=100)),
                ('driver_bio', models.CharField(blank=True, max_length=225, null=True)),
                ('driver_languages', models.CharField(choices=[('arabic', 'Arabic'), ('english', 'English'), ('hindi', 'Hindi'), ('philipine', 'Philipine'), ('other', 'Other')], max_length=100)),
                ('driver_license_number', models.CharField(max_length=100)),
                ('driver_rating', models.IntegerField(default=0)),
                ('driver_rating_count', models.IntegerField(default=0)),
                ('driver_reviews', models.TextField(default='')),
                ('driver_reviews_count', models.IntegerField(default=0)),
                ('driver_status', models.CharField(choices=[('Pending on Review', 'Pending on Review'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Blocked', 'Blocked')], db_index=True, max_length=100)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance (decreases when COD collected, increases when submitted)', max_digits=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=5000.0, help_text='Maximum COD credit limit based on driver performance and trustworthiness', max_digits=10)),
                ('cod_in_hand', models.DecimalField(decimal_places=2, default=0.0, help_text="Total COD currently in driver's possession", max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total lifetime earnings from deliveries', max_digits=10)),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Earnings pending settlement since last payout', max_digits=10)),
                ('last_settlement_date', models.DateTimeField(blank=True, help_text='Last date when earnings were settled/paid', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='core.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('QID', 'QID'), ('Driving License', 'Driving License'), ('Passport', 'Passport'), ('National Identification', 'National Identification')], max_length=100, null=True)),
                ('document_no', models.CharField(max_length=100)),
                ('document_issued_from', models.CharField(blank=True, max_length=100, null=True)),
                ('document_expiry_date', models.DateField(blank=True, null=True)),
                ('document_file', models.ImageField(blank=True, default='core/driver/default/doc_default.png', null=True, upload_to=fleet.models.upload_path_handler)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_document', to='fleet.driver')),
            ],
            options={
                'verbose_name_plural': 'Driver Documents',
            },
        ),
        migrations.CreateModel(
            name='DriverSettlement',
            fields=[
                ('settlement_id', models.AutoField(primary_key=True, serialize=False)),
                ('settlement_code', models.CharField(max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_delivery_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings before deductions', max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, help_text='Total deductions (damages, violations, etc.)', max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0.0, help_text='Performance bonuses and incentives', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final amount to be paid (gross + bonuses - deductions)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Cash, Bank Transfer, etc.', max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID or reference number', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='fleet.driver')),
            ],
            options={
                'verbose_name_plural': 'Driver Settlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earning', 'Task Earning'), ('cod_collection', 'COD Collection'), ('cod_deposit', 'COD Deposit to Admin'), ('settlement', 'Earnings Settlement'), ('deduction', 'Deduction'), ('bonus', 'Bonus/Incentive'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for credits, negative for debits', max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_balance_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cod_in_hand_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_earnings_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='delivery.deliverytask')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fleet.driver')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fleet.driversettlement')),
            ],
            options={
                'verbose_name_plural': 'Driver Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverVacancyAplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('whatsapp_no', models.IntegerField()),
                ('landmark', models.CharField(max_length=100)),
                ('zone_name', models.CharField(max_length=100)),
                ('licence', models.CharField(choices=[('none', 'None'), ('2wheeler', '2 Wheeler'), ('4wheeler', '4 Wheeler'), ('heavy', 'Heavy')], max_length=100)),
                ('is_in_qatar', models.BooleanField(default=False)),
                ('job_type', models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time'), ('both', 'Both')], max_length=100)),
                ('own_vehicle', models.CharField(choices=[('none', 'None'), ('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('pickup', 'Pickup'), ('pickup3ton', 'Pickup 3Ton'), ('pickup_big', 'Pickup Big Items')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Driver Job',
            },
        ),
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('none', 'None'), ('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('pickup', 'Pickup'), ('pickup3ton', 'Pickup 3Ton'), ('pickup_big', 'Pickup Big Items')], default='none', max_length=100)),
                ('vehicle_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='Inactive', max_length=100)),
                ('vehicle_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicle', to='fleet.driver')),
            ],
            options={
                'verbose_name_plural': 'Driver Vehicles',
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['user', 'driver_status'], name='driver_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['driver_code'], name='driver_code_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['created_at'], name='driver_created_idx'),
        ),
        migrations.AddIndex(
            model_name='drivervehicle',
            index=models.Index(fields=['driver', 'vehicle_status'], name='vehicle_driver_status_idx'),
        ),
    ]
