# Generated by Django 5.1.7 on 2025-11-14 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverytask_cod_collected_and_more'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cod_in_hand',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Total COD currently in driver's possession", max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Maximum COD credit limit based on driver performance and trustworthiness', max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_settlement_date',
            field=models.DateTimeField(blank=True, help_text='Last date when earnings were settled/paid', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='pending_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Earnings pending settlement since last payout', max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total lifetime earnings from deliveries', max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance (decreases when COD collected, increases when submitted)', max_digits=10),
        ),
        migrations.CreateModel(
            name='DriverSettlement',
            fields=[
                ('settlement_id', models.AutoField(primary_key=True, serialize=False)),
                ('settlement_code', models.CharField(max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_delivery_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings before deductions', max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, help_text='Total deductions (damages, violations, etc.)', max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0.0, help_text='Performance bonuses and incentives', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final amount to be paid (gross + bonuses - deductions)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Cash, Bank Transfer, etc.', max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID or reference number', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='fleet.driver')),
            ],
            options={
                'verbose_name_plural': 'Driver Settlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earning', 'Task Earning'), ('cod_collection', 'COD Collection'), ('cod_deposit', 'COD Deposit to Admin'), ('settlement', 'Earnings Settlement'), ('deduction', 'Deduction'), ('bonus', 'Bonus/Incentive'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for credits, negative for debits', max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_balance_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cod_in_hand_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_earnings_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='delivery.deliverytask')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fleet.driver')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fleet.driversettlement')),
            ],
            options={
                'verbose_name_plural': 'Driver Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
