# Generated by Django 5.2 on 2026-01-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_add_zone_group'),
        ('fleet', '0002_add_driver_preferred_zones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='preferred_zones',
        ),
        migrations.AddField(
            model_name='driver',
            name='preferred_zone_groups',
            field=models.ManyToManyField(blank=True, help_text="Driver's preferred delivery zone groups", related_name='drivers', to='delivery.zonegroup'),
        ),
    ]
