# Generated by Django 5.1.7 on 2025-11-16 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_is_business_profile_completed_and_more'),
        ('fleet', '0002_driver_cod_in_hand_driver_credit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_status',
            field=models.CharField(choices=[('Pending on Review', 'Pending on Review'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Blocked', 'Blocked')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='Inactive', max_length=100),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['user', 'driver_status'], name='driver_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['driver_code'], name='driver_code_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['created_at'], name='driver_created_idx'),
        ),
        migrations.AddIndex(
            model_name='drivervehicle',
            index=models.Index(fields=['driver', 'vehicle_status'], name='vehicle_driver_status_idx'),
        ),
    ]
