# Generated by Django 5.2 on 2026-01-16 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_driver_driver_code_alter_driver_driver_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('settlement', 'Settlement Receipt'), ('cod_deposit', 'COD Deposit Receipt'), ('earnings', 'Earnings Statement'), ('transaction', 'Transaction Receipt')], max_length=20)),
                ('paper_size', models.CharField(choices=[('thermal_80', 'Thermal 80mm'), ('thermal_58', 'Thermal 58mm'), ('a4', 'A4 Paper'), ('a5', 'A5 Paper'), ('letter', 'Letter')], default='thermal_80', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('show_logo', models.BooleanField(default=True)),
                ('company_name', models.CharField(default='Ezzy Delivery', max_length=200)),
                ('company_address', models.TextField(blank=True, default='Doha, Qatar')),
                ('company_phone', models.CharField(blank=True, default='+974-XXXX-XXXX', max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_color', models.CharField(default='#2196F3', max_length=7)),
                ('font_family', models.CharField(default='Courier New, monospace', max_length=100)),
                ('font_size', models.IntegerField(default=12)),
                ('show_signature_line', models.BooleanField(default=True)),
                ('show_qr_code', models.BooleanField(default=False)),
                ('show_barcode', models.BooleanField(default=False)),
                ('footer_message', models.TextField(default='Thank you for your service!')),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS to override default styles', null=True)),
                ('custom_template', models.TextField(blank=True, help_text='Custom HTML template content', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Receipt Templates',
                'ordering': ['template_type', '-is_default', 'name'],
            },
        ),
    ]
