# Generated by Django 5.2.9 on 2026-01-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_update_driver_zone_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('atm', 'ATM Deposit'), ('fawran', 'Fawran')], default='cash', help_text='Payment method for COD deposit/settlement', max_length=20, null=True),
        ),
    ]
