# Generated by Django 5.2 on 2026-02-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_zonename_options_zonename_is_active_and_more'),
        ('fleet', '0004_receipttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='preferred_zone_groups',
            field=models.ManyToManyField(blank=True, help_text="Driver's preferred delivery zone groups", related_name='drivers', to='delivery.zonegroup'),
        ),
    ]
