# Generated by Django 5.2.9 on 2026-01-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_add_payment_method_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertransaction',
            name='transaction_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique transaction code (auto-generated)', max_length=50, null=True, unique=True),
        ),
    ]
