# Generated by Django 5.2.9 on 2026-02-02 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessteampermission_and_more'),
        ('fleet', '0005_add_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertransaction',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business associated with this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='business.business'),
        ),
        migrations.AlterField(
            model_name='drivertransaction',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fleet.driver'),
        ),
        migrations.AlterField(
            model_name='drivertransaction',
            name='transaction_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique transaction code (auto-generated, format: TYPECODE-YYYYMMDD-SEQ)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='drivertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('cod_collection', 'COD Collection'), ('cod_driver_settle', 'COD Driver Settlement'), ('cod_client_settle', 'COD Client Settlement'), ('cod_return', 'COD Return'), ('delivery_charge', 'Delivery Charge'), ('fulfillment_charge', 'Fulfillment Charge'), ('inventory_handling', 'Inventory Handling Charge'), ('other_charge', 'Other Charges'), ('bills_payable', 'Bills Payable'), ('bills_receivable', 'Bills Receivable'), ('earning', 'Task Earning'), ('settlement', 'Earnings Settlement'), ('deduction', 'Deduction'), ('bonus', 'Bonus/Incentive'), ('adjustment', 'Manual Adjustment'), ('cod_deposit', 'COD Deposit to Admin')], max_length=30),
        ),
    ]
