# Generated by Django 5.2 on 2026-02-06 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_businessapisettings_tiktok_refresh_token_and_more'),
        ('delivery', '0008_deliverytask_calculated_earnings_and_more'),
        ('fleet', '0006_add_transaction_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='drivertransaction',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business associated with this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='business.business'),
        ),
        migrations.AddField(
            model_name='drivertransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='drivertransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('atm', 'ATM Deposit'), ('fawran', 'Fawran')], default='cash', help_text='Payment method for COD deposit/settlement', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drivertransaction',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fleet.driver'),
        ),
        migrations.AlterField(
            model_name='drivertransaction',
            name='transaction_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique transaction code (auto-generated, format: TYPECODE-YYYYMMDD-SEQ)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='drivertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('cod_collection', 'COD Collection'), ('cod_driver_settle', 'COD Driver Settlement'), ('cod_client_settle', 'COD Client Settlement'), ('cod_return', 'COD Return'), ('delivery_charge', 'Delivery Charge'), ('fulfillment_charge', 'Fulfillment Charge'), ('inventory_handling', 'Inventory Handling Charge'), ('other_charge', 'Other Charges'), ('bills_payable', 'Bills Payable'), ('bills_receivable', 'Bills Receivable'), ('earning', 'Task Earning'), ('settlement', 'Earnings Settlement'), ('deduction', 'Deduction'), ('bonus', 'Bonus/Incentive'), ('adjustment', 'Manual Adjustment'), ('cod_deposit', 'COD Deposit to Admin')], max_length=30),
        ),
        migrations.CreateModel(
            name='ZoneEarningsRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('normal_delivery', 'Normal Delivery (Fulfillment)'), ('pick_and_drop', 'Pick and Drop')], default='normal_delivery', help_text='Order type this rate applies to', max_length=20)),
                ('driver_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Driver earnings rate in QR', max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Per kilometer rate for distance-based calculation', max_digits=10)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Base rate before distance calculation', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_zone', models.ForeignKey(help_text='Delivery zone', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_earnings_rates', to='delivery.zonename')),
                ('pickup_zone', models.ForeignKey(blank=True, help_text='Pickup zone (only for pick & drop orders)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_earnings_rates', to='delivery.zonename')),
            ],
            options={
                'verbose_name': 'Zone Earnings Rate',
                'verbose_name_plural': 'Zone Earnings Rates',
                'ordering': ['order_type', 'delivery_zone__zone_number'],
                'unique_together': {('order_type', 'pickup_zone', 'delivery_zone')},
            },
        ),
    ]
