# Generated by Django 5.2.9 on 2026-02-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_drivertransaction_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='drivertransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
