# Generated by Django 5.2 on 2026-02-21 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_change_phone_whatsapp_to_charfield'),
        ('delivery', '0009_deliverytask_payment_method_and_more'),
        ('fleet', '0007_remove_drivertransaction_transaction_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_availability',
            field=models.CharField(choices=[('offline', 'Offline'), ('available', 'Available'), ('on_delivery', 'On Delivery'), ('on_break', 'On Break'), ('returning', 'Returning')], db_index=True, default='offline', help_text='Real-time availability status of the driver', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=100),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['driver_availability'], name='driver_avail_idx'),
        ),
    ]
