# Generated by Django 5.2.11 on 2026-02-04 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_earnings_verification'),
        ('fleet', '0007_remove_drivertransaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneEarningsRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('normal_delivery', 'Normal Delivery (Fulfillment)'), ('pick_and_drop', 'Pick and Drop')], default='normal_delivery', help_text='Order type this rate applies to', max_length=20)),
                ('driver_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Driver earnings rate in QR', max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Per kilometer rate for distance-based calculation', max_digits=10)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Base rate before distance calculation', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_zone', models.ForeignKey(help_text='Delivery zone', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_earnings_rates', to='delivery.zonename')),
                ('pickup_zone', models.ForeignKey(blank=True, help_text='Pickup zone (only for pick & drop orders)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_earnings_rates', to='delivery.zonename')),
            ],
            options={
                'verbose_name': 'Zone Earnings Rate',
                'verbose_name_plural': 'Zone Earnings Rates',
                'ordering': ['order_type', 'delivery_zone__zone_number'],
                'unique_together': {('order_type', 'pickup_zone', 'delivery_zone')},
            },
        ),
    ]
