# Generated by Django 5.2 on 2026-02-21 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_driver_driver_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('delivery_assigned', 'Delivery Assigned'), ('cod_collected', 'COD Collected'), ('earnings_settled', 'Earnings Settled'), ('alert', 'Alert'), ('system', 'System')], default='system', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fleet.driver')),
            ],
            options={
                'verbose_name': 'Driver Notification',
                'verbose_name_plural': 'Driver Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
