# Generated by Django 5.2 on 2026-02-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_drivernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivervehicle',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='fleet/vehicles/'),
        ),
    ]
