# Generated by Django 5.2 on 2026-02-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_deliverytask_payment_method_and_more'),
        ('fleet', '0010_add_vehicle_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('task_taken', 'Task Taken'), ('task_accepted', 'Task Accepted'), ('task_picked_up', 'Task Picked Up'), ('task_start_ride', 'Start Ride'), ('task_out_delivery', 'Out for Delivery'), ('task_delivered', 'Task Delivered'), ('task_failed', 'Task Failed'), ('task_contacted', 'Customer Contacted'), ('task_non_reachable', 'Customer Non-Reachable'), ('cod_collected', 'COD Collected'), ('cod_submitted', 'COD Submitted'), ('earning_credited', 'Earning Credited'), ('settlement', 'Wallet Settlement'), ('login', 'Login'), ('logout', 'Logout'), ('profile_updated', 'Profile Updated'), ('document_uploaded', 'Document Uploaded'), ('vehicle_added', 'Vehicle Added'), ('pickup_scanned', 'Pickup Scanned')], db_index=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='fleet.driver')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_activity_logs', to='delivery.deliverytask')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='fleet.drivertransaction')),
            ],
            options={
                'verbose_name': 'Driver Activity Log',
                'verbose_name_plural': 'Driver Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', '-created_at'], name='fleet_drive_driver__cec5c2_idx'), models.Index(fields=['activity_type', '-created_at'], name='fleet_drive_activit_9ca1f1_idx')],
            },
        ),
    ]
