# Generated by Django 5.2 on 2026-02-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_add_driver_activity_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_code_dms',
        ),
    ]
