# Generated by Django 5.2.11 on 2026-03-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_drivervehicle_vehicle_photo_drivernotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_code_dms',
        ),
    ]
