# Generated by Django 5.2.11 on 2026-03-04 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_driver_location_model'),
        ('fleet', '0013_remove_driver_driver_code_dms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in metres', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading in degrees', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='fleet.driver')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_locations', to='delivery.deliverytask')),
            ],
            options={
                'verbose_name': 'Driver Location',
                'verbose_name_plural': 'Driver Locations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', '-created_at'], name='driverloc_driver_ts_idx')],
            },
        ),
    ]
