# Generated by Django 5.2.11 on 2026-03-08 10:44

import django.db.models.deletion
import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_driver_location_model'),
        ('fleet', '0014_driver_location_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='document_file_back',
            field=models.ImageField(blank=True, null=True, upload_to=fleet.models.upload_path_handler_back),
        ),
        migrations.AddField(
            model_name='drivernotification',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_notifications', to='delivery.deliverytask'),
        ),
    ]
