# Generated by Django 5.2.11 on 2026-03-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_driverdocument_document_file_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivernotification',
            name='notification_type',
            field=models.CharField(choices=[('delivery_assigned', 'Delivery Assigned'), ('cod_collected', 'COD Collected'), ('earnings_settled', 'Earnings Settled'), ('order_comment', 'Order Comment'), ('alert', 'Alert'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
