# Generated by Django 5.2.11 on 2026-03-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_add_order_comment_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Miscellaneous driver metadata (push notification tokens, app settings, etc.)'),
        ),
    ]
