# Generated by Django 5.2.11 on 2026-04-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_add_driver_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivervacancyaplication',
            name='mobile_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='drivervacancyaplication',
            name='whatsapp_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='inactive', max_length=100),
        ),
    ]
