# Generated by Django 5.2.11 on 2026-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_alter_drivervacancyaplication_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('pos', 'POS / Card'), ('fawran', 'Fawran'), ('bank', 'Bank Transfer'), ('atm', 'ATM Deposit')], default='cash', help_text='Payment method for COD deposit/settlement', max_length=20, null=True),
        ),
    ]
