# Generated by Django 5.2.11 on 2026-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0019_alter_drivertransaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertransaction',
            name='is_received',
            field=models.BooleanField(default=False, help_text='Admin confirmed cash was physically received from driver'),
        ),
        migrations.AddField(
            model_name='drivertransaction',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin verified the submitted COD amount is correct'),
        ),
    ]
