# Generated by Django 5.2.11 on 2026-04-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_add_is_received_is_verified_to_driver_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertransaction',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approved / finalised this COD submission'),
        ),
    ]
