# Generated by Django 5.2.12 on 2026-04-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_add_cod_submission_fk_and_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertransaction',
            name='cod_atm_after',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='drivertransaction',
            name='cod_bank_after',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='drivertransaction',
            name='cod_cash_after',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='drivertransaction',
            name='cod_fawran_after',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='drivertransaction',
            name='cod_pos_after',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
