# Generated by Django 5.2.12 on 2026-05-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_drivertransaction_cod_atm_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='to_be_notified',
            field=models.BooleanField(db_index=True, default=True, help_text="Include this driver in auto-task WhatsApp/push notifications (broadcasts via 'all_active_drivers', 'available_drivers', 'zone_drivers' autoflow recipients)."),
        ),
    ]
