# Generated by Django 5.2.12 on 2026-06-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_driver_to_be_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='has_driver_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
