# Generated by Django 5.2.12 on 2026-06-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0024_driver_has_driver_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('QID', 'QID'), ('Passport', 'Passport'), ('Driving License', 'Driving License'), ('Istimara', 'Istimara'), ('National Identification', 'National Identification')], max_length=100, null=True),
        ),
    ]
