# Generated by Django 5.2.16 on 2026-07-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0026_alter_drivertransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Selfie', 'Selfie'), ('QID', 'QID'), ('Passport', 'Passport'), ('Driving License', 'Driving License'), ('Istimara', 'Istimara'), ('National Identification', 'National Identification')], max_length=100, null=True),
        ),
    ]
