# Generated by Django 5.2.16 on 2026-07-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_alter_driverdocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivernotification',
            name='notification_type',
            field=models.CharField(choices=[('delivery_assigned', 'Delivery Assigned'), ('pickup_available', 'Pickup Available'), ('pickup_transfer', 'Pickup Transfer Request'), ('cod_collected', 'COD Collected'), ('earnings_settled', 'Earnings Settled'), ('order_comment', 'Order Comment'), ('alert', 'Alert'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
