# Generated by Django 5.2.16 on 2026-07-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0028_alter_drivernotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('flexible', 'Flexible / Both')], default='', help_text='Employment preference declared by the driver (full time / part time / flexible)', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='work_time_slabs',
            field=models.CharField(blank=True, default='', help_text='Comma-separated preferred working time slabs (keys from WORK_TIME_SLAB_CHOICES)', max_length=100),
        ),
    ]
