# Generated by Django 5.2.16 on 2026-07-28 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_driver_job_type_driver_work_time_slabs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPayoutDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('delivery_charge', 'Delivery Charge'), ('fulfillment_charge', 'Fulfillment Charge'), ('inventory_handling', 'Cargo / Handling Charge'), ('other_charge', 'Other Charge')], default='other_charge', max_length=30)),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge_txn', models.ForeignKey(blank=True, help_text='Revenue transaction booked for this line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deduction_line', to='fleet.drivertransaction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_deductions_created', to=settings.AUTH_USER_MODEL)),
                ('settle_txn', models.ForeignKey(help_text='The cod_client_settle transaction this line was deducted from', on_delete=django.db.models.deletion.CASCADE, related_name='payout_deductions', to='fleet.drivertransaction')),
            ],
            options={
                'verbose_name': 'Business Payout Deduction',
                'verbose_name_plural': 'Business Payout Deductions',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['settle_txn'], name='fleet_busin_settle__0a3d79_idx')],
            },
        ),
    ]
