# Generated by Django 5.2.16 on 2026-08-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0030_businesspayoutdeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='fixed_at',
            field=models.DateTimeField(blank=True, help_text='When the device took the fix. Older than created_at for cached or replayed pings.', null=True),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='queued',
            field=models.BooleanField(default=False, help_text="Replayed from the driver's offline queue rather than sent live."),
        ),
    ]
