# Generated by Django 5.2.16 on 2026-08-08 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_businessapisettings_last_sync_at_and_more'),
        ('delivery', '0044_deliverytask_cod_reconciled_and_more'),
        ('fleet', '0031_driverlocation_fixed_at_driverlocation_queued'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('cod_collection', 'COD Collection'), ('cod_driver_settle', 'COD Driver Settlement'), ('cod_client_settle', 'COD Client Settlement'), ('cod_client_settle_reversal', 'COD Client Settlement Reversal'), ('cod_return', 'COD Return'), ('delivery_charge', 'Delivery Charge'), ('fulfillment_charge', 'Fulfillment Charge'), ('inventory_handling', 'Inventory Handling Charge'), ('other_charge', 'Other Charges'), ('bills_payable', 'Bills Payable'), ('bills_receivable', 'Bills Receivable'), ('client_payment', 'Client Payment Received'), ('earning', 'Task Earning'), ('settlement', 'Earnings Settlement'), ('deduction', 'Deduction'), ('bonus', 'Bonus/Incentive'), ('adjustment', 'Manual Adjustment'), ('cod_deposit', 'COD Deposit to Admin')], max_length=30),
        ),
        migrations.CreateModel(
            name='BusinessChargeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('part_paid', 'Partly Paid'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='issued', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_invoices', to='business.business')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_invoices_issued', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_invoices_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Charge Invoice',
                'verbose_name_plural': 'Business Charge Invoices',
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessChargeInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('delivery_charge', 'Delivery Charge'), ('fulfillment_charge', 'Fulfillment Charge'), ('inventory_handling', 'Cargo / Handling Charge'), ('other_charge', 'Other Charge')], default='delivery_charge', max_length=30)),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge_txn', models.ForeignKey(blank=True, help_text='Revenue transaction booked for this line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='fleet.drivertransaction')),
                ('delivery_task', models.ForeignKey(blank=True, help_text='The delivery this line bills; blank for hand-added charges', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_invoice_lines', to='delivery.deliverytask')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fleet.businesschargeinvoice')),
            ],
            options={
                'verbose_name': 'Business Charge Invoice Line',
                'verbose_name_plural': 'Business Charge Invoice Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('pos', 'POS / Card'), ('fawran', 'Fawran'), ('bank', 'Bank Transfer'), ('atm', 'ATM Deposit')], default='bank', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fleet.businesschargeinvoice')),
                ('payment_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payments', to='fleet.drivertransaction')),
            ],
            options={
                'verbose_name': 'Business Invoice Payment',
                'verbose_name_plural': 'Business Invoice Payments',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='businesschargeinvoice',
            index=models.Index(fields=['business', 'status'], name='fleet_busin_busines_195eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='businesschargeinvoice',
            index=models.Index(fields=['-issued_at'], name='fleet_busin_issued__696a22_idx'),
        ),
        migrations.AddIndex(
            model_name='businesschargeinvoiceline',
            index=models.Index(fields=['invoice'], name='fleet_busin_invoice_969b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='businesschargeinvoiceline',
            index=models.Index(fields=['delivery_task'], name='fleet_busin_deliver_aef309_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinvoicepayment',
            index=models.Index(fields=['invoice'], name='fleet_busin_invoice_0d0e16_idx'),
        ),
    ]
