# Generated by Django 5.2.16 on 2026-08-08 16:32

import core.validators
import django.core.validators
import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0032_alter_drivertransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='document_file',
            field=models.ImageField(blank=True, default='core/driver/default/doc_default.png', null=True, upload_to=fleet.models.upload_path_handler, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(8)]),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='document_file_back',
            field=models.ImageField(blank=True, null=True, upload_to=fleet.models.upload_path_handler_back, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(8)]),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='fleet/vehicles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(8)]),
        ),
    ]
