# Generated by Django 5.2.16 on 2026-08-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0033_alter_driverdocument_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesschargeinvoice',
            name='column_keys',
            field=models.JSONField(blank=True, default=list, help_text='Columns this invoice shows, overriding Business.invoice_columns'),
        ),
    ]
