# Generated by Django 5.2.16 on 2026-08-24 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0034_businesschargeinvoice_column_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(help_text="Random server-issued id, held in the driver's device cookie.", max_length=64, unique=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Awaiting verification'), ('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('label', models.CharField(blank=True, help_text="Human-readable guess at the handset, e.g. 'Android · Chrome'.", max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='First successful verification. A device that has one is never asked for a code again.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('new_device', 'Signed in on another device'), ('staff', 'Revoked by staff')], max_length=20)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_send_count', models.PositiveSmallIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Set when ops released the device instead of a WhatsApp code.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_devices_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Device',
                'verbose_name_plural': 'Driver Devices',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='fleet_drive_user_id_6efcce_idx')],
            },
        ),
    ]
