# Generated by Django 5.2.16 on 2026-09-03 04:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0047_alter_deliverytaskqrcode_qrcode'),
        ('fleet', '0035_driverdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverNavHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('waze', 'Waze'), ('google', 'Google Maps'), ('other', 'Other app')], default='other', max_length=10)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, help_text='When the driver came back to the PWA. Null while still in the nav app.', null=True)),
                ('from_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('from_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('to_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('to_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('dest_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('dest_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('route_polyline', models.TextField(blank=True, default='', help_text='JSON [[lat, lng], ...] reconstructing the gap. An estimate, not measured.')),
                ('route_km', models.FloatField(blank=True, help_text='Road distance across the gap, km', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_handoffs', to='fleet.driver')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_handoffs', to='delivery.deliverytask')),
            ],
            options={
                'verbose_name': 'Driver Nav Handoff',
                'verbose_name_plural': 'Driver Nav Handoffs',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['driver', '-opened_at'], name='navhandoff_driver_ts_idx')],
            },
        ),
    ]
