# Generated by Django 5.2.16 on 2026-09-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0036_drivernavhandoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivernavhandoff',
            name='provider',
            field=models.CharField(choices=[('waze', 'Waze'), ('google', 'Google Maps'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone call'), ('other', 'Other app')], default='other', max_length=10),
        ),
    ]
