# Generated by Django 5.2.16 on 2026-09-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0037_alter_drivernavhandoff_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivernavhandoff',
            name='auto',
            field=models.BooleanField(default=False, help_text='Opened by the page losing the foreground rather than by a tap on a link. Catches the gaps no button can see: the screen locking, the home button, an app opened from the notification shade.'),
        ),
        migrations.AddField(
            model_name='drivernavhandoff',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('return', 'Driver came back'), ('ping', 'Device reported in'), ('superseded', 'Another handoff opened')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='drivernavhandoff',
            name='left_foreground',
            field=models.BooleanField(blank=True, help_text='Whether the page actually went to the background. Null when the client never said.', null=True),
        ),
        migrations.AlterField(
            model_name='drivernavhandoff',
            name='provider',
            field=models.CharField(choices=[('waze', 'Waze'), ('google', 'Google Maps'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone call'), ('background', 'App in background'), ('other', 'Other app')], default='other', max_length=10),
        ),
    ]
