# Generated by Django 5.2.16 on 2026-09-03 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0047_alter_deliverytaskqrcode_qrcode'),
        ('fleet', '0038_drivernavhandoff_auto_drivernavhandoff_close_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivernavhandoff',
            name='pickup_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_handoffs', to='delivery.pickuptask'),
        ),
    ]
