# Generated by Django 5.2.16 on 2026-09-07 18:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_business_invoice_columns'),
        ('delivery', '0047_alter_deliverytaskqrcode_qrcode'),
        ('fleet', '0039_drivernavhandoff_pickup_task'),
        ('orders', '0063_order_delivery_area_name_order_delivery_area_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_code', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('occurred_on', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.CharField(choices=[('opening', 'Opening Balance'), ('cod', 'COD Collected'), ('delivery_charge', 'Delivery Charge'), ('expense', 'Expense Recharged'), ('credit', 'Credit Issued'), ('advance', 'Advance Paid'), ('payout', 'COD Payout'), ('payment', 'Payment Received'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], db_index=True, max_length=20)),
                ('kind', models.CharField(blank=True, help_text='For charge segments, the DriverTransaction type that booked it', max_length=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('cleared', 'Cleared'), ('void', 'Void')], db_index=True, default='open', max_length=12)),
                ('billing_state', models.CharField(choices=[('unbilled', 'Unbilled'), ('billed', 'Billed'), ('not_billable', 'Not Billable')], default='not_billable', max_length=14)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.CharField(max_length=200)),
                ('order_number', models.CharField(blank=True, max_length=64, null=True)),
                ('task_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='business.business')),
                ('charge_invoice', models.ForeignKey(blank=True, help_text='Set when this entry was billed on an invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='fleet.businesschargeinvoice')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='delivery.deliverytask')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='fleet.driver')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.order')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='fleet.businessledgerentry')),
                ('txn', models.ForeignKey(blank=True, help_text='The money row this entry accounts for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='fleet.drivertransaction')),
            ],
            options={
                'verbose_name': 'Business Ledger Entry',
                'verbose_name_plural': 'Business Ledger Entries',
                'ordering': ['occurred_on', 'id'],
                'indexes': [models.Index(fields=['business', 'occurred_on'], name='fleet_busin_busines_7bf7d2_idx'), models.Index(fields=['business', 'segment', 'status'], name='fleet_busin_busines_315322_idx'), models.Index(fields=['business', 'billing_state'], name='fleet_busin_busines_253267_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit', 0), ('credit', 0), _connector='OR'), name='ledger_entry_single_sided'), models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='ledger_entry_non_negative')],
            },
        ),
    ]
