# Generated by Django 5.2.16 on 2026-09-09 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0040_businessledgerentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesschargeinvoiceline',
            name='amend_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesschargeinvoiceline',
            name='amended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesschargeinvoiceline',
            name='amended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_invoice_lines_amended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesschargeinvoiceline',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What this line said before the first amendment; blank if never amended', max_digits=10, null=True),
        ),
    ]
