# Generated by Django 5.2.16 on 2026-09-09 16:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0042_renumber_charge_invoices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_fee', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='QAR paid for a normal (fulfilment) delivery.', max_digits=10)),
                ('hub_fee', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='QAR paid for the hub delivery leg (leg 2 of a two-leg job).', max_digits=10)),
                ('pick_and_drop_percent', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Percent of the client delivery charge paid on a pick & drop job.', max_digits=5)),
                ('effective_from', models.DateField(help_text='First day this card applies.')),
                ('effective_to', models.DateField(blank=True, help_text='Last day it applies. Empty means it is still running.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_pay_rates_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, help_text='Leave empty for the fleet-wide card. Set it to pay one driver differently - a per-driver card always beats the fleet card.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_rates', to='fleet.driver')),
            ],
            options={
                'verbose_name': 'Delivery Pay Rate',
                'verbose_name_plural': 'Delivery Pay Rates',
                'ordering': ['-effective_from', '-id'],
                'indexes': [models.Index(fields=['driver', 'effective_from'], name='fleet_deliv_driver__eba4ca_idx')],
            },
        ),
    ]
