# Generated by Django 5.2.16 on 2026-09-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0043_deliverypayrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='payout_columns',
            field=models.JSONField(blank=True, default=list, help_text='Default payout-invoice columns for this driver (keys from fleet.payout_columns)'),
        ),
        migrations.AddField(
            model_name='driversettlement',
            name='column_keys',
            field=models.JSONField(blank=True, default=list, help_text='Columns this payout invoice shows, overriding Driver.payout_columns'),
        ),
    ]
