# Generated by Django 5.2.16 on 2026-09-18 06:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0044_driver_payout_columns_driversettlement_column_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypayrate',
            name='exchange_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='QAR paid for an exchange visit — replacement handed over and the original collected in one trip. Starts level with a normal delivery; raise it here if the round trip should pay more.', max_digits=10),
        ),
    ]
