# Generated by Django 5.2.17 on 2026-09-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0045_deliverypayrate_exchange_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(help_text='Push service URL the browser issued for this device.', unique=True)),
                ('p256dh', models.CharField(help_text='Device public key (payload encryption).', max_length=255)),
                ('auth', models.CharField(help_text='Device auth secret (payload encryption).', max_length=255)),
                ('user_agent', models.CharField(blank=True, help_text='Recorded so staff can tell which phone stopped accepting pushes.', max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('last_failure', models.CharField(blank=True, max_length=200)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='fleet.driver')),
            ],
            options={
                'verbose_name': 'Driver Push Subscription',
                'verbose_name_plural': 'Driver Push Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'is_active'], name='driverpush_driver_live_idx')],
            },
        ),
    ]
