# Generated by Django 5.2.17 on 2026-09-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0046_driverpushsubscription'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='driver',
            name='driver_code_idx',
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
