# Generated by Django 5.2.17 on 2026-09-22 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0047_remove_driver_driver_code_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='dashboard_access_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Cleared to work: tasks, pickups, COD and earnings. Separate from driver_status — an approved driver without this sees only their profile and the opportunities board.'),
        ),
        migrations.AddField(
            model_name='driver',
            name='dashboard_access_granted_at',
            field=models.DateTimeField(blank=True, help_text='When dashboard access was last granted', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='dashboard_access_granted_by',
            field=models.ForeignKey(blank=True, help_text='Staff user who last granted dashboard access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_driver_dashboard_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
