# Generated by Django 5.2.17 on 2026-09-22 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0043_business_return_destination'),
        ('delivery', '0054_remove_parcelcustody_uniq_open_parcel_custody_per_task_and_more'),
        ('dispatch', '0001_initial'),
        ('fleet', '0049_backfill_driver_dashboard_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('vehicle_type', models.CharField(blank=True, choices=[('none', 'None'), ('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('pickup', 'Pickup'), ('pickup3ton', 'Pickup 3Ton'), ('pickup_big', 'Pickup Big Items')], default='', help_text='Vehicle this work needs; blank means any', max_length=100)),
                ('job_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('flexible', 'Flexible / Both')], default='', help_text='Full time / part time / flexible', max_length=20)),
                ('pay_note', models.CharField(blank=True, default='', help_text="Free text, e.g. 'QAR 25/hour + fuel'. Not a rate card — actual pay always resolves through delivery/earnings.py.", max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, help_text='Stop showing this posting after this time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(blank=True, help_text='Store this work is based at. Required before a confirmed interest can be turned into a dispatch RiderShift.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='business.pickuplocation')),
                ('zone_groups', models.ManyToManyField(blank=True, help_text='Zone groups this work covers; blank means anywhere', related_name='opportunities', to='delivery.zonegroup')),
            ],
            options={
                'verbose_name': 'Driver Opportunity',
                'verbose_name_plural': 'Driver Opportunities',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverOpportunitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('time_slab', models.CharField(blank=True, choices=[('morning', 'Morning (6 AM – 12 PM)'), ('afternoon', 'Afternoon (12 PM – 6 PM)'), ('evening', 'Evening (6 PM – 12 AM)'), ('night', 'Night (12 AM – 6 AM)')], default='', help_text='Label only, for matching against Driver.work_time_slabs', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='How many drivers can be confirmed onto this slot')),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='fleet.driveropportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Slot',
                'verbose_name_plural': 'Opportunity Slots',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverOpportunityInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('shortlisted', 'Shortlisted'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='interested', max_length=20)),
                ('note', models.CharField(blank=True, default='', help_text='Anything the driver wanted to add', max_length=300)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_opportunity_interests', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_interests', to='fleet.driver')),
                ('rider_shift', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_interest', to='dispatch.ridershift')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='fleet.driveropportunityslot')),
            ],
            options={
                'verbose_name': 'Opportunity Interest',
                'verbose_name_plural': 'Opportunity Interests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='driveropportunity',
            index=models.Index(fields=['status', 'published_at'], name='opp_status_published_idx'),
        ),
        migrations.AddIndex(
            model_name='driveropportunityslot',
            index=models.Index(fields=['status', 'starts_at'], name='oppslot_status_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='driveropportunityslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='opportunity_slot_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='driveropportunityinterest',
            index=models.Index(fields=['driver', 'status'], name='oppint_driver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='driveropportunityinterest',
            index=models.Index(fields=['slot', 'status'], name='oppint_slot_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driveropportunityinterest',
            unique_together={('slot', 'driver')},
        ),
    ]
