# Generated by Django 5.2.17 on 2026-09-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0050_driveropportunity_driveropportunityslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_sponsor',
            field=models.CharField(blank=True, default='', help_text="Sponsor / company on the driver's QID (free text — usually an outside firm)", max_length=150),
        ),
    ]
