# Generated by Django 5.2.17 on 2026-09-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0051_driver_driver_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('cod_collection', 'COD Collection'), ('cod_driver_settle', 'COD Driver Settlement'), ('cod_client_settle', 'COD Client Settlement'), ('cod_client_settle_reversal', 'COD Client Settlement Reversal'), ('cod_return', 'COD Return'), ('fee_collection', 'Delivery Fee Collected in Cash'), ('delivery_charge', 'Delivery Charge'), ('fulfillment_charge', 'Fulfillment Charge'), ('inventory_handling', 'Inventory Handling Charge'), ('other_charge', 'Other Charges'), ('bills_payable', 'Bills Payable'), ('bills_receivable', 'Bills Receivable'), ('client_payment', 'Client Payment Received'), ('earning', 'Task Earning'), ('settlement', 'Earnings Settlement'), ('deduction', 'Deduction'), ('bonus', 'Bonus/Incentive'), ('adjustment', 'Manual Adjustment'), ('cod_deposit', 'COD Deposit to Admin')], max_length=30),
        ),
    ]
