# Generated by Django 5.2.17 on 2026-09-24 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0056_deliverytask_fee_collected_amount_and_more'),
        ('fleet', '0052_alter_drivertransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('ref_code', models.CharField(blank=True, default='', help_text='Optional public reference shown on the careers page, e.g. EZY-DRV-01', max_length=20)),
                ('headline', models.CharField(blank=True, default='', help_text='One line under the title — the offer in a sentence', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='What the work involves and who it suits')),
                ('pay_package', models.CharField(blank=True, default='', help_text="Free text for the advert, e.g. 'QAR 3,500/month + fuel'. Not a rate card — actual pay always resolves through delivery/earnings.py.", max_length=200)),
                ('job_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('flexible', 'Flexible / Both')], default='', help_text='Full time / part time / flexible; blank means any', max_length=20)),
                ('vehicle_type', models.CharField(blank=True, choices=[('none', 'None'), ('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('pickup', 'Pickup'), ('pickup3ton', 'Pickup 3Ton'), ('pickup_big', 'Pickup Big Items')], default='', help_text='Vehicle this offer needs; blank means any', max_length=100)),
                ('perks', models.TextField(blank=True, default='', help_text='One perk per line')),
                ('requirements', models.TextField(blank=True, default='', help_text='One requirement per line')),
                ('show_in_driver_app', models.BooleanField(default=True, help_text='Show on the driver app opportunities screen')),
                ('show_on_careers', models.BooleanField(default=True, help_text='Show in the driver offers section of /careers/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, help_text='Stop showing this offer after this time', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first on both surfaces')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_driver_proposals', to=settings.AUTH_USER_MODEL)),
                ('zone_groups', models.ManyToManyField(blank=True, help_text='Zone groups this offer covers; blank means anywhere', related_name='driver_proposals', to='delivery.zonegroup')),
            ],
            options={
                'verbose_name': 'Driver Proposal',
                'verbose_name_plural': 'Driver Proposals',
                'ordering': ['display_order', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'display_order'], name='drvprop_status_order_idx')],
            },
        ),
    ]
