# Generated by Django 5.2.17 on 2026-09-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0053_driverproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertransaction',
            name='cod_fee_after',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
