# Generated by Django 5.2.17 on 2026-09-26 19:56

import core.validators
import django.core.validators
import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0054_drivertransaction_cod_fee_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='document_file_back_original',
            field=models.ImageField(blank=True, null=True, upload_to=fleet.models.upload_path_handler_back_original, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(8)]),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='document_file_original',
            field=models.ImageField(blank=True, null=True, upload_to=fleet.models.upload_path_handler_original, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(8)]),
        ),
    ]
