# Generated by Django 5.2.17 on 2026-09-29 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0055_driverdocument_document_file_back_original_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProposalInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'New'), ('contacted', 'Contacted'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='interested', max_length=20)),
                ('note', models.CharField(blank=True, default='', help_text='Anything the driver wanted to add', max_length=300)),
                ('staff_note', models.CharField(blank=True, default='', help_text='Internal — what staff agreed or why it was declined', max_length=500)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_proposal_interests', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_interests', to='fleet.driver')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='fleet.driverproposal')),
            ],
            options={
                'verbose_name': 'Proposal Interest',
                'verbose_name_plural': 'Proposal Interests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['proposal', 'status'], name='propint_prop_status_idx')],
                'unique_together': {('proposal', 'driver')},
            },
        ),
    ]
