# Generated by Django 5.2.17 on 2026-10-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0056_driverproposalinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverproposal',
            name='ref_code',
            field=models.CharField(blank=True, default='', help_text='Optional public reference shown on the driver jobs page, e.g. EZY-DRV-01', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverproposal',
            name='show_on_careers',
            field=models.BooleanField(default=True, help_text='Show on the public driver jobs page, /careers/drivers/'),
        ),
    ]
