# Generated by Django 5.2.17 on 2026-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0057_driver_proposal_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='ai_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='ai_document_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='ai_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='ai_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='ai_status',
            field=models.CharField(blank=True, choices=[('pending', 'Waiting for image check'), ('verified', 'Verification done'), ('mismatch', 'Does not match the image'), ('unreadable', 'Image could not be read'), ('error', 'Image check failed'), ('no_image', 'No image to check'), ('not_needed', 'No check needed')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
