# Generated by Django 5.2 on 2026-01-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Meta description (140-155 chars)', max_length=160),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='DEPRECATED - Meta keywords no longer used by search engines', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO title (50-60 chars)', max_length=70),
        ),
    ]
