# Generated by Django 5.2 on 2026-01-12 14:36

import business.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location_title', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('pickup_zone_no', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_street_no', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_building_no', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('pickup_lon', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('pickup_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('aproval pending', 'Aproval Pending'), ('suspended', 'Suspended')], default='active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pickup Location',
                'db_table': 'client_pickuplocation',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_bio', models.CharField(blank=True, max_length=225, null=True)),
                ('business_code', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('business_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('business_email', models.CharField(blank=True, max_length=100, null=True)),
                ('business_whatsapp', models.CharField(blank=True, max_length=100, null=True)),
                ('business_facebook_page', models.CharField(blank=True, max_length=100, null=True)),
                ('business_instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('business_since', models.DateField(blank=True, max_length=100, null=True)),
                ('business_product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('business_languages', models.CharField(default='english', max_length=100)),
                ('business_qid', models.CharField(blank=True, max_length=11, null=True)),
                ('business_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Aproval Pending'), ('suspended', 'Suspended')], default='aproval pending', max_length=100)),
                ('fulfillment_service_enabled', models.BooleanField(default=False, help_text='Enable fulfillment service (WMS integration) for this business')),
                ('fulfillment_activated_at', models.DateTimeField(blank=True, help_text='When the fulfillment service was activated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_business', to='core.profile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Business',
                'db_table': 'client_business',
            },
        ),
        migrations.CreateModel(
            name='BusinessApiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'Woocommerce'), ('magento', 'Magento'), ('opencart', 'Opencart'), ('prestashop', 'Prestashop'), ('bigcommerce', 'Bigcommerce'), ('custom', 'Custom')], default='custom', max_length=100)),
                ('api_access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('api_version', models.CharField(blank=True, max_length=100, null=True)),
                ('site_api_url', models.CharField(blank=True, max_length=100, null=True)),
                ('site_contry', models.CharField(blank=True, default='Qatar', max_length=100, null=True)),
                ('order_api_endpoint', models.CharField(blank=True, max_length=100, null=True)),
                ('product_api_endpoint', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verify_api', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('business_languages', models.CharField(default='english', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_settings_api', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Business Settings',
                'db_table': 'client_businessapisettings',
            },
        ),
        migrations.CreateModel(
            name='BusinessLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_logo', models.ImageField(blank=True, default='business/avatar.png', null=True, upload_to=business.models.upload_path_handler)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_logo', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Business Logo',
                'db_table': 'client_businesslogo',
            },
        ),
        migrations.CreateModel(
            name='BusinessPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_image', models.ImageField(blank=True, help_text='Upload promotional poster/banner image', null=True, upload_to=business.models.upload_path_handler)),
                ('poster_title', models.CharField(blank=True, help_text='Optional title for the poster', max_length=200, null=True)),
                ('poster_description', models.TextField(blank=True, help_text='Optional description', max_length=500, null=True)),
                ('poster_order', models.PositiveIntegerField(default=0, help_text='Display order (0-5)')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this poster')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_posters', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Business Posters',
                'db_table': 'client_businessposter',
                'ordering': ['poster_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_description', models.TextField(blank=True, max_length=225, null=True)),
                ('business_address', models.CharField(blank=True, max_length=225, null=True)),
                ('business_city', models.CharField(blank=True, max_length=100, null=True)),
                ('business_state', models.CharField(blank=True, max_length=100, null=True)),
                ('business_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('business_country', models.CharField(blank=True, default='Qatar', max_length=100, null=True)),
                ('business_start_date', models.DateField(blank=True, max_length=100, null=True)),
                ('business_founters_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_founters_bio', models.CharField(blank=True, max_length=100, null=True)),
                ('business_mision', models.TextField(blank=True, max_length=25, null=True)),
                ('business_mision_detailed', models.TextField(blank=True, max_length=125, null=True)),
                ('business_about_part_1', models.TextField(blank=True, max_length=125, null=True)),
                ('business_about_part_2', models.TextField(blank=True, max_length=125, null=True)),
                ('business_uniqueness_title', models.CharField(blank=True, max_length=225, null=True)),
                ('business_uniqueness_description', models.TextField(blank=True, max_length=225, null=True)),
                ('business_catagory_main', models.CharField(blank=True, max_length=20, null=True)),
                ('business_catagory_detailed', models.TextField(blank=True, max_length=100, null=True)),
                ('business_website', models.CharField(blank=True, max_length=100, null=True)),
                ('business_facebook_page', models.CharField(blank=True, max_length=100, null=True)),
                ('business_instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('business_tiktok', models.CharField(blank=True, max_length=100, null=True)),
                ('business_youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('business_twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('business_linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('business_snapchat', models.CharField(blank=True, max_length=100, null=True)),
                ('business_email', models.CharField(blank=True, max_length=100, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Business Profile',
                'db_table': 'client_businessprofile',
            },
        ),
        migrations.CreateModel(
            name='BusinessSocialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_social_info', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Business Social Info',
                'db_table': 'client_businesssocialinfo',
            },
        ),
        migrations.CreateModel(
            name='BusinessTeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_code', models.CharField(blank=True, max_length=100, null=True)),
                ('team_role', models.CharField(blank=True, max_length=100, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('team_email', models.CharField(blank=True, max_length=100, null=True)),
                ('team_bio', models.CharField(blank=True, max_length=225, null=True)),
                ('team_logo', models.ImageField(blank=True, default='business/avatar.png', null=True, upload_to=business.models.upload_path_handler)),
                ('team_verifed', models.BooleanField(default=False)),
                ('team_status', models.CharField(choices=[('aproval pending', 'Aproval Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='aproval pending', max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to='business.business')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_profile', to='core.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff Profile',
                'db_table': 'client_businessteamprofile',
            },
        ),
        migrations.CreateModel(
            name='DriverDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_directory', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Drivers Directories',
                'db_table': 'client_driverdirectory',
            },
        ),
    ]
