# Generated by Django 5.1.2 on 2024-10-27 04:21

import business.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_bio', models.CharField(blank=True, max_length=225, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('business_email', models.CharField(blank=True, max_length=100, null=True)),
                ('business_whatsapp', models.CharField(blank=True, max_length=100, null=True)),
                ('business_facebook_page', models.CharField(blank=True, max_length=100, null=True)),
                ('business_instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('business_since', models.DateField(blank=True, max_length=100, null=True)),
                ('business_product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('business_code', models.CharField(blank=True, max_length=100, null=True)),
                ('business_languages', models.CharField(default='english', max_length=100)),
                ('business_qid', models.CharField(blank=True, max_length=11, null=True)),
                ('business_status', models.CharField(default='aproval pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to='core.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Business',
            },
        ),
        migrations.CreateModel(
            name='BusinessLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_logo', models.ImageField(blank=True, default='business/avatar.png', null=True, upload_to=business.models.upload_path_handler)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_logo', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Business Logo',
            },
        ),
        migrations.CreateModel(
            name='BusinessSocialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_social_info', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='DriverDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_directory', to='business.business')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_directory', to='fleet.driver')),
            ],
            options={
                'verbose_name_plural': 'Drivers Directories',
            },
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location_title', models.CharField(max_length=100)),
                ('pickup_zone_no', models.PositiveIntegerField(blank=True)),
                ('pickup_street_no', models.PositiveIntegerField(blank=True)),
                ('pickup_building_no', models.PositiveIntegerField(blank=True)),
                ('pickup_lat', models.PositiveIntegerField(blank=True)),
                ('pickup_lon', models.PositiveIntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_location', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Pickup Location',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_code', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_email', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_bio', models.CharField(blank=True, max_length=225, null=True)),
                ('staff_logo', models.ImageField(blank=True, default='business/avatar.png', null=True, upload_to=business.models.upload_path_handler)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='business.business')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to='core.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff Profile',
                'unique_together': {('business', 'staff_code')},
            },
        ),
    ]
