# Generated by Django 5.1.2 on 2024-10-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_building_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_lat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_lon',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_street_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_zone_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
