# Generated by Django 5.2 on 2026-01-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdirectory',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_directory', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_location', to='business.business'),
        ),
        migrations.AlterUniqueTogether(
            name='businessteamprofile',
            unique_together={('business', 'team_code')},
        ),
    ]
