# Generated by Django 5.1.2 on 2024-10-28 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_pickuplocation_pickup_building_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessApiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'Woocommerce'), ('magento', 'Magento'), ('opencart', 'Opencart'), ('prestashop', 'Prestashop'), ('bigcommerce', 'Bigcommerce'), ('custom', 'Custom')], default='custom', max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('site_api_url', models.CharField(blank=True, max_length=100, null=True)),
                ('order_api_url', models.CharField(blank=True, max_length=100, null=True)),
                ('product_api_url', models.CharField(blank=True, max_length=100, null=True)),
                ('verify_api', models.BooleanField(default=False)),
                ('business_languages', models.CharField(default='english', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_settings', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
