# Generated by Django 5.2.9 on 2026-02-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessteampermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Approval Pending'), ('suspended', 'Suspended')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Approval Pending'), ('suspended', 'Suspended')], default='active', max_length=100),
        ),
    ]
