# Generated by Django 5.1.2 on 2024-10-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_business_profile_alter_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessapisettings',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_api_settings', to='business.business'),
        ),
    ]
