# Generated by Django 5.1.2 on 2024-10-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_businessapisettings_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='staff_status',
            field=models.CharField(choices=[('aproval pending', 'Aproval Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='aproval pending', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_verifed',
            field=models.BooleanField(default=False),
        ),
    ]
