# Generated by Django 5.2.11 on 2026-02-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_pickuplocation_is_fulfilment_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='fulfillment_service_status',
            field=models.CharField(choices=[('none', 'Not Requested'), ('requested', 'Requested'), ('active', 'Active')], default='none', help_text='Fulfillment service status: none, requested, or active', max_length=20),
        ),
    ]
