# Generated by Django 5.1.2 on 2024-10-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_staffprofile_staff_status_staffprofile_staff_verifed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='locality',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
