# Generated by Django 5.1.2 on 2024-10-28 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_pickuplocation_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='pickup_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('aproval pending', 'Aproval Pending'), ('suspended', 'Suspended')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('aproval pending', 'Aproval Pending'), ('suspended', 'Suspended')], default='aproval pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessapisettings',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_settings_api', to='business.business'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_status',
            field=models.CharField(choices=[('aproval pending', 'Aproval Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='aproval pending', max_length=100),
        ),
    ]
