# Generated by Django 5.2.11 on 2026-02-12 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_add_fulfillment_service_status'),
        ('warehouse', '0003_sellerwarehouselink_warehouselocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Linked warehouse (auto-set when business is connected to a warehouse)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_pickup_locations', to='warehouse.warehouse'),
        ),
    ]
