# Generated by Django 5.1.2 on 2024-10-28 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_pickuplocation_pickup_status_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='staff_bio',
            new_name='team_bio',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='staff_code',
            new_name='team_code',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='staff_email',
            new_name='team_email',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='staff_logo',
            new_name='team_logo',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='staff_name',
            new_name='team_name',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='staff_phone',
            new_name='team_phone',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='staff_status',
            new_name='team_status',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='staff_verifed',
            new_name='team_verifed',
        ),
        migrations.AlterUniqueTogether(
            name='staffprofile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to='business.business'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_profile', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='staffprofile',
            unique_together={('business', 'team_code')},
        ),
    ]
