# Generated by Django 5.2.11 on 2026-02-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_pickuplocation_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessteamprofile',
            name='team_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
