# Generated by Django 5.1.2 on 2024-10-28 22:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_rename_staff_bio_staffprofile_team_bio_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffProfile',
            new_name='BusinessTeamProfile',
        ),
    ]
