# Generated by Django 5.2.11 on 2026-02-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_add_rejected_status_to_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='fulfillment_service_enabled',
            field=models.BooleanField(default=True, help_text='Enable fulfillment service (WMS integration) for this business'),
        ),
    ]
