# Generated by Django 5.1.2 on 2024-10-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_rename_staffprofile_businessteamprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='site_contry',
            field=models.CharField(blank=True, default='Qatar', max_length=100, null=True),
        ),
    ]
