# Generated by Django 5.2.11 on 2026-03-03 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_fulfillment_default_true'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Pre-selected as pickup location when creating new orders'),
        ),
        migrations.CreateModel(
            name='BusinessTeamJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_role_title', models.CharField(blank=True, help_text="Desired position/role title as entered by the user (e.g. 'Sales Manager')", max_length=100)),
                ('message', models.TextField(blank=True, help_text='Optional message to the business owner')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='business.business')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Join Request',
                'verbose_name_plural': 'Team Join Requests',
                'db_table': 'client_businessteamjoinrequest',
                'indexes': [models.Index(fields=['business', 'status'], name='client_busi_busines_45c4d8_idx'), models.Index(fields=['user', 'status'], name='client_busi_user_id_a9ce55_idx')],
                'unique_together': {('business', 'user')},
            },
        ),
    ]
