# Generated by Django 5.2.11 on 2026-03-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_pickuplocation_is_default_businessteamjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='google_sheet_url',
            field=models.TextField(blank=True, help_text='Google Sheets URL (published as CSV or shareable link)', null=True),
        ),
        migrations.AlterField(
            model_name='businessapisettings',
            name='api_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('tiktokshop', 'TikTok Shop'), ('magento', 'Magento'), ('opencart', 'OpenCart'), ('prestashop', 'PrestaShop'), ('bigcommerce', 'BigCommerce'), ('google_sheet', 'Google Sheet'), ('custom', 'Custom')], default='custom', max_length=100),
        ),
    ]
