# Generated by Django 5.1.2 on 2024-10-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_businessapisettings_site_contry'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessteamprofile',
            name='team_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
