# Generated by Django 5.2.11 on 2026-03-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_businessapisettings_google_sheet_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='column_mapping',
            field=models.JSONField(blank=True, default=None, help_text='Google Sheet column mapping: {"customer_name": "Col Header", "phone": "Col Header", ...}', null=True),
        ),
    ]
