# Generated by Django 5.1.2 on 2024-10-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_businessteamprofile_team_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='api_access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
