# Generated by Django 5.1.2 on 2024-11-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_businessapisettings_api_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='api_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
