# Generated by Django 5.2.11 on 2026-03-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_add_column_mapping_to_api_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='import_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Shared import column mapping for all sources: {col_idx_str: db_field}'),
        ),
    ]
