# Generated by Django 5.2.11 on 2026-03-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_add_import_mapping_to_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='import_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Shared import column mapping for all sources: {db_field: source_column_header}'),
        ),
    ]
