# Generated by Django 5.1.2 on 2024-11-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_businessapisettings_api_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessapisettings',
            old_name='verify_api',
            new_name='is_verify_api',
        ),
        migrations.RenameField(
            model_name='businessapisettings',
            old_name='order_api_url',
            new_name='order_api_endpoint',
        ),
        migrations.RenameField(
            model_name='businessapisettings',
            old_name='product_api_url',
            new_name='product_api_endpoint',
        ),
    ]
