# Generated by Django 5.2.11 on 2026-03-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_business_import_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='fulfillment_service_status',
            field=models.CharField(choices=[('none', 'Not Requested'), ('not_required', 'Not Required'), ('requested', 'Requested'), ('active', 'Active')], default='none', help_text='Fulfillment service status: none, not_required, requested, or active', max_length=20),
        ),
    ]
