# Generated by Django 5.1.2 on 2024-11-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_rename_verify_api_businessapisettings_is_verify_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
