# Generated by Django 5.2.11 on 2026-03-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_alter_business_fulfillment_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='temp_order_enabled',
            field=models.BooleanField(default=False, help_text='Enable temp order sync for this business'),
        ),
    ]
