# Generated by Django 5.1.7 on 2025-05-25 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_businessapisettings_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Aproval Pending'), ('suspended', 'Suspended')], default='aproval pending', max_length=100),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_description', models.TextField(blank=True, max_length=225, null=True)),
                ('business_address', models.CharField(blank=True, max_length=225, null=True)),
                ('business_city', models.CharField(blank=True, max_length=100, null=True)),
                ('business_state', models.CharField(blank=True, max_length=100, null=True)),
                ('business_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('business_country', models.CharField(blank=True, default='Qatar', max_length=100, null=True)),
                ('business_start_date', models.DateField(blank=True, max_length=100, null=True)),
                ('business_founters_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_founters_bio', models.CharField(blank=True, max_length=100, null=True)),
                ('business_mision', models.TextField(blank=True, max_length=25, null=True)),
                ('business_mision_detailed', models.TextField(blank=True, max_length=125, null=True)),
                ('business_about_part_1', models.TextField(blank=True, max_length=125, null=True)),
                ('business_about_part_2', models.TextField(blank=True, max_length=125, null=True)),
                ('business_uniqueness_title', models.CharField(blank=True, max_length=225, null=True)),
                ('business_uniqueness_description', models.TextField(blank=True, max_length=225, null=True)),
                ('business_catagory_main', models.CharField(blank=True, max_length=20, null=True)),
                ('business_catagory_detailed', models.TextField(blank=True, max_length=100, null=True)),
                ('business_website', models.CharField(blank=True, max_length=100, null=True)),
                ('business_facebook_page', models.CharField(blank=True, max_length=100, null=True)),
                ('business_instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('business_tiktok', models.CharField(blank=True, max_length=100, null=True)),
                ('business_youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('business_email', models.CharField(blank=True, max_length=100, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Business Profile',
            },
        ),
    ]
