# Generated by Django 5.2.11 on 2026-04-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_add_temp_order_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessteamprofile',
            name='team_logo',
            field=models.ImageField(blank=True, default='business/avatar.png', null=True, upload_to='business/team_logos/'),
        ),
    ]
