# Generated by Django 5.2.11 on 2026-04-02 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_alter_businessteamprofile_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotificationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_status', models.CharField(choices=[('assigned', 'Driver Assigned'), ('picked_up', 'Picked Up'), ('start_ride', 'Start Ride'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_message', models.TextField(blank=True, default='', help_text='Custom message template. Use {customer_name}, {order_number}, {driver_name}, {driver_phone}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_triggers', to='business.business')),
            ],
            options={
                'db_table': 'business_whatsapp_trigger',
                'unique_together': {('business', 'trigger_status')},
            },
        ),
    ]
