# Generated by Django 5.1.7 on 2025-11-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_alter_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_code',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_lon',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True),
        ),
    ]
