# Generated by Django 5.2.11 on 2026-04-02 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_whatsappnotificationtrigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandedTrackingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#f7c000', help_text='Hex color for header/buttons', max_length=7)),
                ('secondary_color', models.CharField(default='#001f3f', help_text='Hex color for text/accents', max_length=7)),
                ('show_driver_name', models.BooleanField(default=True)),
                ('show_driver_phone', models.BooleanField(default=False)),
                ('show_eta', models.BooleanField(default=True)),
                ('custom_footer_text', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_config', to='business.business')),
            ],
            options={
                'db_table': 'business_branded_tracking_config',
            },
        ),
    ]
