# Generated by Django 5.1.7 on 2025-11-13 21:34

import business.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_business_business_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_snapchat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BusinessPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_image', models.ImageField(blank=True, help_text='Upload promotional poster/banner image', null=True, upload_to=business.models.upload_path_handler)),
                ('poster_title', models.CharField(blank=True, help_text='Optional title for the poster', max_length=200, null=True)),
                ('poster_description', models.TextField(blank=True, help_text='Optional description', max_length=500, null=True)),
                ('poster_order', models.PositiveIntegerField(default=0, help_text='Display order (0-5)')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this poster')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_posters', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Business Posters',
                'ordering': ['poster_order', '-created_at'],
            },
        ),
    ]
