# Generated by Django 5.2.12 on 2026-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_add_product_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnotificationtrigger',
            name='notification_phone',
            field=models.CharField(blank=True, default='', help_text='Additional phone number (with country code, e.g. 97455512345) that should also receive this notification. Leave blank to notify customer only.', max_length=30),
        ),
    ]
