# Generated by Django 5.2.12 on 2026-04-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_whatsappnotificationtrigger_notification_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='google_sheet_gid',
            field=models.BigIntegerField(blank=True, help_text='Worksheet (tab) gid to import from. NULL = use first tab or gid in URL.', null=True),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='google_sheet_tab_name',
            field=models.CharField(blank=True, default='', help_text='Last-known title of the selected worksheet (display only).', max_length=255),
        ),
    ]
