# Generated by Django 5.2 on 2025-12-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_rename_tables'),
    ]

    operations = [
        migrations.RunSQL(
            # Add columns to business_business table (renamed from client_business in 0021)
            sql="""
                ALTER TABLE business_business
                ADD COLUMN IF NOT EXISTS fulfillment_service_enabled BOOLEAN DEFAULT FALSE;

                ALTER TABLE business_business
                ADD COLUMN IF NOT EXISTS fulfillment_activated_at TIMESTAMP WITH TIME ZONE NULL;
            """,
            reverse_sql="""
                ALTER TABLE business_business DROP COLUMN IF EXISTS fulfillment_service_enabled;
                ALTER TABLE business_business DROP COLUMN IF EXISTS fulfillment_activated_at;
            """
        ),
    ]
