# Generated by Django 5.2.12 on 2026-04-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_businessapisettings_google_sheet_gid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='last_headers',
            field=models.JSONField(blank=True, default=list, help_text='Last-seen header row from the source sheet, used to map raw_row positions to db fields.'),
        ),
    ]
