# Generated by Django 5.2.12 on 2026-06-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_businessapisettings_last_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_tiktok',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
