# Generated by Django 5.2 on 2025-12-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_sync_table_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssocialinfo',
            options={'verbose_name_plural': 'Business Social Info'},
        ),
    ]
