# Generated by Django 5.2.16 on 2026-07-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_add_website_tiktok_to_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pickup_disposition_default',
            field=models.CharField(choices=[('drop', 'Drop at hub'), ('self_deliver', 'Deliver by self'), ('transfer', 'Transfer to another driver')], default='drop', help_text='Preset route after collection: drop at hub, deliver by self, or transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='pickup_mode_default',
            field=models.CharField(choices=[('assigned', 'Assigned fleet only'), ('public_pool', 'Public pool (all active drivers)')], default='assigned', help_text="Who may claim this business's pickup tasks", max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='pickup_task_enabled',
            field=models.BooleanField(default=False, help_text='Auto-create a first-mile pickup task when this business creates an order'),
        ),
        migrations.AddField(
            model_name='driverdirectory',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Inactive drivers stay linked but no longer see this business's assigned pickups"),
        ),
    ]
