# Generated by Django 5.2.16 on 2026-07-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_business_pickup_disposition_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Last successful sync fetch from this source (Google Sheet / Shopify / WooCommerce).', null=True),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='last_sync_count',
            field=models.PositiveIntegerField(default=0, help_text='Rows/orders seen during the last sync fetch.'),
        ),
    ]
