# Generated by Django 5.2 on 2026-01-13 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_alter_businesssocialinfo_options'),
        ('core', '0006_change_phone_whatsapp_to_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTeamPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(db_index=True, help_text='Permission code from BusinessPermissions', max_length=50)),
                ('is_granted', models.BooleanField(default=True, help_text='True = explicitly granted, False = explicitly revoked')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Permission',
                'verbose_name_plural': 'Team Permissions',
                'db_table': 'business_team_permission',
            },
        ),
        migrations.AlterModelOptions(
            name='businessteamprofile',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterUniqueTogether(
            name='businessteamprofile',
            unique_together={('business', 'team_code')},
        ),
        migrations.AddField(
            model_name='businessteamprofile',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessteamprofile',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessteamprofile',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='business.business'),
        ),
        migrations.AlterField(
            model_name='businessteamprofile',
            name='team_role',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], db_index=True, default='staff', help_text='Base role determining default permissions', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessteamprofile',
            name='team_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='businessteamprofile',
            unique_together={('business', 'team_code'), ('business', 'user')},
        ),
        migrations.AddIndex(
            model_name='businessteamprofile',
            index=models.Index(fields=['business', 'team_status'], name='client_busi_busines_ae7c90_idx'),
        ),
        migrations.AddIndex(
            model_name='businessteamprofile',
            index=models.Index(fields=['user', 'team_status'], name='client_busi_user_id_e3807d_idx'),
        ),
        migrations.AddField(
            model_name='businessteampermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_team_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessteampermission',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='business.businessteamprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='businessteampermission',
            unique_together={('team_member', 'permission_code')},
        ),
    ]
