# Generated by Django 5.2 on 2026-02-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_add_team_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='tiktok_refresh_token',
            field=models.CharField(blank=True, help_text='TikTok refresh token for renewing access token', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='tiktok_shop_cipher',
            field=models.CharField(blank=True, help_text='TikTok Shop cipher for API requests', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='tiktok_shop_id',
            field=models.CharField(blank=True, help_text='TikTok Shop ID (obtained after OAuth authorization)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='tiktok_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the TikTok access token expires', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Approval Pending'), ('suspended', 'Suspended')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessapisettings',
            name='api_access_token',
            field=models.CharField(blank=True, help_text='Access token for API authentication', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessapisettings',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key / App Key / Consumer Key', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessapisettings',
            name='api_secret',
            field=models.CharField(blank=True, help_text='API Secret / App Secret / Consumer Secret', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessapisettings',
            name='api_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('tiktokshop', 'TikTok Shop'), ('magento', 'Magento'), ('opencart', 'OpenCart'), ('prestashop', 'PrestaShop'), ('bigcommerce', 'BigCommerce'), ('custom', 'Custom')], default='custom', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessapisettings',
            name='api_version',
            field=models.CharField(blank=True, help_text='API version (e.g., 202309 for TikTok Shop)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessapisettings',
            name='order_api_endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessapisettings',
            name='product_api_endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessapisettings',
            name='site_api_url',
            field=models.CharField(blank=True, help_text='Store URL or API base URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Approval Pending'), ('suspended', 'Suspended')], default='active', max_length=100),
        ),
    ]
