# Generated by Django 5.2.16 on 2026-08-08 16:32

import business.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_businessapisettings_last_sync_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslogo',
            name='business_logo',
            field=models.ImageField(blank=True, default='business/avatar.png', null=True, upload_to=business.models.upload_path_handler, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(5)]),
        ),
    ]
