# Generated by Django 5.2 on 2026-02-21 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_businessapisettings_tiktok_refresh_token_and_more'),
        ('warehouse', '0005_add_dimensions_to_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='fulfillment_service_status',
            field=models.CharField(choices=[('none', 'Not Requested'), ('requested', 'Requested'), ('active', 'Active')], default='none', help_text='Fulfillment service status: none, requested, or active', max_length=20),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='is_fulfilment_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Linked warehouse (auto-set when business is connected to a warehouse)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_pickup_locations', to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='business',
            name='fulfillment_service_enabled',
            field=models.BooleanField(default=True, help_text='Enable fulfillment service (WMS integration) for this business'),
        ),
        migrations.AlterField(
            model_name='businessteamprofile',
            name='team_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
