# Generated by Django 5.2.16 on 2026-08-08 17:11

import business.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_alter_businesslogo_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessposter',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Upload promotional poster/banner image', null=True, upload_to=business.models.upload_path_handler, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(8)]),
        ),
        migrations.AlterField(
            model_name='businessteamprofile',
            name='team_logo',
            field=models.ImageField(blank=True, default='business/avatar.png', null=True, upload_to='business/team_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(5)]),
        ),
    ]
