# Generated by Django 5.2 on 2026-02-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_businessapisettings_tiktok_refresh_token_and_more'),
        ('warehouse', '0003_warehouse_bin_naming_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='fulfillment_service_status',
            field=models.CharField(choices=[('none', 'Not Requested'), ('requested', 'Requested'), ('active', 'Active')], default='none', help_text='Fulfillment service status: none, requested, or active', max_length=20),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='is_fulfilment_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Linked warehouse (auto-set when business is connected to a warehouse)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_pickup_locations', to='warehouse.warehouse'),
        ),
    ]
