# Generated by Django 5.2.16 on 2026-08-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_alter_businessposter_poster_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='invoice_columns',
            field=models.JSONField(blank=True, default=list, help_text='Default charge-invoice columns for this client (keys from fleet.invoice_columns)'),
        ),
    ]
