# Generated by Django 5.2 on 2026-02-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_business_fulfillment_service_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Pre-selected as pickup location when creating new orders'),
        ),
    ]
