# Generated by Django 5.2.16 on 2026-09-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_business_invoice_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='contact_name',
            field=models.CharField(blank=True, default='', help_text='Person the driver asks for at this address', max_length=100),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='contact_phone',
            field=models.CharField(blank=True, default='', help_text='Number the driver calls on arrival', max_length=20),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='is_p2p',
            field=models.BooleanField(db_index=True, default=False, help_text="One-off address from a P2P booking, not a client's saved address"),
        ),
    ]
