# Generated by Django 5.2.16 on 2026-09-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_seed_p2p_house_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='last_sample_payload',
            field=models.JSONField(blank=True, default=None, help_text='Custom API: the last sample order payload staff pasted, kept so the mapping can be tested before the seller has sent a real order.', null=True),
        ),
    ]
