# Generated by Django 5.2.16 on 2026-09-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_businessapisettings_last_sample_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pod_kind',
            field=models.CharField(choices=[('photo', 'Photo'), ('signature', 'Customer signature'), ('both', 'Photo and signature')], default='photo', help_text='What counts as proof on a successful delivery. A failed attempt always takes a photo — there is no customer present to sign for it.', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='pod_required_delivered',
            field=models.BooleanField(default=False, help_text='Driver must capture proof before a task for this client can close as delivered'),
        ),
        migrations.AddField(
            model_name='business',
            name='pod_required_failed',
            field=models.BooleanField(default=False, help_text='Driver must capture a photo before a task for this client can close as failed'),
        ),
    ]
