# Generated by Django 5.2.16 on 2026-09-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_business_pod_kind_business_pod_required_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='live_tracking_enabled',
            field=models.BooleanField(default=False, help_text="Show this client a Live Tracking map of their driver's position while a delivery is out on the road"),
        ),
    ]
