# Generated by Django 5.2.16 on 2026-09-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_backfill_live_tracking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='fetch_api_key',
            field=models.CharField(blank=True, default='', help_text="The API key the SELLER's site issued to us. Never our own ClientApiKey.", max_length=255),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='fetch_auth_name',
            field=models.CharField(blank=True, default='', help_text="Header or query-parameter name - only for the 'header' and 'query' styles (e.g. X-API-Key, api_key).", max_length=100),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='fetch_auth_style',
            field=models.CharField(choices=[('bearer', 'Authorization: Bearer <key>'), ('header', 'Custom header'), ('query', 'Query string parameter'), ('basic', 'HTTP Basic (key:secret)'), ('none', 'No authentication')], default='bearer', help_text='How the key issued by the seller is presented to their endpoint.', max_length=20),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='fetch_enabled',
            field=models.BooleanField(default=False, help_text='Include this source in the hourly order pull.'),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='fetch_list_path',
            field=models.CharField(blank=True, default='', help_text="Path to the order array inside the response, e.g. 'data.orders'. Leave empty when the response is the array itself.", max_length=200),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='fetch_orders_url',
            field=models.URLField(blank=True, default='', help_text="Full URL on the seller's own site that returns their orders as JSON, e.g. https://theirshop.com/api/orders. Leave empty for push-only.", max_length=500),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='fetch_params',
            field=models.JSONField(blank=True, default=None, help_text='Extra query string sent with every fetch, e.g. {"status": "pending", "limit": "50"}.', null=True),
        ),
    ]
