# Generated by Django 5.2.16 on 2026-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_businessapisettings_fetch_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='fetch_status_include',
            field=models.CharField(blank=True, default='', help_text="Comma-separated statuses worth delivering, e.g. 'accepted'. Orders in any other status are ignored. Empty means take every order returned.", max_length=255),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='fetch_status_path',
            field=models.CharField(blank=True, default='', help_text="Path to each order's status field, e.g. 'status'. Only used with fetch_status_include.", max_length=200),
        ),
    ]
