# Generated by Django 5.2.16 on 2026-09-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_businessapisettings_fetch_status_include_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='fetch_products_list_path',
            field=models.CharField(blank=True, default='', help_text="Path to the product array in that response, e.g. 'data.products'. Leave empty when the response is the array itself.", max_length=200),
        ),
        migrations.AddField(
            model_name='businessapisettings',
            name='fetch_products_url',
            field=models.URLField(blank=True, default='', help_text="URL on the seller's site returning their product catalogue as JSON. Separate from the order URL — an order feed says nothing about a catalogue.", max_length=500),
        ),
    ]
