# Generated by Django 5.2.16 on 2026-09-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_businessapisettings_fetch_products_list_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='product_column_mapping',
            field=models.JSONField(blank=True, default=None, help_text='Product field -> JSON path in the seller\'s product response, e.g. {"item_name": "title", "item_sku": "sku", "item_price": "price"}. Nothing is guessed: an unmapped field is simply not imported.', null=True),
        ),
    ]
