# Generated by Django 5.2.17 on 2026-09-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0041_repair_mis_flagged_fulfillment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappnotificationtrigger',
            name='custom_message',
            field=models.TextField(blank=True, default='', help_text='Custom message template. Placeholders are defined in core/trigger_tokens.py (TOKEN_GROUPS) — add one there, not here.'),
        ),
    ]
