# Generated by Django 5.2.17 on 2026-09-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0042_alter_whatsappnotificationtrigger_custom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='return_destination',
            field=models.CharField(choices=[('hub', 'Ezzy hub / warehouse'), ('business', 'Back to the business')], default='hub', help_text="Where undelivered parcels for this client are returned to. 'Back to the business' falls back to the hub when the pickup location is inactive or is itself a fulfilment centre.", max_length=20),
        ),
    ]
