# Generated by Django 5.2.17 on 2026-09-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0043_business_return_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='return_collection_destination',
            field=models.CharField(choices=[('hub', 'Ezzy hub / warehouse'), ('business', 'Back to the business')], default='business', help_text="Where goods collected back from a customer are taken. Defaults to the client's own counter; 'Ezzy hub' routes them to a hub first, which then needs a run out to the client.", max_length=20),
        ),
    ]
