# Generated by Django 5.2.17 on 2026-09-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_business_return_collection_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='customer_pays_delivery',
            field=models.BooleanField(default=False, help_text='The customer pays the delivery charge in cash at the door, on top of any COD. This client is then NOT invoiced for it.'),
        ),
    ]
