# Generated by Django 5.2.17 on 2026-09-26 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0045_business_customer_pays_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDistanceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_to_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance ceiling for this band, inclusive. Blank = no upper limit.', max_digits=7, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='QAR charged for a delivery that falls in this band.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_rates', to='business.business')),
            ],
            options={
                'verbose_name': 'Distance rate',
                'verbose_name_plural': 'Distance rates',
                'ordering': ['business', models.OrderBy(models.F('up_to_km'), nulls_last=True), 'id'],
            },
        ),
    ]
