# Generated by Django 5.2.17 on 2026-10-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0046_businessdistancerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapisettings',
            name='import_qatar_only',
            field=models.BooleanField(default=False, help_text='Only import orders shipping to Qatar. For stores that sell across the GCC: orders going anywhere else are left out of the import lists instead of being offered as deliveries we cannot make. Off by default so an existing connection keeps behaving exactly as it did.'),
        ),
    ]
