# Generated by Django 5.2.16 on 2026-09-09 12:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0048_deliverytask_driver_note_deliverytask_driver_note_at_and_more'),
        ('fleet', '0042_renumber_charge_invoices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(help_text='First day of the month this run pays.', unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_runs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_month'],
            },
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_code', models.CharField(max_length=40, unique=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deductions_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_target', models.PositiveIntegerField(default=0)),
                ('deliveries_covered', models.PositiveIntegerField(default=0, help_text='Deliveries absorbed by the salary in this month.')),
                ('deliveries_incentive', models.PositiveIntegerField(default=0, help_text='Deliveries beyond the target, paid on the per-delivery leg.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('fawran', 'Fawran')], default='', max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_slips', to='fleet.driver')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_slips_paid', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='payroll.salaryrun')),
            ],
            options={
                'ordering': ['driver_id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_deductions_created', to=settings.AUTH_USER_MODEL)),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_lines', to='payroll.salaryslip')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='Fixed monthly salary in QAR, before deductions.', max_digits=10)),
                ('delivery_target', models.PositiveIntegerField(default=0, help_text='Deliveries the salary covers in a month. Anything beyond this earns the normal per-delivery fee on top.')),
                ('effective_from', models.DateField(help_text='First day this agreement applies.')),
                ('effective_to', models.DateField(blank=True, help_text='Last day it applies. Empty means it is still running.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_structures_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='fleet.driver')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slips', to='payroll.salarystructure'),
        ),
        migrations.CreateModel(
            name='SalaryCoveredTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_covered_tasks', to='fleet.driver')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_cover', to='delivery.deliverytask')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_tasks', to='payroll.salarystructure')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['driver', 'effective_from'], name='payroll_sal_driver__bcd9e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='salaryslip',
            constraint=models.UniqueConstraint(fields=('run', 'driver'), name='payroll_one_slip_per_driver_per_run'),
        ),
        migrations.AddIndex(
            model_name='salarycoveredtask',
            index=models.Index(fields=['driver', 'period_month'], name='payroll_sal_driver__d36cb3_idx'),
        ),
    ]
