# Generated by Django 5.2.16 on 2026-09-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='covered_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='covered_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
