# Generated by Django 5.2.16 on 2026-09-09 19:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_salaryslip_covered_from_salaryslip_covered_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='additions_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='SalaryAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_additions_created', to=settings.AUTH_USER_MODEL)),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addition_lines', to='payroll.salaryslip')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
