# Generated by Django 5.2.16 on 2026-07-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_ai_summary_lead_ai_summary_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('driver', 'Driver')], db_index=True, default='business', max_length=20),
        ),
    ]
