# Generated by Django 5.2.16 on 2026-07-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='wa_chat_override',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
