# Generated by Django 5.2.16 on 2026-08-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_wa_chat_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('business', 'Business'), ('driver', 'Driver')], default='business', help_text='Which board this column belongs to.', max_length=20)),
                ('key', models.SlugField(max_length=20)),
                ('label', models.CharField(max_length=60)),
                ('position', models.PositiveIntegerField(default=0, help_text='Left-to-right order on the board.')),
                ('is_closed', models.BooleanField(default=False, help_text='Terminal column — stamps closed_at and drops out of the Open total.')),
                ('hide_after_days', models.PositiveIntegerField(blank=True, help_text='Hide cards this many days after they closed. Blank = never hide.', null=True)),
                ('is_fallback', models.BooleanField(default=False, help_text='Where a driver with no matching rule lands. Exactly one per board.')),
                ('auto_rules', models.JSONField(blank=True, default=list, help_text='Rule keys from crm.stage_rules. Empty = manual drag-only column.')),
                ('write_back', models.CharField(blank=True, choices=[('', 'Nothing — board-only column'), ('pending', 'Driver: Pending Verification'), ('under_review', 'Driver: Under Review'), ('verified', 'Driver: Verified / Approved'), ('rejected', 'Driver: Rejected')], default='', max_length=20)),
                ('confirm_text', models.CharField(blank=True, default='', help_text='Asks staff to confirm before the drop, e.g. "approve this driver".', max_length=120)),
                ('needs_reason', models.BooleanField(default=False, help_text='Prompt for a reason before writing back (rejections).')),
                ('crm_status', models.CharField(blank=True, default='', help_text='Legacy PricingEnquiry.crm_status to mirror. Blank = do not mirror.', max_length=20)),
                ('dot_swatch', models.CharField(choices=[('grey', 'Grey'), ('slate', 'Slate'), ('blue', 'Blue'), ('teal', 'Teal'), ('green', 'Green'), ('forest', 'Forest'), ('violet', 'Violet'), ('amber', 'Amber'), ('red', 'Red')], default='grey', max_length=10)),
                ('is_system', models.BooleanField(default=False, help_text='Seeded column — editable but not deletable.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Stage (board column)',
                'verbose_name_plural': 'Lead Stages (board columns)',
                'ordering': ['category', 'position', 'pk'],
                'unique_together': {('category', 'key')},
            },
        ),
    ]
