# Generated by Django 5.2.16 on 2026-08-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_seed_lead_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='stage_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage_pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
