# Generated by Django 5.2.16 on 2026-08-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_lead_stage_pinned_lead_stage_pinned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='wa_session',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
