# Generated by Django 5.2.16 on 2026-08-07 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_lead_wa_session'),
        ('fleet', '0031_driverlocation_fixed_at_driverlocation_queued'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_leads', to='fleet.driver'),
        ),
    ]
