# Generated by Django 5.2.16 on 2026-08-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_lead_merged_at_lead_merged_by_lead_merged_into_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstage',
            name='outcome',
            field=models.CharField(blank=True, choices=[('', 'Neither — just a terminal column'), ('won', 'Won / approved'), ('lost', 'Lost / rejected')], default='', help_text='Counts this column as a win or a loss in reports, and fires the lead_won / lead_lost auto-flows. Only meaningful on a terminal column.', max_length=10),
        ),
    ]
