# Generated by Django 5.2.17 on 2026-09-29 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_driver_stage_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadWaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('session', models.CharField(blank=True, default='', help_text='WAHA session the chat was linked on (matters for lids).', max_length=64)),
                ('label', models.CharField(blank=True, default='', help_text='Who this number is, e.g. Owner, Office, Accounts.', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_wa_links', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_links', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lead WhatsApp number',
                'verbose_name_plural': 'Lead WhatsApp numbers',
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['identifier'], name='crm_leadwal_identif_4d6bd4_idx')],
                'constraints': [models.UniqueConstraint(fields=('lead', 'identifier'), name='crm_leadwalink_unique_per_lead')],
            },
        ),
    ]
