# Generated by Django 5.2.17 on 2026-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_move_wa_chat_override_to_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='merge_filled',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
