# Purpose: Add Lead.phone_2, a second mobile number for the same contact.
# Used by: CRM lead contact card, New Lead form, search, export, merge.

# Generated by Django 5.2.17 on 2026-10-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_lead_phone_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone_2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='2nd mobile'),
        ),
    ]
