# Generated by Django 5.2.17 on 2026-10-06 05:29

from django.db import migrations, models


def backfill_assigned_at(apps, schema_editor):
    """Owners that predate the field: the last logged assignment, else the card's
    creation (an owner set at creation or by the pricing sync logs no activity)."""
    Lead = apps.get_model('crm', 'Lead')
    LeadActivity = apps.get_model('crm', 'LeadActivity')
    for lead in Lead.objects.filter(assigned_to__isnull=False, assigned_at__isnull=True):
        last = (LeadActivity.objects
                .filter(lead_id=lead.pk, activity_type='assignment')
                .order_by('-created_at').values_list('created_at', flat=True).first())
        Lead.objects.filter(pk=lead.pk).update(assigned_at=last or lead.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_pricing_link_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_assigned_at, migrations.RunPython.noop),
    ]
