# Generated by Django 5.2.12 on 2026-05-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0023_businessapisettings_last_headers'),
        ('orders', '0047_alter_order_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waha_message_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('session', models.CharField(default='default', max_length=64)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=8)),
                ('from_number', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('to_number', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('body', models.TextField(blank=True, default='')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('location', 'Location'), ('sticker', 'Sticker'), ('contact', 'Contact'), ('unknown', 'Unknown')], default='text', max_length=16)),
                ('media_url', models.CharField(blank=True, default='', max_length=500)),
                ('media_mime', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('received', 'Received'), ('picked_up', 'Picked Up'), ('processed', 'Processed'), ('archived', 'Archived'), ('failed', 'Failed')], default='received', max_length=16)),
                ('error_kind', models.CharField(blank=True, default='', max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='business.business')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='orders.order')),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
                'ordering': ['-received_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'received_at'], name='whatsapp_wh_status_d0aaae_idx'), models.Index(fields=['from_number', 'received_at'], name='whatsapp_wh_from_nu_540119_idx'), models.Index(fields=['business', 'received_at'], name='whatsapp_wh_busines_56fd95_idx'), models.Index(fields=['direction', 'received_at'], name='whatsapp_wh_directi_34adb9_idx')],
            },
        ),
    ]
