# Generated by Django 5.2.12 on 2026-05-13 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_alter_order_customer_address'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='AddressVerificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, help_text='Digits-only phone (matches WhatsAppMessage.from_number)', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued for send'), ('sent', 'Sent — awaiting reply'), ('verified', 'Verified — coords applied'), ('manual_review', 'Manual review needed'), ('failed', 'Send failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('send_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('applied_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('applied_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_verification_jobs', to='orders.order')),
                ('received_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_jobs_received', to='whatsapp.whatsappmessage')),
                ('sent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_jobs_sent', to='whatsapp.whatsappmessage')),
            ],
            options={
                'verbose_name': 'Address Verification Job',
                'verbose_name_plural': 'Address Verification Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'status', 'sent_at'], name='whatsapp_ad_phone_25be9f_idx'), models.Index(fields=['status', 'created_at'], name='whatsapp_ad_status_39c9a2_idx')],
            },
        ),
    ]
