# Generated by Django 5.2.12 on 2026-05-13 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappmessage_latitude_whatsappmessage_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WahaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_messaging_enabled', models.BooleanField(default=True)),
                ('last_toggled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_toggled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waha_config_toggles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WAHA Config',
                'verbose_name_plural': 'WAHA Config',
            },
        ),
    ]
