# Generated by Django 5.2.12 on 2026-05-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_wahaconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='waha_message_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
