# Generated by Django 5.2.12 on 2026-05-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_alter_whatsappmessage_waha_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressverificationjob',
            name='driver_failure_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='addressverificationjob',
            name='kind',
            field=models.CharField(choices=[('auto_import', 'Auto-Import Verify'), ('delivery_failed', 'Delivery Recovery')], db_index=True, default='auto_import', help_text='Why this job exists (auto-import vs delivery-failed recovery)', max_length=20),
        ),
        migrations.AddField(
            model_name='addressverificationjob',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
