# Generated by Django 5.2.16 on 2026-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_addressverificationjob_driver_failure_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32, unique=True)),
                ('lid', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('saved_name', models.CharField(blank=True, default='', max_length=255)),
                ('push_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_business', models.BooleanField(default=False)),
                ('is_my_contact', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Contact',
                'verbose_name_plural': 'WhatsApp Contacts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
