# Generated by Django 5.2.16 on 2026-07-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_whatsappcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_file',
            field=models.FileField(blank=True, default='', upload_to='whatsapp/media/'),
        ),
    ]
