# Generated by Django 5.2.16 on 2026-07-18 12:17

import whatsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_whatsappmessage_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='media_file',
            field=models.FileField(blank=True, default='', storage=whatsapp.models._private_media_storage, upload_to='whatsapp/media/'),
        ),
    ]
