# Generated by Django 5.2.16 on 2026-08-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_businessapisettings_last_sync_at_and_more'),
        ('orders', '0060_alter_orderstatushistory_field_name'),
        ('whatsapp', '0008_alter_whatsappmessage_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='session',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='phone',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='session',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='waha_message_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['session', 'received_at'], name='whatsapp_wh_session_d87a93_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappcontact',
            constraint=models.UniqueConstraint(fields=('session', 'phone'), name='waha_contact_unique_per_session'),
        ),
        migrations.AddConstraint(
            model_name='whatsappmessage',
            constraint=models.UniqueConstraint(fields=('session', 'waha_message_id'), name='waha_msg_unique_per_session'),
        ),
    ]
