# Generated by Django 5.2.16 on 2026-08-07 18:39

from django.db import migrations, models

# Kept local rather than imported from whatsapp.waha_views: a migration has to
# keep behaving the same when that module later changes.
_SYSTEM_EVENT_TYPES = {
    'e2e_notification', 'notification_template', 'gp2', 'protocol', 'ciphertext',
}


def _raw_type(payload):
    if not isinstance(payload, dict):
        return ''
    inner = payload.get('payload')
    if isinstance(inner, dict):
        payload = inner
    data = payload.get('_data')
    raw = data.get('type') if isinstance(data, dict) else None
    return str(raw or payload.get('type') or '').lower()


def stamp_system_rows(apps, schema_editor):
    """Relabel already-stored protocol chatter as 'system'.

    These rows have a sender but no message, so the CRM inbox counts each one
    as an unknown sender needing triage. Relabelled rather than deleted — the
    raw payloads stay auditable.
    """
    Message = apps.get_model('whatsapp', 'WhatsAppMessage')
    ids = [
        m.id for m in Message.objects.filter(message_type='unknown').only('id', 'raw_payload')
        if _raw_type(m.raw_payload) in _SYSTEM_EVENT_TYPES
    ]
    for i in range(0, len(ids), 500):
        Message.objects.filter(id__in=ids[i:i + 500]).update(message_type='system')


def unstamp_system_rows(apps, schema_editor):
    Message = apps.get_model('whatsapp', 'WhatsAppMessage')
    Message.objects.filter(message_type='system').update(message_type='unknown')


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_whatsappcontact_session_alter_whatsappcontact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('location', 'Location'), ('sticker', 'Sticker'), ('contact', 'Contact'), ('system', 'System notification'), ('unknown', 'Unknown')], default='text', max_length=16),
        ),
        migrations.RunPython(stamp_system_rows, unstamp_system_rows),
    ]
