# Generated by Django 5.2.16 on 2026-08-08 16:32

import core.validators
import django.core.validators
import whatsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_whatsappmessage_system_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='media_file',
            field=models.FileField(blank=True, default='', storage=whatsapp.models._private_media_storage, upload_to='whatsapp/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif', 'pdf', 'mp3', 'ogg', 'opus', 'm4a', 'mp4', 'webm', '3gp']), core.validators.MaxFileSizeValidator(25)]),
        ),
    ]
