# Generated by Django 5.2.16 on 2026-08-08 18:21

import core.validators
import django.core.validators
import whatsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_alter_whatsappmessage_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='media_file',
            field=models.FileField(blank=True, default='', storage=whatsapp.models._private_media_storage, upload_to='whatsapp/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif', 'pdf', 'csv', 'xls', 'xlsx', 'mp3', 'ogg', 'oga', 'opus', 'm4a', 'aac', 'amr', 'wav', 'mp4', 'webm', '3gp', '3gpp', 'mov', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'vcf']), core.validators.MaxFileSizeValidator(25)]),
        ),
    ]
