# Generated by Django 5.2.17 on 2026-09-29 04:23

import core.validators
import django.core.validators
import whatsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0012_alter_whatsappmessage_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=64)),
                ('chat_id', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, storage=whatsapp.models._private_media_storage, upload_to='whatsapp/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif', 'pdf', 'csv', 'xls', 'xlsx', 'mp3', 'ogg', 'oga', 'opus', 'm4a', 'aac', 'amr', 'wav', 'mp4', 'webm', '3gp', '3gpp', 'mov', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'vcf']), core.validators.MaxFileSizeValidator(2)])),
                ('has_photo', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('session', 'chat_id')},
            },
        ),
    ]
