# Generated by Django 5.2.17 on 2026-10-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0014_restricted_chat_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='labels_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
