# Generated by Django 5.2.17 on 2026-10-03 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0015_whatsappcontact_labels_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_index=True, default='default', max_length=64)),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('sender', models.CharField(max_length=64)),
                ('emoji', models.CharField(blank=True, default='', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'message_id', 'sender'), name='wa_reaction_one_per_sender')],
            },
        ),
    ]
