# Generated by Django 5.2 on 2026-02-06 22:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0027_businessapisettings_tiktok_refresh_token_and_more'),
        ('delivery', '0007_alter_zonename_options_zonename_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('schema', models.JSONField(help_text='JSON Schema for tool input parameters')),
                ('is_enabled', models.BooleanField(default=True)),
                ('requires_auth', models.BooleanField(default=False, help_text='Requires authenticated user to execute')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('total_errors', models.PositiveIntegerField(default=0)),
                ('avg_latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('web', 'Web Chat'), ('whatsapp', 'WhatsApp'), ('api', 'REST API')], default='web', max_length=20)),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='Phone number for WhatsApp conversations', max_length=20)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Active context: current order, zone, etc.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('total_tokens_input', models.PositiveIntegerField(default=0)),
                ('total_tokens_output', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='business.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool Result')], max_length=20)),
                ('content', models.TextField()),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('tool_input', models.JSONField(blank=True, null=True)),
                ('tool_output', models.JSONField(blank=True, null=True)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_agent.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_call_type', models.CharField(choices=[('chat', 'Chat Completion'), ('tool_use', 'Tool Use'), ('embedding', 'Embedding')], max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.business')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='ai_agent.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.CharField(help_text='Text that maps to this zone (e.g., "الدفنة", "Defna", "Al Dafna")', max_length=200)),
                ('input_type', models.CharField(choices=[('area_name', 'Area Name'), ('street_ref', 'Street Reference'), ('landmark', 'Landmark'), ('typo', 'Common Typo'), ('alias', 'Alias')], default='area_name', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=10)),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score 0-1 for this mapping')),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='delivery.zonename')),
            ],
            options={
                'ordering': ['zone', 'text_input'],
            },
        ),
        migrations.CreateModel(
            name='CODRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('delivered_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('cod_refused_orders', models.PositiveIntegerField(default=0)),
                ('returned_orders', models.PositiveIntegerField(default=0)),
                ('total_cod_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('collected_cod_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('risk_score', models.FloatField(default=0.5, help_text='Composite risk score 0-1')),
                ('risk_factors', models.JSONField(default=list, help_text='List of contributing risk factors')),
                ('zone_risk_modifier', models.FloatField(default=0.0, help_text='Risk adjustment based on zone patterns')),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_zone', models.ForeignKey(blank=True, help_text='Most common delivery zone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.zonename')),
            ],
            options={
                'ordering': ['-risk_score'],
                'indexes': [models.Index(fields=['risk_score'], name='ai_agent_co_risk_sc_e1d086_idx'), models.Index(fields=['phone_number'], name='ai_agent_co_phone_n_b2ea60_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['channel', 'status'], name='ai_agent_co_channel_a8e39b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-last_activity'], name='ai_agent_co_user_id_1eb159_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business', '-last_activity'], name='ai_agent_co_busines_6f5572_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['phone_number'], name='ai_agent_co_phone_n_1c3fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_agent_co_convers_13d0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['user', '-created_at'], name='ai_agent_us_user_id_bed815_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['business', '-created_at'], name='ai_agent_us_busines_4d39e0_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['-created_at'], name='ai_agent_us_created_03a77f_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['api_call_type', '-created_at'], name='ai_agent_us_api_cal_b043db_idx'),
        ),
        migrations.AddIndex(
            model_name='zonetrainingdata',
            index=models.Index(fields=['text_input'], name='ai_agent_zo_text_in_90c91d_idx'),
        ),
        migrations.AddIndex(
            model_name='zonetrainingdata',
            index=models.Index(fields=['language', 'input_type'], name='ai_agent_zo_languag_748684_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zonetrainingdata',
            unique_together={('zone', 'text_input')},
        ),
    ]
