# Generated by Django 5.2.11 on 2026-03-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CODRiskScore',
        ),
    ]
