# Generated by Django 5.2.16 on 2026-07-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_delete_codriskscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='External session key from an integration (e.g. n8n session_id / WhatsApp number)', max_length=128),
        ),
    ]
