# Generated by Django 5.2 on 2026-01-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_enquiry', models.JSONField()),
                ('change_data_log', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('client_order_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('order_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('order_status', models.CharField(choices=[('to_review', 'Hold for Review'), ('ready_to_pickup', 'Ready to pickup'), ('publish', 'Publish for start delivery'), ('delivered', 'Delivered'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='to_review', max_length=100)),
                ('task_status', models.CharField(choices=[('new_order', 'New Order'), ('info_missing', 'Info Missing'), ('pending_for_confirm', 'Pending in confirm with Customer'), ('dl_task_listed', 'listed in Delivery Tasks')], db_index=True, default='new_order', max_length=100)),
                ('task_created', models.BooleanField(default=False)),
                ('cod_status_by_client', models.CharField(blank=True, choices=[('no_cod', 'No COD'), ('include', 'Include')], max_length=100, null=True)),
                ('cod_status_by_staff', models.CharField(blank=True, choices=[('not_collected', 'Not Collected'), ('partially_collected', 'Partially Collected'), ('fully_paid', 'Fully Collected'), ('cod_with_driver', 'COD Collected & with Driver'), ('cod_with_ezzy', 'COD handover to EZZY'), ('cod_settled_with_business', 'COD Settled with Business')], max_length=100, null=True)),
                ('cod_amount', models.IntegerField(default=0)),
                ('dl_included', models.BooleanField(default=True)),
                ('dl_amount', models.IntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('address_verified', 'Address Verified'), ('address_needs_update', 'Address Needs Update'), ('customer_contacted', 'Customer Contacted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('address_verified', models.BooleanField(default=False)),
                ('address_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('original_order_data', models.JSONField(blank=True, help_text='Original order data as proof', null=True)),
                ('stock_reserved', models.BooleanField(default=False, help_text='Whether stock has been reserved for this order')),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=100)),
                ('customer_whatsapp', models.CharField(blank=True, max_length=100)),
                ('customer_address', models.CharField(blank=True, max_length=100)),
                ('deadline_date', models.CharField(blank=True, max_length=100)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('dl_zone', models.PositiveIntegerField(blank=True)),
                ('dl_building', models.PositiveIntegerField(blank=True)),
                ('dl_street', models.PositiveIntegerField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the order was delivered', null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, help_text='When the order was marked as fulfilled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_addresses', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='business.business')),
                ('pickup_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.pickuplocation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='AddressVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('original_address', models.CharField(max_length=500)),
                ('verified_address', models.CharField(blank=True, max_length=500, null=True)),
                ('verification_result', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('needs_update', 'Needs Update'), ('pending', 'Pending'), ('address_verified', 'Address Verified by Customer'), ('verified', 'Verified by Staff')], default='pending', max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('customer_verified_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('zone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('street_number', models.PositiveIntegerField(blank=True, null=True)),
                ('building_number', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_verifications', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Address Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.ImageField(blank=True, default='business/orders/barcode.png', null=True, upload_to='business/orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_barcode', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_comments', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='orders.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order Verification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'order_status', '-created_at'], name='ord_biz_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'task_status'], name='ord_biz_task_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='ord_number_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_order_code'], name='ord_client_code_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='ord_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['verification_status'], name='ord_verification_idx'),
        ),
    ]
