# Generated by Django 5.1.2 on 2024-10-27 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '__first__'),
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_enquiry', models.JSONField()),
                ('change_data_log', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64, unique=True)),
                ('client_order_code', models.CharField(max_length=64, unique=True)),
                ('order_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('order_status', models.CharField(choices=[('publish', 'Publish for start delivery'), ('cancelled', 'Cancelled'), ('ready_to_pickup', 'Ready to pickup'), ('to_review', 'Hold for Review')], default='to_review', max_length=100)),
                ('task_status', models.CharField(choices=[('publish', 'Publish for start delivery'), ('cancelled', 'Cancelled'), ('ready_to_pickup', 'Ready to pickup'), ('to_review', 'Hold for Review')], default='new_order', max_length=100)),
                ('task_created', models.BooleanField(default=False)),
                ('cod_status_by_client', models.CharField(blank=True, choices=[('no_cod', 'No COD'), ('include', 'Include')], max_length=100, null=True)),
                ('cod_status_by_staff', models.CharField(blank=True, choices=[('cod_with_driver', 'COD Collected & with Driver'), ('fully_paid', 'Fully Collected'), ('cod_with_ezzy', 'COD handover to EZZY'), ('cod_sattled_with_business', 'COD Sattled with Business'), ('partially_collected', 'Partially Collected'), ('not_collected', 'Not Collected')], max_length=100, null=True)),
                ('cod_amount', models.IntegerField(default=0)),
                ('dl_included', models.BooleanField(default='True')),
                ('dl_amount', models.IntegerField(default=0)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=100)),
                ('customer_whatsapp', models.CharField(blank=True, max_length=100)),
                ('customer_address', models.CharField(blank=True, max_length=100)),
                ('deadline_date', models.CharField(blank=True, max_length=100)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('dl_zone', models.PositiveIntegerField(blank=True)),
                ('dl_building', models.PositiveIntegerField(blank=True)),
                ('dl_street', models.PositiveIntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='business.business')),
                ('pickup_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.pickuplocation')),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.ImageField(blank=True, default='business/orders/barcode.png', null=True, upload_to='business/orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_barcode', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_comments', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product01_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product02_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product03_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product04_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product05_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product06_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product07_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product08_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product09_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product10_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product11_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product12_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product13_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product14_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product15_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_list', to='orders.order')),
                ('product01_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product02_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product03_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product04_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product05_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product06_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product07_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product08_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product09_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product10_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product11_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product12_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product13_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product14_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('product15_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Order product lists',
            },
        ),
    ]
