# Generated by Django 5.1.2 on 2024-10-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_client',
            field=models.CharField(blank=True, choices=[('include', 'Include'), ('no_cod', 'No COD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('cod_with_ezzy', 'COD handover to EZZY'), ('cod_sattled_with_business', 'COD Sattled with Business'), ('fully_paid', 'Fully Collected'), ('not_collected', 'Not Collected'), ('cod_with_driver', 'COD Collected & with Driver'), ('partially_collected', 'Partially Collected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('publish', 'Publish for start delivery'), ('cancelled', 'Cancelled'), ('to_review', 'Hold for Review'), ('ready_to_pickup', 'Ready to pickup')], default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('publish', 'Publish for start delivery'), ('cancelled', 'Cancelled'), ('to_review', 'Hold for Review'), ('ready_to_pickup', 'Ready to pickup')], default='new_order', max_length=100),
        ),
    ]
