# Generated by Django 5.1.2 on 2024-10-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_cod_status_by_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_client',
            field=models.CharField(blank=True, choices=[('include', 'Include'), ('no_cod', 'No COD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('not_collected', 'Not Collected'), ('fully_paid', 'Fully Collected'), ('cod_with_ezzy', 'COD handover to EZZY'), ('partially_collected', 'Partially Collected'), ('cod_with_driver', 'COD Collected & with Driver'), ('cod_sattled_with_business', 'COD Sattled with Business')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('to_review', 'Hold for Review'), ('publish', 'Publish for start delivery'), ('ready_to_pickup', 'Ready to pickup')], default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('to_review', 'Hold for Review'), ('publish', 'Publish for start delivery'), ('ready_to_pickup', 'Ready to pickup')], default='new_order', max_length=100),
        ),
    ]
