# Generated by Django 5.2.9 on 2026-01-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_make_delivery_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('normal_delivery', 'Normal Delivery'), ('pick_and_drop', 'Pick and Drop')], default='normal_delivery', help_text='Order type: normal delivery or pick and drop', max_length=20),
        ),
    ]
