# Generated by Django 5.2.9 on 2026-01-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_order_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_delivery',
            field=models.BooleanField(default=False, help_text='Whether delivery is scheduled for a specific time'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Scheduled delivery time if scheduled_delivery is True', null=True),
        ),
    ]
