# Generated by Django 5.1.2 on 2024-10-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_cod_status_by_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('not_collected', 'Not Collected'), ('cod_with_driver', 'COD Collected & with Driver'), ('fully_paid', 'Fully Collected'), ('cod_sattled_with_business', 'COD Sattled with Business'), ('cod_with_ezzy', 'COD handover to EZZY'), ('partially_collected', 'Partially Collected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ready_to_pickup', 'Ready to pickup'), ('publish', 'Publish for start delivery'), ('to_review', 'Hold for Review'), ('cancelled', 'Cancelled')], default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('ready_to_pickup', 'Ready to pickup'), ('publish', 'Publish for start delivery'), ('to_review', 'Hold for Review'), ('cancelled', 'Cancelled')], default='new_order', max_length=100),
        ),
    ]
