# Generated by Django 5.2.11 on 2026-02-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_order_status_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('to_review', 'Hold for Review'), ('ready_to_pickup', 'Ready to pickup'), ('publish', 'Publish for start delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='to_review', max_length=100),
        ),
    ]
