# Generated by Django 5.1.2 on 2024-11-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_cod_status_by_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('partially_collected', 'Partially Collected'), ('cod_with_ezzy', 'COD handover to EZZY'), ('fully_paid', 'Fully Collected'), ('cod_sattled_with_business', 'COD Sattled with Business'), ('not_collected', 'Not Collected'), ('cod_with_driver', 'COD Collected & with Driver')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ready_to_pickup', 'Ready to pickup'), ('publish', 'Publish for start delivery'), ('cancelled', 'Cancelled'), ('to_review', 'Hold for Review')], default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('ready_to_pickup', 'Ready to pickup'), ('publish', 'Publish for start delivery'), ('cancelled', 'Cancelled'), ('to_review', 'Hold for Review')], default='new_order', max_length=100),
        ),
    ]
