# Generated by Django 5.2.11 on 2026-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_lat_lng_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coords_accuracy',
            field=models.CharField(blank=True, choices=[('exact', 'Exact (Building)'), ('street', 'Street Level')], max_length=10, null=True),
        ),
    ]
