# Generated by Django 5.2.11 on 2026-02-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_coords_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coords_accuracy',
            field=models.CharField(blank=True, choices=[('exact', 'Exact (Building)'), ('street', 'Street Level'), ('landmark', 'Landmark/Area'), ('zone_center', 'Zone Center'), ('ai_estimate', 'AI Estimate')], max_length=15, null=True),
        ),
    ]
