# Generated by Django 4.1.13 on 2024-12-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_cod_status_by_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('not_collected', 'Not Collected'), ('cod_with_driver', 'COD Collected & with Driver'), ('cod_sattled_with_business', 'COD Sattled with Business'), ('cod_with_ezzy', 'COD handover to EZZY'), ('partially_collected', 'Partially Collected'), ('fully_paid', 'Fully Collected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('publish', 'Publish for start delivery'), ('to_review', 'Hold for Review'), ('cancelled', 'Cancelled'), ('ready_to_pickup', 'Ready to pickup')], default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('publish', 'Publish for start delivery'), ('to_review', 'Hold for Review'), ('cancelled', 'Cancelled'), ('ready_to_pickup', 'Ready to pickup')], default='new_order', max_length=100),
        ),
    ]
