# Generated by Django 5.1.7 on 2025-03-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_cod_status_by_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_client',
            field=models.CharField(blank=True, choices=[('no_cod', 'No COD'), ('include', 'Include')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('cod_sattled_with_business', 'COD Sattled with Business'), ('cod_with_driver', 'COD Collected & with Driver'), ('fully_paid', 'Fully Collected'), ('partially_collected', 'Partially Collected'), ('cod_with_ezzy', 'COD handover to EZZY'), ('not_collected', 'Not Collected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('to_review', 'Hold for Review'), ('cancelled', 'Cancelled'), ('ready_to_pickup', 'Ready to pickup'), ('publish', 'Publish for start delivery')], default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('to_review', 'Hold for Review'), ('cancelled', 'Cancelled'), ('ready_to_pickup', 'Ready to pickup'), ('publish', 'Publish for start delivery')], default='new_order', max_length=100),
        ),
    ]
