# Generated by Django 5.2.11 on 2026-02-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_expand_coords_accuracy_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='field_name',
            field=models.CharField(choices=[('order_status', 'Order Status'), ('task_status', 'Task Status'), ('verification_status', 'Verification Status'), ('cod_status_by_staff', 'COD Status'), ('dl_task_status', 'Delivery Task Status'), ('dl_task_status_dms', 'DMS Status'), ('dl_task_publish', 'Published to Fleet')], max_length=50),
        ),
    ]
