# Generated by Django 5.1.7 on 2025-05-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_cod_status_by_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('not_collected', 'Not Collected'), ('cod_with_ezzy', 'COD handover to EZZY'), ('cod_with_driver', 'COD Collected & with Driver'), ('fully_paid', 'Fully Collected'), ('cod_sattled_with_business', 'COD Sattled with Business'), ('partially_collected', 'Partially Collected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('publish', 'Publish for start delivery'), ('to_review', 'Hold for Review'), ('ready_to_pickup', 'Ready to pickup')], default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('info_missing', 'Info Missing'), ('pending_for_confirm', 'Pending in confirm with Customer'), ('new_order', 'New Order'), ('dl_task_listed', 'listed in Delivery Tasks')], default='new_order', max_length=100),
        ),
    ]
