# Generated by Django 5.2.11 on 2026-02-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderstatushistory_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qnas_status',
            field=models.CharField(blank=True, choices=[('not_checked', 'Not Checked'), ('verified', 'Verified'), ('not_found', 'Not Found'), ('error', 'Error')], default='not_checked', max_length=15),
        ),
    ]
