# Generated by Django 5.1.7 on 2025-05-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_cod_status_by_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_client',
            field=models.CharField(blank=True, choices=[('include', 'Include'), ('no_cod', 'No COD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('fully_paid', 'Fully Collected'), ('not_collected', 'Not Collected'), ('cod_with_ezzy', 'COD handover to EZZY'), ('cod_with_driver', 'COD Collected & with Driver'), ('cod_sattled_with_business', 'COD Sattled with Business'), ('partially_collected', 'Partially Collected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('publish', 'Publish for start delivery'), ('ready_to_pickup', 'Ready to pickup'), ('to_review', 'Hold for Review')], default='to_review', max_length=100),
        ),
    ]
