# Generated by Django 5.2.11 on 2026-03-03 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_hub_delivery_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the cancellation', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('client_request', 'Client Request'), ('address_issue', 'Address Issue'), ('customer_unreachable', 'Customer Unreachable'), ('duplicate_order', 'Duplicate Order'), ('out_of_stock', 'Out of Stock'), ('driver_issue', 'Driver Issue'), ('other', 'Other')], help_text='Why the order was cancelled', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who cancelled the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='order_source_text',
            field=models.TextField(blank=True, help_text='Raw pasted order text (WhatsApp/chat message) kept for reference', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('to_review', 'Hold for Review'), ('ready_to_pickup', 'Ready to pickup'), ('publish', 'Published'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='field_name',
            field=models.CharField(choices=[('order_status', 'Order Status'), ('task_status', 'Task Status'), ('verification_status', 'Verification Status'), ('cod_status_by_staff', 'COD Status'), ('dl_task_status', 'Delivery Task Status'), ('dl_task_publish', 'Published to Fleet')], max_length=50),
        ),
    ]
