# Generated by Django 5.1.7 on 2025-05-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_cod_status_by_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('cod_with_ezzy', 'COD handover to EZZY'), ('not_collected', 'Not Collected'), ('cod_with_driver', 'COD Collected & with Driver'), ('cod_sattled_with_business', 'COD Sattled with Business'), ('partially_collected', 'Partially Collected'), ('fully_paid', 'Fully Collected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('to_review', 'Hold for Review'), ('ready_to_pickup', 'Ready to pickup'), ('cancelled', 'Cancelled'), ('publish', 'Publish for start delivery')], default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('dl_task_listed', 'listed in Delivery Tasks'), ('new_order', 'New Order'), ('info_missing', 'Info Missing'), ('pending_for_confirm', 'Pending in confirm with Customer')], default='new_order', max_length=100),
        ),
    ]
