# Generated by Django 5.2.11 on 2026-03-08 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_add_scheduled_date_to_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_transferred',
            field=models.BooleanField(db_index=True, default=False, help_text='Order has been transferred/accepted into main workflow by staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='transferred_at',
            field=models.DateTimeField(blank=True, help_text='When the order was transferred', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transferred_by',
            field=models.ForeignKey(blank=True, help_text='Staff who transferred this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
