# Generated by Django 5.1.7 on 2025-09-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_cod_status_by_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_client',
            field=models.CharField(blank=True, choices=[('no_cod', 'No COD'), ('include', 'Include')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('fully_paid', 'Fully Collected'), ('cod_with_ezzy', 'COD handover to EZZY'), ('cod_with_driver', 'COD Collected & with Driver'), ('not_collected', 'Not Collected'), ('cod_sattled_with_business', 'COD Sattled with Business'), ('partially_collected', 'Partially Collected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ready_to_pickup', 'Ready to pickup'), ('publish', 'Publish for start delivery'), ('to_review', 'Hold for Review'), ('cancelled', 'Cancelled')], default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('pending_for_confirm', 'Pending in confirm with Customer'), ('new_order', 'New Order'), ('info_missing', 'Info Missing'), ('dl_task_listed', 'listed in Delivery Tasks')], default='new_order', max_length=100),
        ),
    ]
