# Generated by Django 5.2.11 on 2026-03-09 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_businessapisettings_google_sheet_url_and_more'),
        ('orders', '0017_order_is_transferred_order_transferred_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneDriveSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Friendly name for this source', max_length=200)),
                ('share_link', models.URLField(help_text='OneDrive shared link to Excel file', max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('last_import_at', models.DateTimeField(blank=True, null=True)),
                ('last_import_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onedrive_sources', to='business.business')),
                ('last_import_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'OneDrive Sources',
                'ordering': ['-created_at'],
            },
        ),
    ]
