# Generated by Django 5.2.11 on 2026-03-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_onedrivesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedrivesource',
            name='last_sheet_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='onedrivesource',
            name='last_start_row',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
