# Generated by Django 5.1.7 on 2025-11-07 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_cod_status_by_client_and_more'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproductlist',
            options={'verbose_name_plural': 'Order product lists (DEPRECATED)'},
        ),
        migrations.AddField(
            model_name='order',
            name='address_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='address_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='original_order_data',
            field=models.JSONField(blank=True, help_text='Original order data as proof', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('address_verified', 'Address Verified'), ('address_needs_update', 'Address Needs Update'), ('customer_contacted', 'Customer Contacted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_client',
            field=models.CharField(blank=True, choices=[('include', 'Include'), ('no_cod', 'No COD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('not_collected', 'Not Collected'), ('cod_with_ezzy', 'COD handover to EZZY'), ('partially_collected', 'Partially Collected'), ('cod_with_driver', 'COD Collected & with Driver'), ('fully_paid', 'Fully Collected'), ('cod_sattled_with_business', 'COD Sattled with Business')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ready_to_pickup', 'Ready to pickup'), ('to_review', 'Hold for Review'), ('cancelled', 'Cancelled'), ('publish', 'Publish for start delivery')], default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('pending_for_confirm', 'Pending in confirm with Customer'), ('info_missing', 'Info Missing'), ('new_order', 'New Order'), ('dl_task_listed', 'listed in Delivery Tasks')], default='new_order', max_length=100),
        ),
        migrations.CreateModel(
            name='AddressVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_address', models.CharField(max_length=500)),
                ('verified_address', models.CharField(blank=True, max_length=500, null=True)),
                ('verification_result', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('needs_update', 'Needs Update'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True)),
                ('zone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('street_number', models.PositiveIntegerField(blank=True, null=True)),
                ('building_number', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_verifications', to='orders.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Address Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='orders.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order Verification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
