# Generated by Django 5.2.11 on 2026-03-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_add_last_sheet_to_onedrivesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedrivesource',
            name='last_column_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='onedrivesource',
            name='last_import_max_row',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
