# Generated by Django 5.1.7 on 2025-11-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orderproductlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('partially_collected', 'Partially Collected'), ('not_collected', 'Not Collected'), ('cod_with_ezzy', 'COD handover to EZZY'), ('cod_with_driver', 'COD Collected & with Driver'), ('cod_sattled_with_business', 'COD Sattled with Business'), ('fully_paid', 'Fully Collected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('to_review', 'Hold for Review'), ('publish', 'Publish for start delivery'), ('ready_to_pickup', 'Ready to pickup')], default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('new_order', 'New Order'), ('dl_task_listed', 'listed in Delivery Tasks'), ('pending_for_confirm', 'Pending in confirm with Customer'), ('info_missing', 'Info Missing')], default='new_order', max_length=100),
        ),
    ]
