# Generated by Django 5.2.11 on 2026-03-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_add_mapping_and_maxrow_to_onedrivesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedrivesource',
            name='last_imported_rows',
            field=models.JSONField(blank=True, default=list, help_text='List of row numbers imported in last batch'),
        ),
    ]
