# Generated by Django 5.1.7 on 2025-11-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_cod_status_by_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_client',
            field=models.CharField(blank=True, choices=[('no_cod', 'No COD'), ('include', 'Include')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('cod_sattled_with_business', 'COD Sattled with Business'), ('cod_with_driver', 'COD Collected & with Driver'), ('not_collected', 'Not Collected'), ('cod_with_ezzy', 'COD handover to EZZY'), ('partially_collected', 'Partially Collected'), ('fully_paid', 'Fully Collected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('ready_to_pickup', 'Ready to pickup'), ('to_review', 'Hold for Review'), ('publish', 'Publish for start delivery')], default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('info_missing', 'Info Missing'), ('pending_for_confirm', 'Pending in confirm with Customer'), ('dl_task_listed', 'listed in Delivery Tasks'), ('new_order', 'New Order')], default='new_order', max_length=100),
        ),
    ]
