# Generated by Django 5.2.11 on 2026-03-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_add_imported_rows_to_onedrivesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_description',
            field=models.CharField(blank=True, default='', help_text="Short product summary e.g. 'Perfumes', 'Food items'", max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity for the product description'),
        ),
    ]
