# Generated by Django 5.2.11 on 2026-03-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_rename_product_description_to_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package_description',
            field=models.CharField(blank=True, default='', help_text="Seller's package description e.g. 'Perfumes', 'Food items'", max_length=255),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='field_name',
            field=models.CharField(choices=[('order_status', 'Order Status'), ('task_status', 'Task Status'), ('verification_status', 'Verification Status'), ('cod_status_by_staff', 'COD Status'), ('dl_task_status', 'Delivery Task Status'), ('dl_task_publish', 'Published to Fleet'), ('order_edited', 'Order Edited'), ('task_edited', 'Task Edited'), ('item_deleted', 'Item Deleted')], max_length=50),
        ),
    ]
