# Generated by Django 5.1.7 on 2025-11-16 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_businessprofile_business_linkedin_and_more'),
        ('orders', '0023_addressverification_customer_verified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_order_code',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('not_collected', 'Not Collected'), ('cod_with_driver', 'COD Collected & with Driver'), ('fully_paid', 'Fully Collected'), ('cod_sattled_with_business', 'COD Sattled with Business'), ('cod_with_ezzy', 'COD handover to EZZY'), ('partially_collected', 'Partially Collected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ready_to_pickup', 'Ready to pickup'), ('to_review', 'Hold for Review'), ('publish', 'Publish for start delivery'), ('cancelled', 'Cancelled')], db_index=True, default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('pending_for_confirm', 'Pending in confirm with Customer'), ('dl_task_listed', 'listed in Delivery Tasks'), ('info_missing', 'Info Missing'), ('new_order', 'New Order')], db_index=True, default='new_order', max_length=100),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'order_status', '-created_at'], name='ord_biz_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'task_status'], name='ord_biz_task_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='ord_number_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_order_code'], name='ord_client_code_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='ord_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['verification_status'], name='ord_verification_idx'),
        ),
    ]
