# Generated by Django 5.2.11 on 2026-03-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_add_edit_choices_to_status_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_quantity',
            new_name='package_qty',
        ),
    ]
