# Generated by Django 5.1.7 on 2025-11-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_client_order_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_client',
            field=models.CharField(blank=True, choices=[('include', 'Include'), ('no_cod', 'No COD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('partially_collected', 'Partially Collected'), ('not_collected', 'Not Collected'), ('fully_paid', 'Fully Collected'), ('cod_sattled_with_business', 'COD Sattled with Business'), ('cod_with_driver', 'COD Collected & with Driver'), ('cod_with_ezzy', 'COD handover to EZZY')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dl_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('pending_for_confirm', 'Pending in confirm with Customer'), ('new_order', 'New Order'), ('info_missing', 'Info Missing'), ('dl_task_listed', 'listed in Delivery Tasks')], db_index=True, default='new_order', max_length=100),
        ),
    ]
