# Generated by Django 5.2.11 on 2026-03-11 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_add_column_mapping_to_api_settings'),
        ('orders', '0025_rename_total_quantity_to_package_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package_qty',
            field=models.PositiveIntegerField(default=0, help_text='Package quantity for the product description'),
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('csv_upload', 'CSV / Excel Upload'), ('onedrive', 'OneDrive'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('google_sheet', 'Google Sheet')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('started', 'Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], default='started', max_length=30)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('orders_created', models.PositiveIntegerField(default=0)),
                ('orders_skipped', models.PositiveIntegerField(default=0)),
                ('orders_failed', models.PositiveIntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=list)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('source_meta', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='business.business')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('onedrive_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to='orders.onedrivesource')),
                ('orders', models.ManyToManyField(blank=True, related_name='import_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['business', 'source', '-started_at'], name='implog_biz_src_dt_idx')],
            },
        ),
    ]
