# Generated by Django 5.1.7 on 2025-11-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_cod_status_by_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_client',
            field=models.CharField(blank=True, choices=[('no_cod', 'No COD'), ('include', 'Include')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('not_collected', 'Not Collected'), ('partially_collected', 'Partially Collected'), ('fully_paid', 'Fully Collected'), ('cod_with_driver', 'COD Collected & with Driver'), ('cod_with_ezzy', 'COD handover to EZZY'), ('cod_sattled_with_business', 'COD Sattled with Business')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('to_review', 'Hold for Review'), ('ready_to_pickup', 'Ready to pickup'), ('publish', 'Publish for start delivery'), ('cancelled', 'Cancelled')], db_index=True, default='to_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='task_status',
            field=models.CharField(choices=[('new_order', 'New Order'), ('info_missing', 'Info Missing'), ('pending_for_confirm', 'Pending in confirm with Customer'), ('dl_task_listed', 'listed in Delivery Tasks')], db_index=True, default='new_order', max_length=100),
        ),
    ]
