# Generated by Django 5.2.8 on 2025-11-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_order_cod_status_by_client_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProductList',
        ),
    ]
