# Generated by Django 5.2.11 on 2026-03-11 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_add_column_mapping_to_api_settings'),
        ('orders', '0026_alter_order_package_qty_importlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=200)),
                ('row_num', models.PositiveIntegerField(help_text='Excel row number (1-indexed, includes header)')),
                ('client_order_code', models.CharField(blank=True, default='', max_length=64)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=100)),
                ('customer_address', models.CharField(blank=True, default='', max_length=500)),
                ('dl_zone', models.CharField(blank=True, default='', max_length=20)),
                ('dl_street', models.CharField(blank=True, default='', max_length=20)),
                ('dl_building', models.CharField(blank=True, default='', max_length=20)),
                ('cod_amount', models.CharField(blank=True, default='', max_length=30)),
                ('order_date', models.CharField(blank=True, default='', max_length=50)),
                ('package_desc', models.CharField(blank=True, default='', max_length=500)),
                ('raw_row', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('imported', 'Imported'), ('skipped', 'Skipped')], db_index=True, default='new', max_length=10)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_orders', to='business.business')),
                ('imported_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_temp_order', to='orders.order')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_orders', to='orders.onedrivesource')),
            ],
            options={
                'verbose_name': 'Temp Order',
                'verbose_name_plural': 'Temp Orders',
                'ordering': ['-row_num'],
                'unique_together': {('source', 'row_num')},
            },
        ),
    ]
