# Generated by Django 5.2.8 on 2025-12-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_delete_orderproductlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_reserved',
            field=models.BooleanField(default=False, help_text='Whether stock has been reserved for this order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_staff',
            field=models.CharField(blank=True, choices=[('not_collected', 'Not Collected'), ('partially_collected', 'Partially Collected'), ('fully_paid', 'Fully Collected'), ('cod_with_driver', 'COD Collected & with Driver'), ('cod_with_ezzy', 'COD handover to EZZY'), ('cod_settled_with_business', 'COD Settled with Business')], max_length=100, null=True),
        ),
    ]
