# Generated by Django 5.2.11 on 2026-03-11 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_add_column_mapping_to_api_settings'),
        ('orders', '0027_temporder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temporder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='temporder',
            name='api_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_orders', to='business.businessapisettings'),
        ),
        migrations.AddField(
            model_name='temporder',
            name='onedrive_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_orders', to='orders.onedrivesource'),
        ),
        migrations.AddField(
            model_name='temporder',
            name='platform_id',
            field=models.CharField(blank=True, default='', help_text='Platform order ID for API sources', max_length=100),
        ),
        migrations.AddField(
            model_name='temporder',
            name='source_type',
            field=models.CharField(choices=[('onedrive', 'OneDrive'), ('google_sheet', 'Google Sheet'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce')], db_index=True, default='onedrive', max_length=20),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='client_order_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='row_num',
            field=models.PositiveIntegerField(default=0, help_text='Row number (1-indexed) or 0 for API orders'),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='sheet_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='temporder',
            name='source',
        ),
    ]
