# Generated by Django 5.2 on 2025-12-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_stock_reserved_alter_order_cod_status_by_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When the order was delivered', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, help_text='When the order was marked as fulfilled', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('to_review', 'Hold for Review'), ('ready_to_pickup', 'Ready to pickup'), ('publish', 'Publish for start delivery'), ('delivered', 'Delivered'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='to_review', max_length=100),
        ),
    ]
