# Generated by Django 5.2.11 on 2026-03-12 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_add_column_mapping_to_api_settings'),
        ('orders', '0028_alter_temporder_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporder',
            name='source_type',
            field=models.CharField(choices=[('onedrive', 'OneDrive'), ('google_sheet', 'Google Sheet'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('public_link', 'Public Link')], db_index=True, default='onedrive', max_length=20),
        ),
        migrations.CreateModel(
            name='PublicLinkSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Friendly name for this source', max_length=200)),
                ('url', models.URLField(help_text='Public URL to HTML page with order table', max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_count', models.PositiveIntegerField(default=0)),
                ('last_column_mapping', models.JSONField(blank=True, default=dict, help_text='Auto-detected column mapping: {col_idx: db_field}')),
                ('last_headers', models.JSONField(blank=True, default=list, help_text='Column headers from last sync')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_link_sources', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Public Link Sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='temporder',
            name='public_link_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_orders', to='orders.publiclinksource'),
        ),
    ]
