# Generated by Django 5.2 on 2026-02-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_order_dl_building_alter_order_dl_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('normal_delivery', 'Normal Delivery'), ('pick_and_drop', 'Pick and Drop')], default='normal_delivery', help_text='Order type: normal delivery or pick and drop', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_delivery',
            field=models.BooleanField(default=False, help_text='Whether delivery is scheduled for a specific time'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Scheduled delivery time if scheduled_delivery is True', null=True),
        ),
    ]
