# Generated by Django 5.2.11 on 2026-03-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_add_verified_by_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coords_accuracy',
            field=models.CharField(blank=True, choices=[('by_customer', 'By Customer'), ('by_driver', 'By Driver'), ('exact', 'Exact (Building)'), ('street', 'Street Level'), ('landmark', 'Landmark/Area'), ('zone_center', 'Zone Center'), ('ai_estimate', 'AI Estimate')], max_length=15, null=True),
        ),
    ]
