# Generated by Django 5.2 on 2026-02-11 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_order_type_order_scheduled_delivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('order_status', 'Order Status'), ('task_status', 'Task Status'), ('verification_status', 'Verification Status'), ('cod_status_by_staff', 'COD Status'), ('dl_task_status', 'Delivery Task Status'), ('dl_task_status_dms', 'DMS Status')], max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(max_length=100)),
                ('old_display', models.CharField(blank=True, max_length=100, null=True)),
                ('new_display', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Order Status History',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='ord_status_hist_idx')],
            },
        ),
    ]
