# Generated by Django 5.2.11 on 2026-03-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_add_by_driver_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='source',
            field=models.CharField(choices=[('csv_upload', 'CSV / Excel Upload'), ('onedrive', 'OneDrive'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('google_sheet', 'Google Sheet'), ('temp_order', 'Temp Order')], db_index=True, max_length=30),
        ),
    ]
