# Generated by Django 5.2 on 2026-02-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_orderstatushistory_orderverificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coords_accuracy',
            field=models.CharField(blank=True, choices=[('exact', 'Exact (Building)'), ('street', 'Street Level'), ('landmark', 'Landmark/Area'), ('zone_center', 'Zone Center'), ('ai_estimate', 'AI Estimate')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_client',
            field=models.CharField(blank=True, choices=[('no_cod', 'No COD'), ('pending', 'COD Pending'), ('collected', 'Collected by Driver'), ('received_by_company', 'Received by Company'), ('invoiced', 'Invoiced'), ('settled', 'Settled with Business'), ('online_paid', 'Paid Online to Seller'), ('disputed', 'Disputed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('to_review', 'Hold for Review'), ('ready_to_pickup', 'Ready to pickup'), ('publish', 'Publish to DL Task'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='to_review', max_length=100),
        ),
    ]
