# Generated by Django 5.2.11 on 2026-03-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_add_temp_order_source_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporder',
            name='cod_amount',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='dl_building',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='dl_street',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='dl_zone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
