# Generated by Django 5.2.11 on 2026-03-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_widen_temporder_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporder',
            name='source_type',
            field=models.CharField(choices=[('onedrive', 'OneDrive'), ('google_sheet', 'Google Sheet'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('public_link', 'Public Link'), ('webhook', 'Webhook')], db_index=True, default='onedrive', max_length=20),
        ),
    ]
