# Generated by Django 5.2.11 on 2026-03-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_webhook_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_client',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial'), ('pending', 'COD Pending'), ('collected', 'Collected by Driver'), ('received_by_company', 'Received by Company'), ('invoiced', 'Invoiced'), ('settled', 'Settled with Business'), ('online_paid', 'Paid Online to Seller'), ('disputed', 'Disputed')], max_length=100, null=True),
        ),
    ]
