# Generated by Django 5.2.11 on 2026-03-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_update_cod_status_choices_add_paid_unpaid_partial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_status_by_client',
            field=models.CharField(blank=True, choices=[('online_paid', 'Online Paid'), ('unpaid', 'Unpaid'), ('partial_paid', 'Partial Paid'), ('pending', 'COD Pending'), ('collected', 'Collected by Driver'), ('received_by_company', 'Received by Company'), ('invoiced', 'Invoiced'), ('settled', 'Settled with Business'), ('disputed', 'Disputed')], max_length=100, null=True),
        ),
    ]
