# Generated by Django 5.2 on 2026-02-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_add_qnas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='field_name',
            field=models.CharField(choices=[('order_status', 'Order Status'), ('task_status', 'Task Status'), ('verification_status', 'Verification Status'), ('cod_status_by_staff', 'COD Status'), ('dl_task_status', 'Delivery Task Status'), ('dl_task_publish', 'Published to Fleet')], max_length=50),
        ),
    ]
