# Generated by Django 5.2.11 on 2026-03-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_rename_cod_paid_to_online_paid_partial_to_partial_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporder',
            name='financial_status',
            field=models.CharField(blank=True, default='', help_text='Payment status from source platform (e.g. Shopify: paid/pending/refunded)', max_length=50),
        ),
    ]
