# Generated by Django 5.2.11 on 2026-03-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_add_financial_status_to_temporder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('onedrive', 'OneDrive'), ('google_sheet', 'Google Sheet'), ('public_link', 'Public Link'), ('csv', 'CSV Upload'), ('api', 'API'), ('other', 'Other')], default='', help_text='Source platform this order came from', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_id',
            field=models.CharField(blank=True, default='', help_text="Original order ID on the source platform (e.g. Shopify order name '#1042')", max_length=128),
        ),
    ]
