# Generated by Django 5.2 on 2026-02-28 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_alter_orderstatushistory_field_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the cancellation', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('client_request', 'Client Request'), ('address_issue', 'Address Issue'), ('customer_unreachable', 'Customer Unreachable'), ('duplicate_order', 'Duplicate Order'), ('out_of_stock', 'Out of Stock'), ('driver_issue', 'Driver Issue'), ('other', 'Other')], help_text='Why the order was cancelled', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who cancelled the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
