# Generated by Django 5.2 on 2026-02-28 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_hub_delivery_fields'),
        ('orders', '0038_order_cancellation_notes_order_cancellation_reason_and_more'),
        ('warehouse', '0005_add_dimensions_to_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hub_pickup_batch',
            field=models.ForeignKey(blank=True, help_text='Pickup batch this order belongs to (assigned by staff).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.hubpickupbatch'),
        ),
        migrations.AddField(
            model_name='order',
            name='hub_warehouse',
            field=models.ForeignKey(blank=True, help_text='Hub warehouse used as handoff point for hub deliveries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_orders', to='warehouse.warehouselocation'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_hub_delivery',
            field=models.BooleanField(default=False, help_text='When True, order goes through hub warehouse before last-mile delivery.'),
        ),
    ]
