# Generated by Django 5.2.11 on 2026-03-24 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_business_import_mapping'),
        ('delivery', '0026_add_by_driver_accuracy'),
        ('orders', '0038_add_platform_fields_to_order'),
        ('warehouse', '0005_alter_stockreservation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_order_code',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('business', 'client_order_code'), name='ord_unique_client_code_per_business'),
        ),
    ]
