# Generated by Django 5.2.11 on 2026-03-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_alter_order_client_order_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedrivesource',
            name='is_default_mapping',
            field=models.BooleanField(default=False, help_text='Default source for mapping manager — headers loaded on page open'),
        ),
    ]
