# Generated by Django 5.2 on 2026-02-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_order_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_source_text',
            field=models.TextField(blank=True, help_text='Raw pasted order text (WhatsApp/chat message) kept for reference', null=True),
        ),
    ]
