# Generated by Django 5.2.11 on 2026-03-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_add_is_default_mapping_to_onedrivesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedrivesource',
            name='last_headers',
            field=models.JSONField(blank=True, default=list, help_text='Column headers from last sync/fetch'),
        ),
    ]
