# Generated by Django 5.2.11 on 2026-04-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_add_onedrive_last_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='dl_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
