# Generated by Django 5.2.11 on 2026-04-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_alter_order_cod_amount_alter_order_dl_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('partial', 'Partially Returned')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_delivered',
            field=models.PositiveIntegerField(default=0, help_text='Quantity actually delivered to customer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_returned',
            field=models.PositiveIntegerField(default=0, help_text='Quantity returned by customer'),
        ),
    ]
