# Generated by Django 5.2.11 on 2026-04-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_add_orderitem_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preferred_time_slot',
            field=models.CharField(blank=True, choices=[('', 'No Preference'), ('morning', 'Morning (8 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 4 PM)'), ('evening', 'Evening (4 PM - 8 PM)'), ('night', 'Night (8 PM - 10 PM)')], default='', help_text="Customer's preferred delivery time window", max_length=20),
        ),
    ]
