# Generated by Django 5.2.11 on 2026-04-02 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_add_product_combo'),
        ('orders', '0044_add_preferred_time_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('reason', models.CharField(choices=[('wrong_item', 'Wrong Item Received'), ('damaged', 'Item Damaged'), ('not_as_described', 'Not As Described'), ('customer_changed_mind', 'Customer Changed Mind'), ('duplicate_order', 'Duplicate Order'), ('other', 'Other')], max_length=30)),
                ('reason_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('received', 'Received'), ('refunded', 'Refunded'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20)),
                ('cod_reversal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cod_reversal_processed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='business.business')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_returnrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.PositiveIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='orders.returnrequest')),
            ],
            options={
                'db_table': 'orders_returnitem',
            },
        ),
    ]
