# Generated by Django 5.2.11 on 2026-04-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_returnrequest_returnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_amount_locked',
            field=models.BooleanField(default=False, help_text='True after driver collects COD — prevents amount edits'),
        ),
    ]
