# Generated by Django 5.2.11 on 2026-04-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_order_cod_amount_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
