# Generated by Django 5.2.12 on 2026-05-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_alter_order_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporder',
            name='change_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
