# Generated by Django 5.2.12 on 2026-06-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_temporder_change_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_speed',
            field=models.CharField(choices=[('standard', 'Standard (48hr)'), ('same_day', 'Same Day')], db_index=True, default='standard', help_text='Delivery speed tier: same_day or standard (48hr)', max_length=20),
        ),
    ]
