# Generated by Django 5.2.12 on 2026-06-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_add_delivery_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_speed',
            field=models.CharField(choices=[('standard', 'Standard (48hr)'), ('same_day', 'Same Day'), ('express', 'Express (2-4hr)')], db_index=True, default='standard', help_text='Delivery speed tier: same_day or standard (48hr)', max_length=20),
        ),
    ]
