# Generated by Django 5.2.16 on 2026-07-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_alter_order_delivery_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coords_accuracy',
            field=models.CharField(blank=True, choices=[('by_customer', 'By Customer'), ('by_staff', 'By Staff'), ('by_driver', 'By Driver'), ('exact', 'Exact (Building)'), ('street', 'Street Level'), ('landmark', 'Landmark/Area'), ('zone_center', 'Zone Center'), ('ai_estimate', 'AI Estimate')], max_length=15, null=True),
        ),
    ]
