# Generated by Django 5.2.16 on 2026-07-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_alter_order_coords_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='field_name',
            field=models.CharField(choices=[('order_status', 'Order Status'), ('task_status', 'Task Status'), ('verification_status', 'Verification Status'), ('cod_status_by_staff', 'COD Status'), ('dl_task_status', 'Delivery Task Status'), ('dl_task_publish', 'Published to Fleet'), ('order_edited', 'Order Edited'), ('task_edited', 'Task Edited'), ('item_deleted', 'Item Deleted'), ('cod_correction', 'COD Correction')], max_length=50),
        ),
    ]
