# Generated by Django 5.2.16 on 2026-07-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_alter_orderstatushistory_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='route_distance_exact',
            field=models.BooleanField(default=False, help_text='False when either end fell back to its zone centre — the distance is an estimate, not a measurement'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Straight-line distance from pickup to drop, in km', max_digits=6, null=True),
        ),
    ]
