# Generated by Django 5.2.16 on 2026-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0056_order_route_distance_exact_order_route_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='route_distance_source',
            field=models.CharField(blank=True, choices=[('osrm', 'Road distance'), ('straight_line', 'Straight line'), ('zone_estimate', 'Zone estimate')], default='', help_text='Which method produced route_distance_km — a road distance is a measurement, the other two are approximations', max_length=20),
        ),
    ]
