# Generated by Django 5.2.16 on 2026-07-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0057_order_route_distance_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label_print_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times a waybill has been printed — reprints are expected, not errors.'),
        ),
        migrations.AddField(
            model_name='order',
            name='label_printed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When a waybill for this order was last printed. Null = never printed.', null=True),
        ),
    ]
