# Generated by Django 5.2.16 on 2026-07-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_order_label_print_count_order_label_printed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedrivesource',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Last successful automatic/manual sync fetch of this file', null=True),
        ),
        migrations.AddField(
            model_name='onedrivesource',
            name='last_sync_count',
            field=models.PositiveIntegerField(default=0, help_text='Rows seen during the last sync fetch'),
        ),
    ]
