# Generated by Django 5.2.16 on 2026-08-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_onedrivesource_last_sync_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='field_name',
            field=models.CharField(choices=[('order_status', 'Order Status'), ('task_status', 'Task Status'), ('verification_status', 'Verification Status'), ('cod_status_by_staff', 'COD Status'), ('dl_task_status', 'Delivery Task Status'), ('pickup_status', 'First-Mile Pickup'), ('driver_change', 'Driver Assignment'), ('dl_task_publish', 'Published to Fleet'), ('order_edited', 'Order Edited'), ('task_edited', 'Task Edited'), ('item_deleted', 'Item Deleted'), ('cod_correction', 'COD Correction'), ('location_update', 'Location Updated')], max_length=50),
        ),
    ]
