# Generated by Django 5.2.16 on 2026-08-08 17:11

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0060_alter_orderstatushistory_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbarcode',
            name='barcode',
            field=models.ImageField(blank=True, default='business/orders/barcode.png', null=True, upload_to='business/orders/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif']), core.validators.MaxFileSizeValidator(2)]),
        ),
    ]
