# Generated by Django 5.2.16 on 2026-08-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_alter_orderbarcode_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_note',
            field=models.CharField(blank=True, default='', help_text="Instruction for the scheduled delivery, e.g. 'Birthday — do not deliver early'", max_length=160),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_occasion',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('wedding', 'Wedding'), ('gift', 'Gift / Surprise'), ('event', 'Event / Party'), ('customer_request', 'Customer requested this day'), ('restock', 'Restock / Business schedule'), ('other', 'Other')], default='', help_text='Why this order must land on the scheduled date (birthday, event, ...)', max_length=30),
        ),
    ]
