# Generated by Django 5.2.16 on 2026-08-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_order_scheduled_note_order_scheduled_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_area_name',
            field=models.CharField(blank=True, default='', help_text='Neighbourhood within the delivery zone, resolved from the pin', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_area_source',
            field=models.CharField(blank=True, choices=[('pin', 'Nearest area to the delivery pin'), ('only_area', 'Only area in the zone'), ('same_as_zone', 'Suppressed — area name repeats the zone name'), ('unresolved', 'Could not be resolved')], default='', help_text='How delivery_area_name was produced — empty means never computed', max_length=20),
        ),
    ]
