# Generated by Django 5.2.16 on 2026-09-08 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_ordercomments_authorship_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='p2p_customer',
            field=models.ForeignKey(blank=True, help_text='Personal sender for a P2P booking. Null for every business order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2p_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='package_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Package weight in kg. Priced on for P2P; blank elsewhere.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('normal_delivery', 'Normal Delivery'), ('pick_and_drop', 'Pick and Drop')], db_index=True, default='normal_delivery', help_text='Order type: normal delivery or pick and drop', max_length=20),
        ),
    ]
