# Generated by Django 5.2.16 on 2026-09-08 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0065_order_p2p_customer_order_package_weight_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercomments',
            name='staff_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercomments',
            name='staff_read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_comments_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ordercomments',
            index=models.Index(fields=['order', 'author_role', 'staff_read_at'], name='ord_comment_unread_idx'),
        ),
    ]
