# Generated by Django 5.2.16 on 2026-09-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0067_ordercomments_backfill_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporder',
            name='source_type',
            field=models.CharField(choices=[('onedrive', 'OneDrive'), ('google_sheet', 'Google Sheet'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('public_link', 'Public Link'), ('webhook', 'Webhook'), ('custom_api', 'Custom API')], db_index=True, default='onedrive', max_length=20),
        ),
    ]
