# Generated by Django 5.2.16 on 2026-09-18 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0041_repair_mis_flagged_fulfillment'),
        ('delivery', '0051_backfill_address_area_and_slot'),
        ('orders', '0068_alter_temporder_source_type'),
        ('warehouse', '0012_alter_warehouse_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collect_back',
            field=models.BooleanField(default=False, help_text='Driver takes the original items back on this visit — an exchange, not a re-send.'),
        ),
        migrations.AddField(
            model_name='order',
            name='replacement_reason',
            field=models.CharField(blank=True, choices=[('wrong_item', 'Wrong Item Sent'), ('damaged', 'Damaged in Transit'), ('lost', 'Lost in Transit'), ('missing_items', 'Items Missing from Package'), ('failed_delivery', 'Failed Delivery'), ('size_exchange', 'Exchange — different item or size'), ('other', 'Other')], default='', help_text='Why the replacement went out. Blank on a first delivery.', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='The original order this one re-sends. Null for a first delivery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'replaces'], name='ord_biz_replaces_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('replaces', models.F('id')), _negated=True), name='ord_replacement_not_self'),
        ),
    ]
