# Generated by Django 5.2.16 on 2026-09-18 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0069_order_replacement_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='replacement_order',
            field=models.OneToOneField(blank=True, help_text='The replacement order sent for this return, if goods were re-sent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_return', to='orders.order'),
        ),
    ]
