# Generated by Django 5.2.17 on 2026-09-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0072_alter_orderstatushistory_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('wrong_item', 'Wrong Item Received'), ('damaged', 'Item Damaged'), ('not_as_described', 'Not As Described'), ('customer_changed_mind', 'Customer Changed Mind'), ('duplicate_order', 'Duplicate Order'), ('undelivered', 'Never delivered — returned to shipper'), ('other', 'Other')], max_length=30),
        ),
    ]
