# Generated by Django 5.2.17 on 2026-09-23 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0073_alter_returnrequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_order',
            field=models.OneToOneField(blank=True, help_text='The return-pickup order raised to collect these goods, if one was.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_return_pickup', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('normal_delivery', 'Normal Delivery'), ('pick_and_drop', 'Pick and Drop'), ('return_pickup', 'Return Pickup — Collect from Customer')], db_index=True, default='normal_delivery', help_text='Order type: normal delivery or pick and drop', max_length=20),
        ),
    ]
