# Generated by Django 5.2.17 on 2026-09-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0074_returnrequest_pickup_order_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('to_review', 'Hold for Review'), ('ready_to_pickup', 'Ready to pickup'), ('publish', 'Published'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], db_index=True, default='to_review', max_length=100),
        ),
    ]
