# Generated by Django 5.2.17 on 2026-09-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0045_business_customer_pays_delivery'),
        ('orders', '0075_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='collection_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default charge for the collection. Staff can still override it when they schedule the pickup.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='customer_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='customer_whatsapp',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='dl_building',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='dl_street',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='dl_zone',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='external_reference',
            field=models.CharField(blank=True, default='', help_text="The client's own order or invoice number for goods we did not deliver. Shown where an order number would be.", max_length=64),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='package_description',
            field=models.CharField(blank=True, default='', help_text='What is coming back. Stands in for the order lines a standalone claim does not have.', max_length=255),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='package_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_location',
            field=models.ForeignKey(blank=True, help_text='Where the driver drops the collected goods. Standalone claims only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_return_requests', to='business.pickuplocation'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The outbound order these goods went out on. Null when we did not deliver them.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order'),
        ),
    ]
