# Generated by Django 5.2.17 on 2026-09-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0076_returnrequest_collection_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dl_amount_source',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('rate_card', 'Distance rate card'), ('manual', 'Set by staff')], default='', max_length=10),
        ),
    ]
