# Generated by Django 5.2.17 on 2026-09-26 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0077_order_dl_amount_source'),
        ('product', '0010_product_label_print_count_product_label_printed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Set on a hand-added line. Read line_product, never this.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_lines', to='product.product'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hand-added lines only; an order line carries its own.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='The outbound line this came off, when there was one.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='orders.orderitem'),
        ),
    ]
